### ISSUE TITLE
min.node.size.

### ISSUE THREAD

**Issue by mutian-niu** [imbs-hl/ranger#102]
##Hello Marvin @mnwright , 

I really appreciate your efforts on writing this package, it is really fast!

I just have a quick question on the min.node.size. The default of min.node.size for regression is 5, however, in some RF model that we fit, I found the average node size is smaller than 5 (I have 15000 observations and the approximate average tree size is around 4000, so about 3 observations per terminal). I looked up the R code, it seems like it is set to 0 if not specified. Could you please check the setting of min.node.size? 

Btw, I was just wondering if it there a way to compute the tree size of the model? Thank you!!

Sincerely,
Mutian

**Comment by mnwright** [comment]
The `min.node.size` is evaluated before the splitting, meaning that smaller nodes can occur. The 0 in the R code is mapped to response-specific default values later in C++. 
This is also described in the help on `ranger()`: 

> Note that for classification and regression nodes with size smaller than min.node.size can occur, like in original Random Forest. For survival all nodes contain at least min.node.size samples. 

Note the difference for survival forests. 

To get the number of nodes per tree you could use
`sapply(rf$forest$split.varIDs, length)`
where `rf` is a ranger object with `write.forest = TRUE`.
