### ISSUE TITLE
No error by importance() if importance = "none"

### ISSUE THREAD

**Issue by Thie1e** [imbs-hl/ranger#114]
The importance function should throw an error if the ranger model was fit with `importance = "none"` (the default) as defined in importance.R:

    if (is.null(x$variable.importance) | length(x$variable.importance) < 1) {
        stop("No variable importance found. Please use 'importance' option when growing the forest.")
    }

Currently it returns a zero for every independent variable:

    library(ranger)
    mod <- ranger(Species ~ ., data = iris)
    importance(mod)
    # [1] 0 0 0 0

It happens in 0.4.0, 0.5.0 and 0.5.4. I'll try to look into it, but don't let that stop you from fixing this...

**Comment by mnwright** [comment]
Thanks! Fixed.
