### ISSUE TITLE
Slow OOB prediction for survival data with many unique time points

### ISSUE THREAD

**Issue by Mestalbet** [imbs-hl/ranger#117]
Running on Ubuntu 16.04 with R3.3.0, I notice that ranger uses all cores while the "growing tree" output is printed. But after the last printed message, for example:
"Growing trees.. Progress: 95%. Estimated remaining time: 9 seconds"
The computation continues on a single core for a very long time. Do you know why this could be? Thanks!!!

**Comment by krlmlr** [comment]
Prediction seems to run in parallel but also have a nontrivial serial component. It would be great if prediction could be parallelized entirely.

**Comment by mnwright** [comment]
For what kind of data is this happening? How long does the serial part take, compared to the parallel part?

**Comment by krlmlr** [comment]
I have ~2m observations for prediction with 10-20 independent variables in the forest. On a 24-core machine, the serial part actually takes somewhat longer than the parallel part (both just a few seconds, but still).

Please let me know if you want me to be more specific.

**Comment by Mestalbet** [comment]
Hi,

This is happening for a survival forest for me. The data has about 2m observations. 

Ranger is called as follows:
rmodel <- ranger(formula = Surv(time,event) ~ f1+f2+f3+f4,  data = survdata,
                         seed = 1234,
                         importance = 'permutation',
                         mtry = 2,
                         verbose = TRUE,
                         num.trees = 50,
                         write.forest=TRUE)
where f1-4 are nominal factors. 

If I can provide you with anything that will aid your diagnosis - please let me know. 

Thanks,
Noah

**Comment by Mestalbet** [comment]
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
<30s

And then 4 hours on one CPU.

**Comment by mnwright** [comment]
I've found the problem and it's specific to survival. For the OOB prediction error, the C-Index is computed and for that all pairs of observations need to be compared. 
It may be possible to parallelize and/or speedup the C-Index but still it will be slow to compare all pairs. 
An alternative would be an option to disable computation of OOB prediction errors after training.

**Comment by Mestalbet** [comment]
Cool! Thanks for looking into it. Another option is to just take random subsets of observation pairs and calculate the C-index for each subset. This is then fully parallelizable and with enough subsets it should converge on the C-index calculated for every pair.

**Comment by mllg** [comment]
You could order your survival times first which reduces the number of comparison required for each pair. If you need to calculate the C-index for multiple variables, you only need to order once.

See [here](https://github.com/mllg/fmrmr/blob/master/src/mrmr.cpp#L28) for an example.

**Comment by mnwright** [comment]
I've looked into this again. The major problem is not the C-index computation but the OOB prediction for huge numbers of unique time points (n x n matrix for continuous time points). Is this still a major bottleneck for someone?

**Comment by krlmlr** [comment]
I remember having this problem for "regular" (non-survival) data, but I'm not actively working on that project at this time.

**Comment by ginoa** [comment]
This seems to be a major bottleneck for me.
OOB prediction takes ages even with only 2k observations. 1000 unique survival times.

**Comment by david-clifford** [comment]
The lack of insight into how long this stage of the modelling takes is putting me off from using ranger for a problem I'm tackling. Tree building takes on the order of 1 or 2 minutes across multiple cores but 45 minutes later the OOB prediction is still running on a single core. I'm running with `verbose=TRUE` so even adding more insight into how long it might take could help here. I have approximately 500k observations, 50 covariates, and 15 time points to consider.

**Comment by david-clifford** [comment]
Thanks for the super quick response Marvin. I'll check out this and let you know how it goes.

**Comment by mnwright** [comment]
Merged.
