### ISSUE TITLE
ranger-0.5.0 for R build error

### ISSUE THREAD

**Issue by blueagave** [imbs-hl/ranger#121]
I'm getting the errors below when attempting to install ranger-0.5.0 for R-3.2.4 on Linux.  Running:

> install.packages("ranger")

Any advice?
.....
I/usr/local/packages/r-3.2.4/lib64/R/include -DNDEBUG -DR_BUILD -I/usr/local/include -I"/usr/local/packages/r-3.2.4/lib64/R/library/Rcpp/include"      -c utility.cpp -o utility.o
/bin/sh: I/usr/local/packages/r-3.2.4/lib64/R/include: No such file or directory
make: [utility.o] Error 127 (ignored)
-shared -L/usr/local/packages/r-3.2.4/lib64/R/lib -L/usr/local/lib64 -o ranger.so AAA_check_cpp11.o Data.o DataChar.o DataDouble.o DataFloat.o Forest.o ForestClassification.o ForestProbability.o ForestRegression.o ForestSurvival.o RcppExports.o Tree.o TreeClassification.o TreeProbability.o TreeRegression.o TreeSurvival.o rangerCpp.o utility.o -L/usr/local/packages/r-3.2.4/lib64/R/lib -lR
/bin/sh: line 2: -shared: command not found
make: **\* [ranger.so] Error 127
ERROR: compilation failed for package ‘ranger’
- removing ‘/usr/local/packages/r-3.2.4/lib64/R/library/ranger’
  ...
  Warning message:
  In install.packages("ranger") :
  installation of package ‘ranger’ had non-zero exit status

Thanks,
Tom

**Comment by mnwright** [comment]
Are other `Rcpp` packages working? Which version of g++ is installed on your system?

**Comment by blueagave** [comment]
Yes, Rcpp loads successfully.  Using gcc-5.3.0

**Comment by caewok** [comment]
Check the Makeconf file for R. I saw a similar problem trying to install feather, and finally determined that the CXX1X params were not set correctly after an upgrade. Find and edit the Makeconf file. If you don't know what gcc compiler you have, try typing gcc in the terminal and then tab; if you have any gcc command it should list it.

To edit the Makeconf, use sudoedit, changing it if necessary to the correct path for your Makeconf file:
`sudoedit R/etc/Makeconf`

In the file, look for these lines, and change them if blank. Make sure you use a gcc compiler that is actually installed in your system:
```
CXX1X = gcc-4.8
CXX1XFLAGS = -fpic
CXX1XPICFLAGS = 
CXX1XSTD = -std=c++11
```

**Comment by jarretinha** [comment]
Microsoft R (ubuntu version) has CXX1X, CXX1XFLAGS, CXX1XSTD empty. After providing the above values (without version), compilation worked normally.
