### ISSUE TITLE
are there any plans for a partial dependency plot

### ISSUE THREAD

**Issue by jwijffels** [imbs-hl/ranger#122]
as in randomForest:::partialPlot.randomForest
or as in randomForestSRC::plot.variable

**Comment by mnwright** [comment]
I'd love to have them, but it's not top priority at the moment and might take a while... You are very welcome to contribute!

**Comment by jwijffels** [comment]
I'll see what I can do at the R package somewhere in October.
Any preference regarding naming?

**Comment by mnwright** [comment]
Thanks! No special preference in naming, just don't abbreviate too much.

**Comment by jakob-r** [comment]
@jwijffels As ranger is integrated in *[mlr](https://github.com/mlr-org/mlr)* you can use the partial dependency plot function from mlr:

```r
library(mlr)
lrn.classif = makeLearner("classif.ranger", predict.type = "prob")
fit.classif = train(lrn.classif, iris.task)
pd = generatePartialDependenceData(fit.classif, iris.task)
plotPartialDependence(pd)
#plotPartialDependenceGGVIS(pd)
```
![image](https://cloud.githubusercontent.com/assets/1888623/19229711/eb6ac8ae-8ecf-11e6-99aa-67c89032633a.png)

You can also check out the [mlr tutorial on partial dependences](http://mlr-org.github.io/mlr-tutorial/release/html/partial_dependence/index.html#generating-partial-dependences)

**Comment by jwijffels** [comment]
thanks, this solves the question then
