### ISSUE TITLE
Save a model on disk

### ISSUE THREAD

**Issue by traffinot** [imbs-hl/ranger#124]
Thanks for the package, it is very useful. 
I was wondering if there is a way to save a model on disk and then load it again (as there is in the package extraTress for example) ? 
It is very helpful when you re-use a model every day on a big dataset.

**Comment by mnwright** [comment]
Why not simply use saveRDS()? The ranger forest objects are already serialized.

**Comment by stillmatic** [comment]
a bit of self promotion -
