### ISSUE TITLE
Class names and predicted probability columns might not match

### ISSUE THREAD

**Issue by Eric2333** [imbs-hl/ranger#125]
I am using version 0.5.0 and I spot a problem in prediction results. So, the predicted probability for a classification task is stored in a named matrix. The names of the column is in the same order of the levels of the target variable(which is a factor), however, the actual order of the columns is based on the "first appearance" order in the target variable. Thus, if those two order aren't the same, then the prediction matrix is totally messed up. Here is a demo code:
```
data("iris")
iris = rbind(iris[iris$Species=='virginica',],
             iris[iris$Species=='setosa',],
             iris[iris$Species=='versicolor',])


ii = sample(1:2, nrow(iris), replace = TRUE)
rg.iris <- ranger(Species ~ ., data = iris[ii==1,], write.forest = TRUE, probability = TRUE, importance = 'impurity', classification = TRUE)
bb = predict(rg.iris, iris[ii==2, 1:4])

cbind(bb$predictions, iris$Species[ii==2])
```
The levels for Species is in the order of setosa, versicolor, virginica, while I manually change their first appearance order into virginica, setosa, versicolor.

**Comment by mnwright** [comment]
This was a bug, which is already fixed here on Github, see #95. Unfortunately, the changes are not on CRAN yet.
