### ISSUE TITLE
Interactions between features

### ISSUE THREAD

**Issue by PhilippPro** [imbs-hl/ranger#130]
It would be interesting to have a matrix which shows the interaction between two features based on the random forest (@RaphaelCouronne pointed me to this). 

There is an issue about this on the Breiman page (Interaction section): https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm#inter

Neither randomForest, nor randomForestSRC has implemented this yet.

**Comment by PhilippPro** [comment]
I have to correct myself, there is the function find.interaction in the randomForestSRC package.

**Comment by mnwright** [comment]
Yes that would be nice. Unfortunately, interactions are very hard to detect... See our paper in BMC Bioinformatics: http://dx.doi.org/10.1186/s12859-016-0995-8. 
To reliably detect interactions we have to work on new methods first.
