### ISSUE TITLE
Installation of R Results in Error

### ISSUE THREAD

**Issue by Autris** [imbs-hl/ranger#134]
Installation of R from the Cran repository results in:
_Error: ranger requires a real C++11 compiler. You probably have to update gcc_

I've:
- Updated gcc to 4.4.7
- Installed Rcpp to latest version

OS Information:
- RedHat 6.8

Software Information:
- R 3.2.3

**Comment by mnwright** [comment]
gcc 4.4.7 is still too old. You'll need at least 4.7. 
I should add this information to the error message.
