### ISSUE TITLE
Error when irrelevant column contains NA

### ISSUE THREAD

**Issue by mayer79** [imbs-hl/ranger#139]
I am running the CRAN version 0.6.0 of ranger and am stuck with the following problem in the formula interface: As soon as there is a missing value in an unused column, an error is shown.

```
iris[1, "Sepal.Width"] <- NA
ranger(Species ~ Sepal.Length, data = iris)
# Error: Missing data in columns: Sepal.Width.
```
Any idea how to fix that one?

BTW `ranger` is super

**Comment by mnwright** [comment]
Fixed.

**Comment by mayer79** [comment]
Excellent, thank you

**Comment by muschellij2** [comment]
May be useful to have a different message when you have a factor in the model and put in new data set and then when coercing variable to factor you get `NA`.  So you can get `any(is.na(df))` to `FALSE`, but this error.  The error results after coercion of column to factor as the column has elements not within the levels of the data used to train the `model`.

**Comment by mnwright** [comment]
Thanks. Please reopen if necessary.
