### ISSUE TITLE
Error with using predict.ranger for "Probability estimation" Error in result$predictions[, forest$levels, drop = FALSE] :    subscript out of bounds

### ISSUE THREAD

**Issue by thengl** [imbs-hl/ranger#143]
I've started getting an error message with v0.6-1 of ranger when I run predict using a : 

```
> v = round(predict(mRF, m@data, probability=TRUE)$predictions*100)
Error in result$predictions[, forest$levels, drop = FALSE] : 
  subscript out of bounds
```

In my case the number of levels used for model training and number of levels that comes out in the final model is a bit different, so maybe that causes problems:

```
> str(attr(mRF$predictions, "dimnames")[[2]])
 chr [1:291] "Acraquox" "Acrudox" "Alaquods" "Albaqualfs" "Albaquults" "Alorthods" ...
> str(mRF$forest$levels)
 chr [1:318] "Acraquox" "Acrorthox" "Acrudox" "Acrustox" "Alaquods" "Albaqualfs" ...
```

I see that you have [changed the code recently](https://github.com/imbs-hl/ranger/commit/7ae6a845e1026bf1153c49742764021e1c840475#diff-d25034c07e94e9ebd6bff7e9ff029e14) so that subsetting of the results is done with `drop=FALSE` (maybe that causes problems?). Let me know if I can send you my model and prediction locations for testing.

**Comment by thengl** [comment]
I've tried with the older version of the package and I still get:

`Error in result$predictions[, forest$levels] : subscript out of bounds`

**Comment by thengl** [comment]
I solved the problem by dropping the levels that have no observations using:

```
x = x[complete.cases(x),]
x[,j] = droplevels(x[,j])
mRF = ranger::ranger(formulaString, data=x, importance="impurity", write.forest=TRUE, probability=TRUE)
```

**Comment by mnwright** [comment]
Good to hear that you solved the problem. 

I could reproduce the issue: 
```R
library(ranger)
rf <- ranger(Species ~ ., iris[1:100, ], probability = TRUE)
predict(rf, iris)
```
Is throwing an error, while 
```R
rf <- ranger(Species ~ ., droplevels(iris[1:100, ]), probability = TRUE)
predict(rf, iris)
```
is working fine. 

So should we just call `droplevels()`on the outcome before growing the forest? We cannot predict on levels not there in the training phase, anyway.

**Comment by thengl** [comment]
Yes that sounds reasonable to me. There is no need to keep record of classes that have no observations.
