### ISSUE TITLE
how to choose parameters for ranger? 

### ISSUE THREAD

**Issue by lixin4306ren** [imbs-hl/ranger#144]
I tried to use ranger for gwas analysis. My dataset includes 95 individuals, 754,909 SNPs, the phenotype is body weight (continuous variable). I tried many different combinations of parameters, but always got very high OOB, 98%~100%. I'm wondering how to choose those parameters for my analysis? Any guide for that? Thanks.

**Comment by rfcv** [comment]
You do a grid search. Basically, you loop through different hyperparameters (mtry, min.node.size, num.trees, sample.fraction. Then you test the results of the model on data that it wasn't trained on. Repeat this multiple times for each hyperparameter selection (cross validation).

**Comment by mnwright** [comment]
Closed. Please re-open in case of questions.
