### ISSUE TITLE
Too many levels in unordered categorical variable error with high dimensionality column

### ISSUE THREAD

**Issue by krishnateja614** [imbs-hl/ranger#146]
I recently stumble upon Ranger package and ideally it should be perfect for my project since I'm dealing with a column with high dimensionality (~4000, all right not so high dimensional :)) and Ranger handles that natively. The dimensions are not ordered in my column and hence I'm setting the parameter **"respect.unordered.factors=TRUE"** which is giving me the following error, **"Too many levels in unordered categorical variable col_1. Only 63 levels allowed on this system. Consider ordering this factor"** .I installed the R package from CRAN and not the dev version. Can someone help me how to resolve this error?. What I could gather was this error is present in the randomforest fortran package but I don't know what caused this error in my setting?

**Comment by mnwright** [comment]
Which version of ranger are you using? With the newest CRAN version (0.6.0) this should work.

**Comment by krishnateja614** [comment]
Thanks for pointing this out. Even though I ran install.packages("ranger"), it didn't update from 0.4.0 to 0.6.0 and packageVersion was still showing 0.4. I installed it manually with source files from CRAN and now that I'm on 0.6.0, the error hasn't occurred.Thanks for pointing this out.

**Comment by GearFear** [comment]
Deal with same issue, using cpp_version, version 0.7.1

**Comment by Datou0718** [comment]
I encountered the same problem with cpp_version, the dimension is about 135 but it printed "Error: Too many levels in unordered categorical variable col_1. Only 63 levels allowed on this system. Ranger will EXIT now.". The ranger version I'm using is 0.16.1 and I have no idea how to solve it.
