### ISSUE TITLE
Ranger favours numeric features?

### ISSUE THREAD

**Issue by MiksLynx** [imbs-hl/ranger#148]
Hi,
After a few uses on different datasets I have started to notice that ranger favours numeric features in comparison with 'randomforest' package in which I have not observed this.
To compare I run both algorithms with same parameters and datasets and while with 'randomforest' package i get a 50%/50% split between factor/numeric features in top20 based on importance(MeanGiniIncrease),
in 'ranger' package i get 100% numeric features in top20 based on importance.

So have anyone else noticed this and is this intended?

**Comment by mnwright** [comment]
Did you set the `respect.unordered.factors` option in ranger?
Could you share the code of your comparisons?

**Comment by mnwright** [comment]
Closed. Please re-open in case of questions.
