### ISSUE TITLE
ranger favours variables with lower indexes for mtry > nVar/2

### ISSUE THREAD

**Issue by piotrszul** [imbs-hl/ranger#151]
We have been using ranger recently for a GWAS like study and we noticed it has a tendency to boost  (gini) importances for variables with low indexes for mtry >= no_variables/2.

For example for a random two class response ranger produces the following rankings:

mtry = no_variables/2 - 1

X1022     X8813      X957     X4647     X4530     X4055     X7388     X4067           
0.8856694 0.8132811 0.7967820 0.5972233 0.5873035 0.5766025 0.5001176 0.3920248 

mtry =  no_variables/2 

X1        X2        X3        X4        X5        X6        X8      X957   
1.8599748 1.2381851 1.0830624 0.9947045 0.9438055 0.8752772 0.7527798 0.7397533 

The first one makes sense, but in the second case clearly the importance is highly correlated with the index. 

This is also true for non-random responses in which case variables of lower indexes obscure the importance of true predictors.

See:  [ranger_no_permutation.R.txt](https://github.com/imbs-hl/ranger/files/668863/ranger_no_permutation.R.txt)

We believe this behaviour is caused by two different procedures used to select variables for split, as in:

https://github.com/imbs-hl/ranger/blob/f68c15bf267846549719017ff1a0f42f02830ccc/source/src/utility/utility.cpp

```
void drawWithoutReplacementSkip(std::vector<size_t>& result, std::mt19937_64& random_number_generator, size_t max,
    std::vector<size_t>& skip, size_t num_samples) {
	if (num_samples < max / 2) {
		drawWithoutReplacementSimple(result, random_number_generator, max, skip, num_samples);
	} else {
		drawWithoutReplacementKnuth(result, random_number_generator, max, skip, num_samples);
	}
}
```

drawWithoutReplacementKnuth returns candidates ordered by index, which causes this effect (as it favours variables with lower indexes in case of equal decrease of gini).

We believe this effect is undesirable and the order of candidates should be random.

**Comment by mnwright** [comment]
Yes, this seems to be right. Variables are tried in order and splits are only used if the decrease in impurity is larger than before. As a consequence, if many variables have the same effect, the first one is selected for splitting. As you have noted correctly, the indices of the random subset are still in order if Knuth's algorithm is used. 

Thanks for pointing this out. I'll see if I can find a computationally affordable solution.

**Comment by mnwright** [comment]
Fixed. I've switched to the Fisher Yates algorithm instead of Knuth's algorithm S. Actually, this should even be faster in most cases.

**Comment by piotrszul** [comment]
I have run my test code on the fixed version and it appears not to favour low index variables any longer.
Thank you!
