### ISSUE TITLE
[QUESTION] ranger with genomic data set

### ISSUE THREAD

**Issue by thierrygosselin** [imbs-hl/ranger#152]
Hi Marvin, 

I'm using `ranger` to impute genomic RADseq dataset (with lots of missing data). I'm looking at the best strategy to account for potential correlation between variables

Example:
* let say I'm only interested in 1 population in a tidy dataset with 5 columns (below)
* the number of SNP/LOCUS can change depending on `LOCUS`, some locus have 3 SNPs others only have 1
* all columns are factors
* `GENOTYPE` is not biallelic.

|POP_ID|INDIVIDUALS|LOCUS|SNP|GENOTYPE|
|:---|:---|:---|:---|:---|
|1|1| 1|1|001002|
|1|1| 1|2|003003|
|1|1| 2|1|001002|
|1|1| 2|2|003003|
|1|1| 2|3|001001|
|1|1| 3|1|001001|
|1|2| 1|1|001001|
|1|2| 1|2|002003|
|1|2| 2|1|001001|
|1|2| 2|2|003003|
|1|2| 2|3|004004|
|1|2| 3|1|001003|

Currently, if I'm using ranger with this dataset in long/tidy format :

```
test <- ranger::ranger(
    formula = GENOTYPE ~ INDIVIDUALS + LOCUS + SNP,
    data = complete.data,
    num.trees = 200, 
    num.threads = 32)
```

*Strategy/questions:*

**Question 1**

With this, because `GENOTYPE` is factored, I will get GENOTYPE values that should not be observed for certain `LOCUS/SNP` combo. So what's wrong with this ?

**Question 2**
To circumvent this, if my locus are **fully independent**, I could run `ranger` separately for each locus with formula like this:
`formula = GENOTYPE ~ INDIVIDUALS + SNP` , or should I spread my data set by SNP ?, so that while treating each locus separately, sometimes the dataset as 1 column for SNP and sometimes it as 3 columns of SNP (SNP1, SNP2, SNP3):

pop1, ind1, locus2 with 3 SNP:

|INDIVIDUALS|SNP1|SNP2|SNP3|
|:---|:---|:---|:---|
|1|001002|003003|001001|

Thanks
Thierry

**Comment by thierrygosselin** [comment]
found a solution: xgboost

**Comment by mnwright** [comment]
Sorry, I just didn't have time to go through your problem. Good to hear you found a solution.
