### ISSUE TITLE
Ranger does not split on interactions terms in a formula

### ISSUE THREAD

**Issue by walterwzhang** [imbs-hl/ranger#155]
Hi,

Let's say that I have a data.frame object `DT` with 3 columns, `y`, `x1`, `x2`. I want to the ranger function to explicitly fit `y` onto `x1`, `x2`, and `x1*x2`. If I construct a formula object, `y ~ x1 * x2` (or even just `y ~ x1:x2`), ranger will will only split on the "independent variables" `x1` and `x2` during the fit. Is there anyway to get ranger to split on the interaction term `x1*x2` through the model formula implementation?

I am running `ranger(y~x1*x2, DT,   num.trees = 100, write.forest = T)` in above example with ranger version 0.6.0. Further, I am examining ranger's variable splits by looking at the ranger object's `$forest$split.varIDs` and matching them with `$forest$independent.variable.names`. 

I also understand that I can manually generate a fourth column in the `DT` defined above that contains the `x1*x2` data. Then using the 'y~.' formula, I can trick ranger into considering the interaction term as an independent variable, and ranger will split on it. 

Thank you for your help and for making this package available.

**Comment by mnwright** [comment]
Currently only `+` and `.` are considered in the formula interface. I'll try to find a solution.

**Comment by mayer79** [comment]
In my opinion, the current behaviour is more natural when it comes to random forests. For instance, in this small example, I would not want to add an extra interaction term in `ranger`:

```
fit <- lm(Sepal.Width ~ Sepal.Length * Petal.Length, data = iris)
fit2 <- ranger(formula(fit), data = iris)
```

**Comment by mnwright** [comment]
I've found a solution by parsing the formula with my own function. It should even be faster than before. 

@mayer79 Wouldn't you use `Sepal.Length + Petal.Length` to include both variables, `Sepal.Length : Petal.Length` for the interaction only and `Sepal.Length * Petal.Length` for both variables and the interaction?

**Comment by mayer79** [comment]
ok, fine!
