### ISSUE TITLE
Memory issues with large dataset

### ISSUE THREAD

**Issue by afonsoguerra** [imbs-hl/ranger#158]
Hi,

Thanks for your great work that allows me regularly to use random forests faster than what is possible with the randomforest package in R. 

Unfortunately, in my latest dataset ranger crashes.  Command line below, error and session info underneath. 

The randomforest package is deadly slow but runs without issue with the same dataset. 

rf.ranger <- ranger(class~., data = data1, num.trees = 1001, mtry = 236, write.forest = FALSE, probability = FALSE, num.threads = 2, importance="none", save.memory = TRUE)

 *** caught segfault ***
address 0xffffffffef1d32fc, cause 'memory not mapped'

Traceback:
 1: terms.formula(formula, data = data)
 2: terms(formula, data = data)
 3: model.frame.default(formula, data, na.action = na.fail)
 4: model.frame(formula, data, na.action = na.fail)
 5: ranger(class ~ ., data = data1, num.trees = 1001, mtry = 236,     write.forest = FALSE, probability = FALSE, num.threads = 2,     importance = "none", save.memory = TRUE)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
Segmentation fault: 11

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ranger_0.6.0

loaded via a namespace (and not attached):
[1] Rcpp_0.12.9

**Comment by mnwright** [comment]
Does it work if you use the `dependent.variable.name` interface instead of a formula? 
Could you please describe your dataset in more detail? Maybe give an example?

**Comment by afonsoguerra** [comment]
Thanks for the tip, I will try that and report back.

The dataset consists of genetic expression data coming from a sequencing experiment, it consists of 40000 genes (measurements) and about 500 entities I am trying to train/classify on. Due to the size and nature of the dataset I cant really share it, but I’m quite happy to spend some time helping to understand the problem and debug it.



On 3 Feb 2017, at 07:21, Marvin N. Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it work if you use the dependent.variable.name interface instead of a formula?
Could you please describe your dataset in more detail? Maybe give an example?

**Comment by afonsoguerra** [comment]
Further to my reply this morning, I can confirm that adding the training variable to the dataset and using it as dependent.variable.name did run the training without problem. 

rf.ranger <- ranger(dependent.variable.name="class", data = data1, num.trees = 1001, mtry = 236, write.forest = FALSE, probability = FALSE, num.threads = 2, importance="none", save.memory = TRUE)

Thanks for solving the problem! I'm still happy to help further debug the situation if you are interested. Otherwise feel free to close the issue.

**Comment by mnwright** [comment]
Closed. Please re-open in case of questions.
