### ISSUE TITLE
Ranger 1D Regression seems a bit off

### ISSUE THREAD

**Issue by jakob-r** [imbs-hl/ranger#160]
Look at this example
```r
set.seed(1)
library(smoof)
library(ggplot2)
fn = makeSphereFunction(1)
autoplot(fn)
data = generateGridDesign(getParamSet(fn),resolution = 10L)
data$y = apply(data, 1, fn)

model1 = randomForest::randomForest(y~x, data)
model2 = ranger::ranger(y~x, data = data)

predData = generateGridDesign(getParamSet(fn), 100L)
p1 = predict(model1, newdata = predData)
p2 = predict(model2, data = predData)
predData$RF = p1
predData$Ranger = p2$predictions
autoplot(fn) + geom_point(data = data, aes(x = x, y = y)) + geom_line(data = reshape2::melt(predData, id.var = "x"), mapping = aes(x = x, y = value, col = variable))
```
which generates this output:
![image](https://cloud.githubusercontent.com/assets/1888623/22737707/86eca7dc-ee04-11e6-9655-05d47c9d3419.png)

For other 1D regressions we observed the same "displacement", that looks a bit strange.

**Comment by jakob-r** [comment]
For the 2-dimensional case it looks similarly strange:
```r
set.seed(1)
library(smoof)
library(ggplot2)
fn = makeSphereFunction(2)
autoplot(fn, render.levels = TRUE)
data = generateGridDesign(getParamSet(fn),resolution = 10L)
data$y = apply(data, 1, fn)

model1 = randomForest::randomForest(y~., data)
model2 = ranger::ranger(y~., data = data)

predData = generateGridDesign(getParamSet(fn), 100)
p1 = predict(model1, newdata = predData)
p2 = predict(model2, data = predData)
predData$RF = p1
predData$Ranger = p2$predictions
mdata = reshape2::melt(predData, id.var = c("x1", "x2"))
ggplot() + geom_tile(data = mdata, mapping = aes(x = x1, y = x2, fill = value)) + facet_wrap(~variable) + geom_point(data = data, aes(x = x1, y = x2), color = "white")
```
![image](https://cloud.githubusercontent.com/assets/1888623/22738623/7bc25baa-ee08-11e6-9b4e-ef90c613fba0.png)

**Comment by mnwright** [comment]
Thanks! Should be fixed with PR #161. 
We were splitting at the values occurring in the data and not in between. Now, we always split at the midpoint between two values. Shouldn't be a large difference on larger datasets, but still this is the better approach. 

Also thanks to Tal Galili, who already noticed this. See his paper on arXiv: https://arxiv.org/abs/1611.04561.

**Comment by jakob-r** [comment]
Thanks a lot. Out of couriosity: Have you seen other implementations that don't use that (a+b)/2 split point?

**Comment by mnwright** [comment]
I think `randomForestSRC` splits at A.
