### ISSUE TITLE
Add fixed proportion sampling

### ISSUE THREAD

**Issue by EricArcher** [imbs-hl/ranger#167]
Is it possible to specify different sample sizes for each class rather than just the single `sample.fraction` argument in `ranger`?  

The analogy in the Liaw and Weiner implementation of `randomForest` is their `sampsize` argument which can take an (optionally named) vector as long as the number of classes. For example, if I want to build a forest where every tree has a random 5 setosa, 10 versicolor and 25 virginica samples, I could specify:

```
> library(randomForest)
> rf <- randomForest(Species ~ ., data = iris, sampsize = c(5, 10, 25), replace = F)
> oob.pct <- rf$oob.times / 500
> (1 - tapply(oob.pct, rf$y, mean)) * 50
    setosa versicolor  virginica 
         5         10         25 
```

**Comment by mnwright** [comment]
The exact stratified sampling you described is not possible yet. You could use `case.weights` to approximate that behaviour: 

    library(ranger)
    weights <- rep(NA, nrow(iris))
    weights[iris$Species == "setosa"] <- 5 
    weights[iris$Species == "versicolor"] <- 10 
    weights[iris$Species == "virginica"] <- 25 
    rg <- ranger(Species ~ ., data = iris, case.weights = weights, replace = TRUE, keep.inbag = TRUE, sample.fraction = 40/150)
    inbag <- rowMeans(do.call(cbind, rg$inbag.counts))
    tapply(inbag, iris$Species, mean) * 50
    #     setosa versicolor  virginica 
    #      4.970     10.022     25.008 

If you use `replace=FALSE`, the selection frequencies will be slightly biased because already selected observations are skipped.

**Comment by EricArcher** [comment]
Thanks! That should be close enough. 
Is stratified sampling planned to be implemented?

**Comment by mnwright** [comment]
Yes, I'd like to have it.

**Comment by mnwright** [comment]
Renamed and reopened.

**Comment by mnwright** [comment]
Added. Example: 

````R
library(ranger)
rf <- ranger(Species ~ ., iris, replace = TRUE, keep.inbag = TRUE, 
             sample.fraction = c(0.01, 0.1, 0.5))
inbag <- do.call(cbind, rf$inbag.counts)

colSums(inbag[iris$Species == "setosa", ]) # floor(0.01*150) = 1
colSums(inbag[iris$Species == "versicolor", ]) # floor(0.1*150) = 15
colSums(inbag[iris$Species == "virginica", ]) # floor(0.5*150) = 75
```

**Comment by RohitThakur01** [comment]
I have been getting this error when I run the code 
 rf <- ranger(Species ~ ., iris, replace = TRUE, keep.inbag = TRUE, sample.fraction = c(0.01, 0.1, 0.5))
Error in rangerCpp(treetype, dependent.variable.name, data.final, variable.names,  : 
  Expecting a single value: [extent=3].

**Comment by mnwright** [comment]
Did you install the newest version from GitHub? 
`devtools::install_github("imbs-hl/ranger")`

The feature is not on CRAN yet.

**Comment by RohitThakur01** [comment]
Thanks, it worked now.
