### ISSUE TITLE
Out-of-bag predictions for non-terminal nodes

### ISSUE THREAD

**Issue by CorinnaSchmalohr** [imbs-hl/ranger#168]
Hi,
I am interested in using ranger for a project where I need to get the oob predictions for non-terminal nodes. As far as I understood, in rf$forest$split.values there are oob predictions for terminal nodes and the splitting values for non-terminal nodes. 

Is there a way to get the predictions for the samples that were oob during the growing of the trees?

**Comment by mnwright** [comment]
For terminal nodes in `rf$forest$split.values` the predictions based on the observations in the node are saved, i.e., the major class in that node for classification and the mean outcome for regression. The OOB data is not used in the trees. 
What do you mean by OOB prediction of a node?

**Comment by CorinnaSchmalohr** [comment]
Okay, I had thought that the `rf$forest$split.values` predictions were on the oob bag samples, but they actually are on the inbag-samples, sorry for the misunderstanding.

As far as I understood, you use the OOB samples to compute the OOB prediction error.
I was wondering if the actual OOB predictions for each tree can be accessed somehow. In addition, I am not only interested in the OOB predictions for the terminal nodes, but also in the predictions for the internal nodes. I am using rf for regression.

What I want is something like in the following example using the randomForest Package:
`rf=randomForest(Ozone ~ ., data=airquality, na.action=na.omit)
rf$forest$nodepred`

**Comment by PhilippPro** [comment]
The oob prediction of each tree can be accessed by calling predict on the same data, I use this for my [OOBCurve](https://github.com/PhilippPro/OOBCurve) package. 

Example of how to access them: 

```
library(ranger)
mod = ranger(Species ~., data = iris, num.trees = 100, keep.inbag = TRUE)
preds = predict(mod, data = iris, predict.all = TRUE)
inbag = do.call(cbind, mod$inbag.counts)
preds$predictions
```
In `inbag` you have the information if the observation was used for training in each tree and in `preds$predictions` you have the predictions of each tree.

Your `randomForest` example is not out-of-bag, I think and I think these are the predictions of the terminal nodes??

**Comment by CorinnaSchmalohr** [comment]
@PhilippPro
I am actually not sure whether the predictions in `rf$forest$nodepred` are inbag or oob, but there are predictions for both internal and terminal nodes (however, the `getTree` function in the randomForest package only returns predictions for terminal nodes). My example was supposed to show what kind of information I generally want. 
Unfortunately, your example above is not what I need. 

For my application I would need for each tree and _each node_ in that tree the response value of the samples that were oob for this particular tree.  I am aware that this is rather unusual. I had hoped that maybe this kind of information was somewhere in the ranger object where I hadn't found it, or that there was a way to get this information somehow. 
If this is not the case (and if you don't plan to add this feature at some point) then feel free to close the issue.
