### ISSUE TITLE
Memory Issues and Parallization

### ISSUE THREAD

**Issue by payton1** [imbs-hl/ranger#169]
Hello, I am running a dataset with ~ 1.1 million rows, and 90 predictor variables on a 16 core machine with 64 GB of memory.  The dataset is able to run successfully after ~ 30 hours of running time.  However, I am interested in decreasing the run-time and wanted to get your guidance.  Is there a way to run the ranger function in a distribution fashion? i.e. on a compute farm?  Other ways of decreasing this run time?

Thank you

**Comment by mnwright** [comment]
How many trees are you growing? What kind of features are in your dataset? Continuous or categorical? 
Please post the ranger() call you are using. 

There are currently no plans for distributed computing in ranger.

**Comment by payton1** [comment]
Hello, I am growing 500 trees.  The response variable is categorical.  About 25% of the predictor variables are continuous and the rest are categorical.  

tree.result <- ranger( Target~., data=as.data.frame(signalDF), mtry=predictors, write.forest=TRUE, num.threads=32)

**Comment by mnwright** [comment]
30 hours seems a lot. I've tested the following 
````
library(ranger)

n <- 1.1e6
p_cat <- 68
p_cont <- 22

x_cat <- replicate(p_cat, rbinom(n, 1, .5))
x_cont <- replicate(p_cont, rnorm(n))
y <- factor(rbinom(n, 1, .5))
dat <- data.frame(y = y, x_cat, x_cont)

system.time(ranger(dependent.variable.name = "y", data = dat, 
                                  num.trees = 500, num.threads = 16))
````

And it took about 100 minutes to complete.

**Comment by payton1** [comment]
One difference between your function call and mine is that I set mtry equal to the number of predictors.  I am guessing that is the reason for the difference in exec time.

**Comment by mnwright** [comment]
Closed. Please re-open in case of questions.
