### ISSUE TITLE
Support for maxnodes argument

### ISSUE THREAD

**Issue by ck37** [imbs-hl/ranger#175]
Hello,

It would be helpful to support the maxnodes argument as implemented in randomForest - is that a possibility? It can be a preferable way to limit tree complexity compared to minnodesize, because it allows initial splits to result in small nodes provided that the max node size hasn't been exceeded. Segal & Xiao 2011 discuss it:

> "The R package RF includes a tuning parameter maxnodes that can be used to override growing maximal trees. Judiciously setting this parameter is anticipated to be beneficial in large sample size settings, and/or in situations where maximal trees severely overfit. Such control seems less awkward, especially for large sample sizes, than trying to govern tree size by the (related) parameter nodesize which determines the minimum size for terminal nodes: prescribing maxnodes more readily allows for penalization of tree complexity whereas not precluding vari- ably sized nodes. Lin and Jeon provide a theoretic perspective that is also contrary to use of maximal trees."

Segal, M., & Xiao, Y. (2011). Multivariate random forests. Wiley Interdisciplinary Reviews: Data Mining and Knowledge Discovery, 1(1), 80-87.

Thanks,
Chris

**Comment by mnwright** [comment]
Yes, we should have another stopping criterion. `maxnodes` in `randomForest` is the number of terminal nodes and thus depending on the order the nodes are created. Wouldn't the maximal tree depth be a more natural parameter?

**Comment by ck37** [comment]
I think it would be good to support maxnodes for backwards compatibility with randomForest at the very least. Also I saw just now that scikit-learn's implementation supports maxnodes: http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

That said, I think maximal tree depth would also be handy as an additional option.

**Comment by hadjipantelis** [comment]
I too was looking for a `max_tree_depth`-like parameter.

I think it is a great idea to have both a `max.tree.depth` and a `min.node.size`.

**Comment by samitpmc** [comment]
Is there any option in Rangers to specify max tree depth. If not can you point to code where I can add check to prevent tree depth please?

**Comment by mnwright** [comment]
Not yet. The checks for `min.node.size` are here: 
https://github.com/imbs-hl/ranger/blob/e770dfe2f0a9fb324944351e36c550ce9e4174da/src/TreeClassification.cpp#L83
https://github.com/imbs-hl/ranger/blob/e770dfe2f0a9fb324944351e36c550ce9e4174da/src/TreeProbability.cpp#L87
https://github.com/imbs-hl/ranger/blob/e770dfe2f0a9fb324944351e36c550ce9e4174da/src/TreeRegression.cpp#L70

For survival forests, the `min.node.size` is checked after splitting, and there are several checks in https://github.com/imbs-hl/ranger/blob/master/src/TreeSurvival.cpp. 
However, the tree depth check can probably simply added here:
https://github.com/imbs-hl/ranger/blob/e770dfe2f0a9fb324944351e36c550ce9e4174da/src/TreeSurvival.cpp#L94

I will probably add this feature myself before the next CRAN release but this might take a few weeks.

**Comment by hadjipantelis** [comment]
Thank you for this! :)

**Comment by rohan-shah** [comment]
I would also love to have a maxnodes or maxdepth argument.

**Comment by mnwright** [comment]
Added a `max.depth` parameter.

**Comment by samitpmc** [comment]
Great thanks

**Comment by ghazals** [comment]
It is very nice to have the 

> max.depth

 argument, however, a lot of time since comparisons with the random forest package is needed. So it would be nice to have 

> maxnodes

as well.

**Comment by mnwright** [comment]
I don't think that parameter makes much sense in ranger. It might stop at an arbitrary point at a given depth and it's dependent on the order the nodes are created. I think in randomForest it's mostly used to limit memory usage and speedup computation (because one can reserve memory for nodes a priori).
