### ISSUE TITLE
Add check for prediction with forest grown in old ranger version

### ISSUE THREAD

**Issue by Jtrack01** [imbs-hl/ranger#176]
Hi,

Please could you assist with an error I am encountering when using version 0.6.0 of the package?

I am getting a segfault (memory not mapped) error when running a script which loads ranger. The same issue seems to occur in versions 0.4.0 to 0.6.0.  I have also tested using version 0.3.0 and everything is fine. It occurs on both Windows and Linux versions of R.

The O/S I am using is Redhat 7.3 with R 3.3.2 and Microsoft R 9.0.1 installed. I am using the command line R when executing the script.

I have attached the partial output from valgrind and the traceback details from R. I have caret, sqldf, and data.table packages loaded, as part of the set of required packages for the script.

[traceback.txt](https://github.com/imbs-hl/ranger/files/868305/traceback.txt)
[valgrind_part.txt](https://github.com/imbs-hl/ranger/files/868306/valgrind_part.txt)

Thanks

**Comment by mnwright** [comment]
Could you please provide a reproducible example? Thanks!

**Comment by Jtrack01** [comment]
Hi,

Could you please provide an email address I can send the example and files to?

**Comment by mnwright** [comment]
Your model seems to be from an old ranger version. You generally should predict with the same version you used for training. 
I've posted a hack to convert old forests to the new structure in #132. Maybe that helps? 

We should probably add a check for this to avoid crashing the session...

**Comment by mnwright** [comment]
Check added.
