### ISSUE TITLE
Obtaining matrix of votes for OOB samples

### ISSUE THREAD

**Issue by EricArcher** [imbs-hl/ranger#177]
Perhaps I'm overlooking it, but for classification models, is there a way to obtain a matrix of votes for the OOB samples across the forest in `ranger`? Ideally, the values would be expressed as percentage of trees voting for each class when the sample was OOB, like the `$votes` matrix in the `randomForest` output.

**Comment by mnwright** [comment]
You could use the `probability` option: 

````R
library(ranger)
rf <- ranger(Species ~., data = iris, probability = TRUE)
rf$predictions
````

Is that what you want?

**Comment by EricArcher** [comment]
<head slap> D'oh - can't see how I missed that. Thanks! </head slap>
