### ISSUE TITLE
splitrule = "gini" error

### ISSUE THREAD

**Issue by topepo** [imbs-hl/ranger#178]
```r
> library(ranger)
> ranger(Species ~ ., data = iris, splitrule = "gini")
Error in ranger(Species ~ ., data = iris, splitrule = "gini") : 
  Error: Unknown splitrule.
> sessionInfo()
R Under development (unstable) (2017-03-21 r72380)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ranger_0.7.0

loaded via a namespace (and not attached):
[1] compiler_3.4.0 tools_3.4.0    Rcpp_0.12.10 
```
I'm updating `caret` to use randomized trees for topepo/caret/issues/581. `splitule = "extratrees"` works fine.

**Comment by mnwright** [comment]
How could I miss that? The `"gini"` splitrule is working fine, I've just forgotten to add the option. For now you'll have to use `splitrule = NULL` to get Gini splitting.

**Comment by topepo** [comment]
No problem. When do you plan on the next release being out?

**Comment by mnwright** [comment]
Fixed. Does it have to be on CRAN to solve it in `caret`?

**Comment by topepo** [comment]
Yes, but I'm about send a version to CRAN so it can wait until the next caret release (>= 3mo) if that works for you.

**Comment by mnwright** [comment]
Fine with me. Next ranger release won't be in the next couple of weeks.

**Comment by topepo** [comment]
Just a note... I've incorporated extremely randomized trees with ranger into the next `caret` release (topepo/caret#581)
