### ISSUE TITLE
predict() with predict.all=TRUE throws error when data has only one record

### ISSUE THREAD

**Issue by awmercer** [imbs-hl/ranger#182]
The most recent update seems to have introduced a bug with the predict.all option in ```predict()```.  If the data frame for which you are creating predictions contains only a single record, you get the following error: 
```Error in do.call(rbind, result$predictions) :  second argument must be a list```

Here is a small example that reproduces the error:
```
df = data.frame(a = runif(10), b = runif(10), c = runif(10))
r = ranger(data=df, dependent.variable.name = "a", replace=FALSE)
# Works fine
predict(r, data = df, predict.all = TRUE)

# Fails
predict(r, data = df[1,], predict.all = TRUE)
```
Thanks!
-Andrew

**Comment by mnwright** [comment]
Thanks, fixed.
