### ISSUE TITLE
predict() returning probabilities > 1

### ISSUE THREAD

**Issue by efh0888** [imbs-hl/ranger#183]
I'm using caret to build a random forest model (with method = "ranger") and to make predictions. Strangely, I am getting some predictions that print as 0/1 but in fact are greater than 1. I used ranger() directly (using the training data and tuned mtry value from caret) and get the same results, so the issue must be in ranger.

I'm working with highly sensitive data, and frankly don't have any clue how I can create another random forest model with the same issue on different data. If you have any suggestions I'll gladly give it a shot. But the best I can do at this point is describe what I did (fairly straightforward and probably won't help at all) and attach the portion of the affected predictions as a zipped RDS object.

```
set.seed(456)
rfModel <- ranger(TARGET ~ ., data = train, probability = TRUE, mtry = 2)
probs <- data.frame(predict(rfModel, test)$predictions)
sum(probs[,2] > 1)  # 161
```

[probs_greater_than_1.zip](https://github.com/imbs-hl/ranger/files/917673/probs_greater_than_1.zip)

**Comment by mnwright** [comment]
Seems to be some kind of conversion issue from C++ to R. These values are always 1 + 6.661338e-16. Example: 
    
    library(ranger)
    rf <- ranger(Species ~ ., iris, probability = TRUE)
    pred <- predict(rf, iris)$predictions
    unique(pred[pred > 1] - 1) # 6.661338e-16

**Comment by efh0888** [comment]
Interesting.  So that's probably true for all probabilities?

**Comment by mnwright** [comment]
Fixed. We were dividing several times to average probability predictions by tree, causing numerical inaccuracies.

**Comment by efh0888** [comment]
Fantastic
