### ISSUE TITLE
Trouble Installing Ranger on Linux Redhat VM

### ISSUE THREAD

**Issue by cbenedum** [imbs-hl/ranger#189]
I keeping having an error when I attempt to install Ranger 0.6.0 onto my RedHat virtual machine. The error that I am getting is the first screenshot. I have updated my gcc, and currently have two versions on my machine (the second and most up to date version - 4.9.4 - is located at /usr/local/bin). The second screenshot includes this information and the version information. Lastly I updated the the PATH variable to include the gcc location before the location of the out of date gcc (screenshot 3). Any help would be greatly appreciated! 

Screenshot 1
![screenshot1](https://cloud.githubusercontent.com/assets/16128314/25390152/b1898a64-29a0-11e7-8394-3b66d1e51859.png)

Screenshot 2
![screenshot2](https://cloud.githubusercontent.com/assets/16128314/25390158/b50e8478-29a0-11e7-8978-86f7cdb2fa4c.png)

Screenshot 3
![screenshot3](https://cloud.githubusercontent.com/assets/16128314/25390169/bb71ad40-29a0-11e7-9d74-8e06653e1858.png)

**Comment by mnwright** [comment]
It seems the gcc is still not properly configured. Is `which g++` also pointing to `/usr/local/bin`? Could you try to check that from within R with `system("which g++")`?

**Comment by cbenedum** [comment]
When i run system('which g++') I get /usr/bin/g++. However when I run 'which g++' from outside of R within the terminal I get /usr/local/bin/g++

**Comment by mnwright** [comment]
Is this solved?

**Comment by cbenedum** [comment]
No it is not

**Comment by mnwright** [comment]
Your R installation is not recognising your updated gcc. You could try to create a `~/.R/Makevars` file with something like this: 
    CC=/usr/local/bin/gcc      
    CXX=/usr/local/bin/g++ 
    CXX1X=/usr/local/bin/g++

Please note that this is not a problem with ranger, but with your system's configuration.

**Comment by cbenedum** [comment]
Ok thank you!
