### ISSUE TITLE
Clarify licensing 

### ISSUE THREAD

**Issue by mz2** [imbs-hl/ranger#190]
Is the license for the C++ code also GPL3 (I understand the R package license is GPL3)? Any chance of LGPL licensing it, or the very least GPL2? I'd really like to use it in a program where I could share any source code changes to ranger itself, and the Objective-C / Swift wrapper that I would like to build to it, but not the full program source code where I'd like to use it. GPL2 even would allow me to share the source code to the specific command line tool or server process I would create for using ranger in.

**Comment by mnwright** [comment]
The license for the C++ code is also GPL3. Unfortunately we cannot change the license.
