### ISSUE TITLE
Couldn't load data for ranger (C++ version)

### ISSUE THREAD

**Issue by blairzhang126** [imbs-hl/ranger#192]
I have some trouble loading my data. It's a 1.2G file with 4000 individuals and 148,418 SNPs as columns separated by single white space. I installed C++ version because R version couldn't allocate memory when doing analysis.

However, when I load my data, I got an error: "Error: Could not open input file. Too few columns in a row. Are all values numeric? Ranger will EXIT now." Any ideas how to solve it? I appreciate your help.

**Comment by mnwright** [comment]
Sounds like you used the formula interface in R. That's usually the reason for this kind of error. 
First, try to use alternative interface with `dependent.variable.name` (still in R, see the example in the help). Second, for GWAS data you should definitely use the `GenABEL` interface. There is an example in the R help for this, too.

**Comment by blairzhang126** [comment]
The GenABEL is really really helpful. Thanks so much!
