### ISSUE TITLE
Cross compiler on Windows 10 x64 ?

### ISSUE THREAD

**Issue by ifenglin** [imbs-hl/ranger#194]
Hello,

I just found this library helpful for my research on the topic of genetic algorithm and random forest. I'd like to build in with Visual Studio 2015 on Windows 10 x64. I notice there is a folder for named cross compile, but I am not so sure how I should proceed.  Would you please give a few tips on this? I'd truly appreciate your help.

Ifeng

**Comment by mnwright** [comment]
To create Windows binaries I'm cross compiling on a Linux machine with the toolchain in the `cross_compile` directory. I don't know if ranger can be directly compiled on Windows with Visual Studio.

**Comment by razumovs** [comment]
Trying on Visual Studio 2015 and so far failing.  Was wondering whether anyone got there.

**Comment by ifenglin** [comment]
It does not work for me, so I downloaded WinGDB and used gcc compiler. It
works well with this combination in Visual Studio environment.

Am 12.10.2017 6:30 vorm. schrieb "razumovs" <notifications@github.com>:
