### ISSUE TITLE
ranger(): error when given a data.frame containing a variable with an "illegal" varname

### ISSUE THREAD

**Issue by SelimRaboudi** [imbs-hl/ranger#196]
Hi,

The problem:
```{r}
# normal behaviour
ranger(Species ~ ., data = iris) #works
```
But when changing the variable names to illegal ones (containing "+", "-", starting by a number, ...)

```{r}
names(iris) <- c("0_Sepal.Length", "Sepal.Widt+h", "Pe-tal.Length", "Petal.Width", "Species")
ranger(Species ~ ., data = iris)
```
`Error in '[.data.frame'(data, , independent_vars, drop = FALSE) : 
  undefined columns selected`

When converting iris to a tibble we get the names of the incriminated vars:
```{r}
iris <- tibble::as_tibble(iris)
ranger(Species ~ ., data = iris)
```
`Error: Unknown columns: '`0_Sepal.Length`', '`Sepal.Widt+h`', '`Pe-tal.Length`'`

One should of course avoid such variable names, but it happened to me with a dataset of 300 vars, for which I just wanted to run a quick-and-dirty rf without taking care of renaming each of the ~20 problematic vars. 

Is there an easy way to fix this ?

**Comment by mnwright** [comment]
Error message for illegal column names added. The problem can be avoided by using the alternative interface with `dependent.variable.name`.
