### ISSUE TITLE
Ranger crashes on specific floating-point input

### ISSUE THREAD

**Issue by mbq** [imbs-hl/ranger#204]
The following code
```r
z<-readBin(as.raw(c(
 247,192,0,24,2,53,252,63,
 248,192,0,24,2,53,252,63
)),numeric(),2,endian='little')
ranger::ranger(a~.,data=data.frame(a=factor(1:2),z=z))
```
causes ranger to crash. `z` are two close, but different doubles (there is a +1 difference in mantissa). 

This was originally reported by @Jurvb [here](https://github.com/mbq/Boruta/issues/2).

**Comment by mnwright** [comment]
Fixed. 

Was related to #161. We are using the mid-point between to covariate values as split point. If the mid-point is numerically the same as the larger value, empty nodes occur, crashing ranger. This is now caught and the smaller value is used for splitting.
