### ISSUE TITLE
case.weights and missing minority class predictions

### ISSUE THREAD

**Issue by bballew** [imbs-hl/ranger#210]
I'm using ranger to analyze GWAS data, initially testing with a highly LD-pruned set of 67k SNPs.  I'm trying to use case.weights to account for unbalanced classes (174 cases, 3038 controls), but I end up losing predictions entirely from the confusion matrix for the minority class.  E.g.:

```
w<-as.numeric(readLines("weights_file"))   # file with 3212 values, 5 for controls and 100 for cases
train_rf<-ranger(aff_status ~ ., 
            data = train.gwaa, 
            num.trees = 250, 
            mtry = 1000, 
            importance = "impurity", 
            case.weights = w)
```

Confusion matrix: 

```
    predicted
true    0    1
   0 3038    0
   1    2    0
```

As you can see, there are no predictions at all for 172 of my cases.  Any suggestions?  

Thanks!
Bari

**Comment by mnwright** [comment]
The cases have such a high weight that they are in-bag in all trees. The confusion matrix is based on out-of-bag predictions and the cases get `NA` here (check `train_rf$predictions`). 
By default the `table` function (used for the confusion matrix) ignores NA's, I've changed that to include NA's and now your example should look like this:

```
    predicted
true   0   1 <NA>
   0 890  70    0
   1   1   0   39
```

**Comment by bballew** [comment]
Ah I see!  Thank you - that makes perfect sense.
