### ISSUE TITLE
How to use `importance_pvalues`?More examples are needed

### ISSUE THREAD

**Issue by GegznaV** [imbs-hl/ranger#212]
The following code results in an error:
```r
library(ranger)
rg.iris <- ranger(Species ~ ., data = iris, importance = 'permutation')
importance_pvalues(rg.iris)

## Error in ecdf(vimp) : 'x' must have 1 or more non-missing values
## In addition: Warning messages:
## 1: In if (method == "janitza") { :
##   the condition has length > 1 and only the first element will be used
## 2: In importance_pvalues(rg.iris) :
##   Permutation variable importance found, inaccurate p-values. 
##   Please use hold-out permutation importance to use this method.
```
1. Why the code does not work?
2. Could you include several examples in the package, which show how to use functions `importance_pvalues` and `holdoutRF` correctly?

**Comment by mnwright** [comment]
The Janitza method is only working for high dimensional data with negative importance values. For the iris dataset you'll have to use the permutation (altmann) approach: 
```r
library(ranger)
rg.iris <- ranger(Species ~ ., data = iris, importance = 'permutation')
importance_pvalues(rg.iris, method = "altmann", formula = Species ~ ., data = iris)
```

Example for the Janitza approach:
```r
library(ranger)
n <- 50
p <- 400
dat <- data.frame(y = factor(rbinom(n, 1, .5)), replicate(p, runif(n)))
hrf <- holdoutRF(y ~ ., dat)
importance_pvalues(hrf, method = "janitza")
```

TODOs:
* Check for negative importance values earlier to avoid the error shown above
* Provide examples
* Improve documentation, describe methods
* Default to permutation approach?
* Permutation approach without additional `formula` and `data` arguments?

**Comment by mnwright** [comment]
Done.

**Comment by chaugong** [comment]
I have problem in using importance_pvalues(). 

i ran ranger() and then i saved the ranger object named ranger.optimal in a RData file.

Later, i opened the RData file and tried the function but raised error
`importance_pvalues(x=ranger.optimal,method = "altmann",data = data.in,formula = Bias ~.) `    
Error:                     
`Error in importance_pvalues(x = ranger.optimal, method = "altmann", data = data.in,  :
No variable importance found. Please use 'importance' option when growing the forest.`


But i already specified 'importance' option as 'permutation' when i create ranger.optimal. 

So, what is the possible problem?

**Comment by mnwright** [comment]
Can you see importance values in `x$variable.importance`? What is `x$importance.mode`? where `x` is your ranger object.
