### ISSUE TITLE
how to get test votes from ranger?

### ISSUE THREAD

**Issue by joelive** [imbs-hl/ranger#213]
I hope to replace classic randomForest  in VarSelRF package with ranger.
code:
  boot.run.test <- randomForest(y  = train.class,
                                      x = train.data[, boot.col.data,
                                      drop = FALSE],
                                       ntree = boot.run$ntree,
                                      mtry = run.test.mtry,
                                      keep.forest = FALSE,
                                      xtest = test.data[, boot.col.data,
                                      drop = FALSE])$test
        output.cl$class.pred.array <- boot.run.test$predicted
        output.cl$prob.pred.array <- boot.run.test$votes

But I don't know how to get the boot.run.test$votes from ranger predict function. More examples are needed. Thank you.

**Comment by mnwright** [comment]
To get probability predictions in ranger you'll have to set `probability = TRUE` in the `ranger()` call. If you also need the hard classification, you can find the class with maximal probability in each row. Example: 

```R
library(ranger)
rf <- ranger(Species ~ ., iris, probability = TRUE)
votes <- predict(rf, iris)$predictions
preds <- levels(iris$Species)[max.col(votes)]
```
