### ISSUE TITLE
case.weights applied in bootstrapping vs impurity function

### ISSUE THREAD

**Issue by cjvanlissa** [imbs-hl/ranger#214]
Dear Dr. Wright,

in ranger, case.weights are applied during the bootstrapping process. As far as I understand, however, weights in single trees (e.g., rpart) are applied in evaluating the homogeneity of nodes resulting from a potential split. Are the consequences of these different implementations known, and would it be possible to implement both in ranger?

Sincerely,
Caspar

**Comment by mnwright** [comment]
You are right about the difference. I haven't seen any comparison of the different weighting schemes - please share if you know something. 
See also #131.
