### ISSUE TITLE
OOB error in "probability" mode

### ISSUE THREAD

**Issue by mayer79** [imbs-hl/ranger#216]
Hello rangers

One small question: How is OOB prediction error calculated in treetype 9 (probability mode)?

In a random example (around 50% accuracy), the values is around 30%:

```
> set.seed(3990)
> n <- 1000
> dat <- data.frame(y = factor(sample(0:1, n, replace = TRUE)),
>                   x = rnorm(n))
> 
> fit_1 <- ranger(y~x, data = dat)
> fit_1 # OOB prediction error:             50.80 % 
> 
> fit_2 <- ranger(y~x, data = dat, probability = TRUE)
> fit_2 # OOB prediction error:             0.3133206 
```

Thanks for clarification.

EDIT: I think it is MSE!?

**Comment by mnwright** [comment]
Yes, it's the MSE. We should add this to the docs.
