### ISSUE TITLE
Data Reformatting from .arff

### ISSUE THREAD

**Issue by michaelcalve** [imbs-hl/ranger#218]
I am currently using Random Forest in Weka/Java. 

I want to create a new model using ranger, from the same data I have used with Weka, however I have not seen any documentation on how to orient/arrange the training data.

Currently I have seven classes, and three attributes.

Is there a best practice for formatting a training file?

**Comment by mnwright** [comment]
In R you could try the `farff` package.

**Comment by michaelcalve** [comment]
Nevermind, there just isn't any part of the readme that gives us information as to what the header needs to be and what the format of the data needs to be, explicitly.  However, I was able to figure it out and your algorithms work great!

**Comment by michaelcalve** [comment]
Is there a way to leave comments in the training data??

**Comment by mnwright** [comment]
No that's currently not possible. However, it shouldn't be hard to implement. Small changes in [`Data::loadFromFileWhitespace`](https://github.com/imbs-hl/ranger/blob/25ee990e8f01f7c824448dc7497d6100d4abf7b7/src/Data.cpp#L103) and [`Data::loadFromFileOther`](https://github.com/imbs-hl/ranger/blob/25ee990e8f01f7c824448dc7497d6100d4abf7b7/src/Data.cpp#L138) should do the trick.
