### ISSUE TITLE
How to set the number of threads for importance_pvalues?

### ISSUE THREAD

**Issue by chrisraab** [imbs-hl/ranger#220]
Hi ranger team,

thanks for the great job with this package! I am currently using ranger to calculate permutation based importance values and I couldn't find any information of how to set the number of threads for the function` importance_pvalues()`. I tried ` num.threads`, but still all cores are used.

```
nt <- 2

rf_model_imp <- ranger::ranger(formula = fo, 
		                           data=train, 
		                           num.trees = ntree, 
		                           mtry = mtry,
		                           importance = "permutation",
		                           num.threads=nt)
	    
rf_imp <- ranger::importance_pvalues(rf_model_imp, method = c("altmann"),
		                    num.permutations = imp_perm, formula = fo, data=train,
		                    num.threads=nt)
```
Best
Christoph

**Comment by mnwright** [comment]
Thanks for reporting. This is a bug: `replicate()` doesn't work with `...` arguments. Will fix it soon.

**Comment by mnwright** [comment]
Fixed.
