### ISSUE TITLE
Rcpp::compileAttributes() generates extra "_" for names in RcppExports.cpp

### ISSUE THREAD

**Issue by hsinmin** [imbs-hl/ranger#226]
I am using Rcpp 0.12.13, and it will generate extra "_" for names in RcppExports.cpp. Project building failed because of this issue (Error message: ranger_init.o:ranger_init.c:(.rdata+0x28): undefined reference to `ranger_rangerCpp'). 

I did some research and the root cause seems to be Rcpp (cf: cf: http://dirk.eddelbuettel.com/code/rcpp.changelog.html):

 `2017-07-02  JJ Allaire  
        * src/attributes.cpp: Generate C++ native routines with underscore
        prefix to avoid export when standard exportPattern is used in NAMESPACE`

This problem can be fixed by adding underscores to names in ranger_init.c and RcppExports.R. 

I am wondering if there are hidden tricks that can make rcpp to generate names as the old days. Otherwise, maybe we should just go with the names with additional underscore.

**Comment by mnwright** [comment]
Thanks. It seems the code in `ranger_init.c` is auto-generated now. The new version should work with both Ripp versions.
