### ISSUE TITLE
Getting different results with ranger with different machines

### ISSUE THREAD

**Issue by kimiylilammi** [imbs-hl/ranger#227]
I have tried to run ranger with few different machines and I am getting different results on each machine. The results seem to remain the same with the same machine thought (running the code multiple times results in the same results).

Here's the testcase

```
library(ranger)
set.seed(0)
c <- ranger(Species ~ ., data = iris, seed=0, num.trees = 1, importance = "impurity", num.threads = 1)
print(c)
c$variable.importance
```
Ranger result
```

Call:
 ranger(Species ~ ., data = iris, seed = 0, num.trees = 1, importance = "impurity",      num.threads = 1) 

Type:                             Classification 
Number of trees:                  1 
Sample size:                      150 
Number of independent variables:  4 
Mtry:                             2 
Target node size:                 1 
Variable importance mode:         impurity 
OOB prediction error:             3.64 %
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
   0.7142857    0.0000000   89.2417794    7.3239348 
```

While the output is this on the other machine:
```
Ranger result

Call:
 ranger(Species ~ ., data = iris, seed = 0, num.trees = 1, importance = "impurity",      num.threads = 1) 

Type:                             Classification 
Number of trees:                  1 
Sample size:                      150 
Number of independent variables:  4 
Mtry:                             2 
Target node size:                 1 
Variable importance mode:         impurity 
OOB prediction error:             0.00 %
Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
   0.7142857    2.5000000   88.7417794    6.3239348 
```

You can see that importances are different and so is OOB prediction error.

Both machines have the same session info.
```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Finland.1252  LC_CTYPE=English_Finland.1252    LC_MONETARY=English_Finland.1252 LC_NUMERIC=C                     LC_TIME=English_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ranger_0.8.0         RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.1   Matrix_1.2-10    RevoUtils_10.0.6 tools_3.4.1      Rcpp_0.12.12     grid_3.4.1       lattice_0.20-35 
```

**Comment by mnwright** [comment]
Try `seed=NULL`. Setting it to `0` will run ranger without any seed. We should add this to the docs.

**Comment by kimiylilammi** [comment]
Thank you and thank you for developing and continuing supporting Ranger, its awesome! 

The seed=0 note probably should also read in the predict function as well. I believe it works the same way?

**Comment by mnwright** [comment]
Yes, thanks.

**Comment by Huizi949-z** [comment]
Hello, I tried `seed=NULL` but I still get two different resutls with the same seed. Could you please help with this?

**Comment by mnwright** [comment]
Unfortunately, that's expected behavior because the mt19937_64 seems to be different on Mac. See #533.

**Comment by Huizi949-z** [comment]
> Unfortunately, that's expected behavior because the mt19937_64 seems to be different on Mac. See #533.

Thank you! So currently there is generally no way to reproduce the same results between Mac and Windows?

**Comment by mnwright** [comment]
Maybe compiling with gcc on Mac would solve the problem? We should also try the approach mentioned in #533.
