### ISSUE TITLE
$ operator not defined for this S4 class

### ISSUE THREAD

**Issue by angelaparodymerino** [imbs-hl/ranger#232]
Hi,

When trying to get the table to compare observed phenotypes with the predicted ones, I get the following error (see at the end in bold):

```
> RF1<- ranger(dd ~ site, data = godwit.train, num.trees = 10000,
+        importance = "impurity", write.forest = TRUE)
> RF1
Ranger result

Call:
 ranger(dd ~ site, data = godwit.train, num.trees = 10000, importance = "impurity",      write.forest = TRUE) 

Type:                             **Classification** 
Number of trees:                  10000 
Sample size:                      177 
Number of independent variables:  3413 
Mtry:                             58 
Target node size:                 1 
Variable importance mode:         impurity 
OOB prediction error:             94.92 % 
> #Prediction
> pred.godwit <- predict(RF1, dat = godwit.test)
> table(godwit.test$dd, pred.godwit$predictions)
**Error in godwit.test$dd : $ operator not defined for this S4 class**
```
I have found that this is because godwit.test is a gwaa.data class, but this is indeed the format needed for high dimensional datasets when using ranger (am I right?). 

And by the way, for my analysis I wanted it to be of type regression (the phenotype I am working with is quantitative), and that is why a included importance="impurity", which seems to be for regression. Why is my RF of type Classification as it is shown above?

Thanks in advance,

Regards,

'Angela

**Comment by mnwright** [comment]
It seems `dd` is a factor or character, check `godwit.train@phdata`. Generally, in GenABEL the phenotypes are in the `phdata` slot, so use 
`table(godwit.test@phdata$dd, pred.godwit$predictions)` 
to produce the table (which makes no sense for regression). 

`importance = "impurity"` is for both regression and classification, as described in the documentation.
