### ISSUE TITLE
Why it does classification when I want regression?

### ISSUE THREAD

**Issue by angelaparodymerino** [imbs-hl/ranger#235]
Hi,

First of all, I am pretty new running Random Forests. 

I am working with ~3000 SNPs, 265 individuals and my aim for using RF (ranger) is to be able to identify the SNPs that explain more of the phenotype variation. The phenotype I am working with is continuous (quantitative) and I was wondering why when running ranger (with the parameters as shown below, using all samples, not a training set) it automatically decides to use variable importance mode = Classification, but what I want is to run is regression since the phenotype is continuous. Probably it is something to do with me not understanding well/exactly what does RF is doing with the data (???). How can a "tell" ranger to use variable importance mode = Regression?

```
Call:
 ranger(dd_sd2 ~ 0, data = godwitdata_allsites, num.trees = 500,      mtry = 340, importance = "impurity", write.forest = TRUE,      replace = TRUE) 

Type:                             Classification 
Number of trees:                  500 
Sample size:                      265 
Number of independent variables:  3412 
Mtry:                             340 
Target node size:                 1 
Variable importance mode:         impurity 
OOB prediction error:             92.45 % 
```

Thanks in advance,

'Angela Parody-Merino

**Comment by mayer79** [comment]
The forest type is derived from the data type of the response. So if `dd_sd2` is a factor, then `ranger` will do classification. If `dd_sd2` is numeric, then it will go for regression. This has nothing to do with "importance mode" though. I don't think your example code makes much sense. `~0` means you are not regressing on anything. On my machine, this causes a conflict with `mtry`>0.

**Comment by angelaparodymerino** [comment]
Thanks for your answer Michael, very helpful.

That makes sense. I had encoded dd_sd2 as factor, and it was wrong. Now I changed that to numeric:
`phdata(godwitdata_allsites)$dd_sd2 <- as.numeric(phdata(godwitdata_allsites)$dd_sd2)`
And it runs a regression. 

```
Call:
 ranger(dd_sd2 ~ site, data = godwitdata_allsites, num.trees = 5000,      mtry = 340, importance = "impurity", write.forest = TRUE,      replace = TRUE) 

Type:                             Regression 
Number of trees:                  5000 
Sample size:                      265 
Number of independent variables:  3413 
Mtry:                             340 
Target node size:                 5 
Variable importance mode:         impurity 
OOB prediction error (MSE):       25.82964 
R squared (OOB):                  0.06562611 
```

About what you said:  

> I don't think your example code makes much sense. ~0 means you are not regressing on anything. On my machine, this causes a conflict with mtry>0.

I put ~ 0 because I don't want to include any covariate (i.e. sex, site) from the phenotype file, so I read in the manual the following: 

> To use only the SNPs without sex or other covariates from the phenotype file, use 0 on the right hand side of the formula.

And that is the reason. Is it wrong? If yes, what should I put instead in the case I don't want to include any covariate in the equation?

Thanks again in advance,

'Angela Parody-Merino

**Comment by mayer79** [comment]
I did not know about this ~0 convention for GWAS data, so sorry!

**Comment by angelaparodymerino** [comment]
No worries. Thanks!

Cheers, 

'Angela Parody-Merino
