### ISSUE TITLE
Is the OOB-prediction error the lowest found of all trees that have been built in the run?

### ISSUE THREAD

**Issue by angelaparodymerino** [imbs-hl/ranger#236]
Hi,

I run this: 

```
Call:
 ranger(dd_sd2 ~ 0, data = godwit_allsites.train, num.trees = 5000,      mtry = 340, importance = "impurity", write.forest = TRUE,      replace = TRUE) 

Type:                             Classification 
Number of trees:                  5000 
Sample size:                      177 
Number of independent variables:  3412 
Mtry:                             340 
Target node size:                 1 
Variable importance mode:         impurity 
OOB prediction error:             89.27 % 
```

And I was wondering if I am right saying that the OOB-prediction error shown in the result of this run is the lowest found of the 5000 trees that were generated? In other words: with these parameters (ntree=5000, mtry=340, and default mode of the rest of parameters), the best tree (with the lowest prediction rate) has a prediction error of 89.27%, correct?

How could I get the OOB-prediction errors for each of the 5000 trees? Possible?

Thanks in advance,

'Angela

**Comment by angelaparodymerino** [comment]
I think I found the answer for the first question: 

OOB-prediction error = Overall out of bag prediction error. For classification this is the fraction of missclassified samples, for regression the mean squared error and for survival one minus Harrell's c-index.

But what about my second question: How could I get the OOB-prediction errors for each of the 5000 trees? Possible?

Thanks,

Cheers,

'Angela

**Comment by mnwright** [comment]
You are right about the OOB error, it's for the whole forest. 
There is no built-in way to get tree-wise OOB errors. However, it should be possible with `keep.inbag` while growing and predict with `predict.all` on the same data.
