### ISSUE TITLE
warning into TreeSurvival::computePredictionAccuracyInternal() method

### ISSUE THREAD

**Issue by Tigroux** [imbs-hl/ranger#239]
Hi

in the method TreeSurvival::computePredictionAccuracyInternal(), Visual Studio give a warning on the line:

`sum_chf.push_back(std::accumulate(chf[terminal_nodeID].begin(), chf[terminal_nodeID].end(), 0));`

because the last argument is a integer. So the result of this accumulation is trunk to an integer.
If the expected result must not be trunked, the line must be 

`sum_chf.push_back(std::accumulate(chf[terminal_nodeID].begin(), chf[terminal_nodeID].end(), 0.0));`

Best regards

Remi

**Comment by sofya1983** [comment]
Good afternoon,

I would like to work with Ranger on Windows (change code, debug and run). I see you are using Visual Studio. Does it mean that you have Windows version? If yes, is it possible for you to share it with me?

Kind regards,
Sofya

**Comment by Tigroux** [comment]
Sure,

It's an experimental version. I separate the data from the Forest class.
I used Visual Studio 2013.

You can find the code here:
https://github.com/RNCan/WeatherBasedSimulationFramework/tree/master/GeomaticTools/ranger

Cheers

**Comment by mnwright** [comment]
Thanks! Fixed.
