### ISSUE TITLE
Replicate randomForest error for empty classes in multiclass categorization

### ISSUE THREAD

**Issue by nielsenmarkus11** [imbs-hl/ranger#243]
I fit a model recently using `ranger` for a multiclass problem.  I then used new data to predict the classes of my test data, however after a certain class all of the predictions seemed to be off by one category when looking at the categories alphabetically.

Thinking it might be a bug in the `ranger` package, I tried using the `randomForest` package instead and when I fit the model, it produced the error:

    R: Error in randomForest.default(m, y, …) : Can't have empty classes in y

Finally, I figured out that I was trying to predict a class that didn't exist in my training data which caused the odd results.

Can you add a similar error when the factor level exists, but contains no actual values in a data set?

My workaround was to do the following:

    new.dat <- droplevels(dat)
    rf1 <- ranger(multiclass~x1+x2, data=new.dat)

Thanks.

**Comment by mnwright** [comment]
Thanks. I've added a warning for this.
