### ISSUE TITLE
Is it possible to run 'ranger' in parallel mode?

### ISSUE THREAD

**Issue by andirey** [imbs-hl/ranger#244]
I work with 'ranger' package and found it extremely efficient after 'randomForest' package.
The only one issue it will be good to understand: "How can I run ranger in a parallel mode in R?"
Will be happy to test code snippet for this case.
Thanks

**Comment by mnwright** [comment]
That's easy: `ranger(Species ~ ., iris, num.threads = 4)`.

**Comment by andirey** [comment]
Thanks a lot for so elegant solution!
Great package and very efficient for research.
