### ISSUE TITLE
showProgress modification

### ISSUE THREAD

**Issue by Tigroux** [imbs-hl/ranger#257]
Thanks for the implementation of issue #238  
But with this modification, the method showProgress is no longer valid because the method Forest::predictInternalInThread is not base on num_trees but on num_samples. 

so the max progress must be addd to the showProgress method:
`showProgress("Predicting..", num_trees);`
`showProgress("Aggregate prediction..", num_samples);`

and showProgress became:
`void Forest::showProgress(std::string operation, size_t **maxProgress**) {
	using std::chrono::steady_clock;
	using std::chrono::duration_cast;
	using std::chrono::seconds;

	steady_clock::time_point start_time = steady_clock::now();
	steady_clock::time_point last_time = steady_clock::now();
	std::unique_lock<std::mutex> lock(mutex);

	// Wait for message from threads and show output if enough time elapsed
	while (progress < **maxProgress**) {
		condition_variable.wait(lock);
		seconds elapsed_time = duration_cast<seconds>(steady_clock::now() - last_time);

		// Check for user interrupt
#ifdef R_BUILD
		if (!aborted && checkInterrupt()) {
			aborted = true;
		}
		if (aborted && aborted_threads >= num_threads) {
			return;
	}
#endif

		if (progress > 0 && elapsed_time.count() > STATUS_INTERVAL) {
			double relative_progress = (double)progress / (double)**maxProgress**;
			seconds time_from_start = duration_cast<seconds>(steady_clock::now() - start_time);
			uint remaining_time = (uint)((1 / relative_progress - 1) * time_from_start.count());
			if (verbose_out)
				*verbose_out << operation << " Progress: " << round(100 * relative_progress) << "%. Estimated remaining time: " << beautifyTime(remaining_time) << "." << std::endl;
			last_time = steady_clock::now();
		}
}
}`

This modification avoid to get "no end loop" in showProgress.
Thanks

**Comment by mnwright** [comment]
Ouch. I've found another bug which seems to avoid the infinite loop (but also the display of progress for prediction aggregation): `progress` is not reset after `predictTreesInThread`. 

It isn't possible to get stuck in the infinite loop in the current version, right?

**Comment by Tigroux** [comment]
I don't get infite loop anymore
Thanks

**Comment by mnwright** [comment]
But did you get them without PR #259? I'm asking because that version is on CRAN.

**Comment by Tigroux** [comment]
I don't make test with R. But with my own version of the ranger application, yes I got infinite loop if the number of predicted values is lesser than the number of trees. 
Cheers

**Comment by mnwright** [comment]
OK, thanks.
