### ISSUE TITLE
Is the order mode really experimental?

### ISSUE THREAD

**Issue by PhilippPro** [imbs-hl/ranger#261]
I always get this warning message in my package, because I use the ordered mode as default:
`Warning: The 'order' mode for unordered factor handling for multiclass classification is experimental.`

Is it really that experimental? Isn't it the default in other packages?

**Comment by mnwright** [comment]
Yes it's still experimental. To my knowledge `randomForest`, `randomForestSRC` and `party` are all partitioning, i.e., trying all 2-partitions, and none implemented the ordering approach. For multi class classification there is no perfect ordering method (as for 2-class or regression) and the current approach is not optimal. 
I'm working on a better one. I will present a poster on this topic at the [Biometrisches Kolloquium](http://www.biometrisches-kolloquium2018.de) in March.

**Comment by PhilippPro** [comment]
Did you already experience a dataset, where the method did not work well?

**Comment by mnwright** [comment]
Yes. I'll post an example as soon I have prepared the poster. 

Note that the method is working fine for 2-class classification and regression.
