### ISSUE TITLE
Selection frequency variables

### ISSUE THREAD

**Issue by LinusHi** [imbs-hl/ranger#264]
Is it possible to get the selection frequency for each variable used for splitting in the random forest?

**Comment by mnwright** [comment]
Quick and dirty (working only with the formula interface): 
````R
library(ranger)
rf <- ranger(Species ~ ., iris)
table(unlist(rf$forest$split.varIDs))
````
Ignore the 0's, these are terminal nodes. 

Better: 
````R
table(unlist(sapply(1:rf$num.trees, function(i) {
  treeInfo(rf, i)$splitvarName
})), useNA = "ifany")
````

**Comment by LinusHi** [comment]
Many thanks!
