### ISSUE TITLE
Ranger crashes when factor has just one level

### ISSUE THREAD

**Issue by kasuteru** [imbs-hl/ranger#267]
When using ranger, it crashes if a factor has just a single level. The error message is the following:

> Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
>   contrasts can be applied only to factors with 2 or more levels

This should not be a problem for a random forest algorithm - rather than throwing an error and stopping, a warning that the factor was ignored should be enough.

**Comment by mnwright** [comment]
You are right, this is a general R problem. However, since version 0.7.0 ranger uses it's own formula parser and it should work.
