### ISSUE TITLE
Quantile regression fails when any column has only single value.

### ISSUE THREAD

**Issue by jrhaberstroh** [imbs-hl/ranger#272]
Quantile regression fails when any column has a single value only. This is bad behavior, and should return NA with a warning (at worst).

> test_example <- data.frame(rep = 1, seq_pred = seq(1,10), seq_result = seq(1,10))
> test_validate <- data.frame(rep = 1, seq_pred = 5.5, seq_result = 5.5)
> test_model <- ranger::ranger(seq_result ~ ., test_example)
> predict(test_model, test_validate)$predictions
[1] 5.253736
> test_model <- ranger::ranger(seq_result ~ ., test_example, quantreg = TRUE)
> predict(test_model, test_validate)$predictions
[1] 5.267392
> predict(test_model, test_validate, type = "quantiles")$predictions
Error in node.values[, tree] <- object$random.node.values[terminal.nodes[,  :    replacement has length zero

**Comment by mnwright** [comment]
Thanks, fixed. The problem was that some trees didn't split at all.
