### ISSUE TITLE
Case-specific variable importance?

### ISSUE THREAD

**Issue by dswatson** [imbs-hl/ranger#273]
In their paper introducing case-specific random forests, [Xu et al. (2016)](http://www.tandfonline.com/doi/abs/10.1080/10618600.2014.983641) outline a method for calculating case-specific variable importance (see §4, pp. 57-61). I've written an R version that implements their proposal for regression forests using permutation importance (see below), but it isn't especially fast. I wonder if there would be any interest in expanding the `csrf` function to compute CSVI values for arbitrary tree types and importance metrics? I imagine this could be done quite efficiently in C++, but unfortunately I have no experience in the language!

``` r
csvi <- function(formula, training_data, test_data, 
                 params1 = list(), params2 = list()) {
  
  ## Top 20 or so lines courtesy of ranger::csrf
  ## Grow a random forest on the training data to obtain weights
  rf.proximity <- do.call(ranger, c(list(formula = formula, data = training_data, 
                                         write.forest = TRUE), params1))
  
  ## Get terminal nodes
  terminal.nodeIDs.train <- predict(rf.proximity, training_data, type = "terminalNodes")$predictions
  terminal.nodeIDs.test <- predict(rf.proximity, test_data, type = "terminalNodes")$predictions
  
  ## Calculate weights for all test cases
  wt_mat <- sapply(seq_len(nrow(test_data)), function(i) {
    num.same.node <- rowSums(terminal.nodeIDs.test[i, ] == terminal.nodeIDs.train)
    weights <- num.same.node / sum(num.same.node)
    return(weights)
  })
    
  ## Calculate MDA 
  ## We assume that the first p columns of training_data are predictors
  ## and the final column is the response
  ## This section also requires that params1() include the argument 
  ## keep.inbag = TRUE to identify oob observations
  n <- nrow(training_data)
  p <- ncol(training_data) - 1
  if (rf.proximity$treetype == 'Regression') {
    oob_err <- (rf.proximity$predictions - training_data[, p + 1])^2
    oob_idx <- ifelse(simplify2array(rf.proximity$inbag.counts) == 0, TRUE, NA)
    perm_dat <- training_data
    delta_mat <- sapply(seq_len(p), function(j) {
      perm_dat[, j] <- training_data[sample.int(n), j]
      tree_preds <- predict(rf.proximity, data = perm_dat, predict.all = TRUE)$predictions
      oob_preds <- rowMeans(oob_idx * tree_preds, na.rm = TRUE)
      perm_err <- (oob_preds - training_data[, p + 1])^2
      delta <- perm_err - oob_err
      # delta <- pmax(delta, 0)
      # Xu et al. recommend zeroing out negative deltas, but I think these
      # can actually be useful. See, e.g., Janitza et al.'s p-value method
      return(delta)
    })
    
    ## Weight results by case-wise proximity
    csv <- t(sapply(seq_len(nrow(test_data)), function(i) {
      matrixStats::colWeightedMeans(delta_mat, w = wt_mat[, i])
    }))
    
    ## Not sure this normalization step is necessary, but Xu et al. recommend it?
    csvi <- t(sapply(seq_len(nrow(test_data)), function(i) csv[i, ] / rowSums(csv)))
    dimnames(csvi) <- list(rownames(test_data), colnames(test_data)[seq_len(p)])
    return(csvi)
  } else {
    print('Whoops! Only supporting regression forests for now...')
  }
}
```

**Comment by mnwright** [comment]
Thanks. I'm currently on parental leave and will look into it when I'm back in the office in March.

**Comment by snembrini** [comment]
case-wise (permutation) importance was already available in the randomForest package, so I didn't quite understand when the authors claimed that they "would again like to define a similar [to that in the randomForest package], though case-specific" .

The way they compute the case-wise imprortance may be different, but I wonder how different from the standard case-wise importance from randomForest

**Comment by dswatson** [comment]
Fair point. I'd be curious to see a comparison of how the two measures perform under different conditions. In any event, it appears that neither is implemented in `ranger`? Might be a nice functionality to add.

**Comment by andland** [comment]
I believe that `localImp` in `randomForest` calculates "the average increase in squared OOB residuals when the variable is permuted." This is more of a sensitivity measure on how important the case and variable are to the overall prediction. 

The proposed case-specific variable importance is further intended for test examples.

**Comment by rcannood** [comment]
I'm working on this in [rcannood/ranger](github.com/rcannood/ranger). Rstudio automatically seems to have changed all of the whitespace in each of the files, so the [diff](https://github.com/imbs-hl/ranger/compare/master...rcannood:master) is horrible to look at. At some point, before creating a PR, I will redo all of the changes in a new fork to avoid the spacing issues.

Do case specific importances in classification and survival prediction also make sense?

**Comment by rcannood** [comment]
First off, kudos on ranger :) Having looked at the source code of randomForest and randomForestSRC, working with/on ranger is absolute bliss in comparison. 

I just finished a cleaner version of the case-specific variable importances ([diff](https://github.com/imbs-hl/ranger/compare/master...rcannood:master)). 

@mnwright: Would you be interested in adding this functionality to ranger, at some point? For now, I added implementations for regression, classification and probability trees. For survival trees, I'd have to think about how to implement it. 

In the current implementation, I [added a new ImportanceMode](https://github.com/imbs-hl/ranger/compare/master...rcannood:master#diff-fbbc564748ecd06c32f525a90464db8cR60): `IMP_PERM_CASEWISE`, though now I'm thinking it would have been better to pass it as a boolean variable to [Forest::initCpp](https://github.com/imbs-hl/ranger/blob/master/src/Forest.cpp#L66). his way, it would be possible to implement a casewise `IMP_PERM_BREIMAN` or even a casewise `IMP_GINI`. Do you prefer using the importancemode or a simple boolean in order to choose whether case-specific feature importances need to be calculated?

**Comment by rcannood** [comment]
Looking at the code above, I didn't include any weighting or normalisation (the `csv <-` and `csvi <-` steps).

**Comment by mnwright** [comment]
Added in #444.
