### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by dancooke** [imbs-hl/ranger#275]
Hi,

Thank you for the nice project! I was wondering if you would consider changing the license of some parts of the project to a more permissive one (e.g. MIT or BSD)? I'd like to use ranger in my project, but at the moment I can't as my project is MIT licensed, so to include your code my whole project would also need to become GPL, which I cannot do as other MIT/BSD licensed projects are also using my project, and then they would also need to change, ad infinitum...

I understand you're using some third party libraries which are GPL, so ranger as a whole must stay GPL, but as far as I can tell, all of the core C++ code, which would be highly useful as a stand-alone library, could be changed to MIT or similar (unless you have other reasons for choosing GPL of course). I'd be more than happy to make these changes if you agree. I'd of course also cite ranger in my tools upcoming paper, if I'm able to use it :)

Cheers!
Dan

**Comment by mnwright** [comment]
I see your point and I might give this another thought. Having separate licenses for the C++ and R parts is not a bad idea. I'll need a few weeks to think this through...

**Comment by dancooke** [comment]
Have you come to a decision on this?

**Comment by mnwright** [comment]
Yes, I'd like to change the license for the C++ core. It wasn't an easy decision, having two licenses in one project can be confusing and I don't want to split the two versions... 

I'll have to go through the code carefully to check if there were other contributors or I included some libraries, so the change might take some time.

**Comment by mnwright** [comment]
I think I asked all contributors and found no included GPL code in the affected code, PR #290. 
Any objections?

**Comment by dancooke** [comment]
Fantastic news!

**Comment by mnwright** [comment]
Merged the PR. The C++ core is now MIT licensed.
