### ISSUE TITLE
ranger crashes rsession

### ISSUE THREAD

**Issue by miller-moore** [imbs-hl/ranger#276]
I'm running ranger in quantile regression mode and the train/predict calls are wrapped inside a loop for simulation purposes.  I'm default num.threads (all available).  In my case, the only difference between loop iterations is the exact data passed to ranger (i.e., called "sampledData") changes based on a random sample of rows from a larger data set.  The number of rows is identical in each iteration.  Dimensions of sampledData are 50k by 333.  After 5-10 iterations, ranger causes rsession to crash.  Margin to max system memory was still plenty high during training (based on watching htop).  I also tried dropping num.threads to 1/2 of available threads, but that didn't seem to solve the problem.  

Could the quantile method possibly have a few kinks still needing ironed out?  Maybe a memory leak somewhere that could depend on specific column values exposed to ranger?  I saw in issue #272 posted recently that predict fails for quantile regression when a column was constant, but I've observed failures when that was not the case.  Further, the failures occurred in ranger(...) as opposed to predict(...), in my case.  

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4-3

loaded via a namespace (and not attached):
[1] compiler_3.4.3  

for( i in 1:10 ) {
    mRF <- ranger(dependent.variable.name = "v3", 
                             data = sampleData,
                             importance = 'impurity', num.trees = 1000, 
                             splitrule = 'extratrees', quantreg = TRUE,
                             write.forest = TRUE,  verbose = TRUE)
    p <-  predict(mRF, data = valData, type = 'quantiles', quantiles = c(0.01, 0.05, 0.5, 0.95, 0.99))$predictions
#some other stuff for evaluation
}

**Comment by mnwright** [comment]
This might be the combination of extra trees splitting and quantile regression, which is not tested that well. I will look into it but I might take some time (I'm on parental leave).

**Comment by miller-moore** [comment]
Congrats! I'm 2 weeks away from being in that same position, so totally understand.

I will add that the same problem occurred when using the normal variance splitrule.  Extratrees is relatively more stable for whatever reason.

**Comment by miller-moore** [comment]
Looks like the odd behavior was on our end - lack of server ventilation caused overheating.  I apologize for any time I may have cost you.  

Thanks for the awesome package - I've been a long time user.  Best of luck to you and the family.
