### ISSUE TITLE
Running Ranger C++ application for prediction

### ISSUE THREAD

**Issue by senthilki** [imbs-hl/ranger#278]
I can able to compile the ranger C++ application on Ubuntu machine.

But there is no clarity on input file format. 

From the README file i got below information.
=====================

for a list of commands. First you need a training dataset in a file. This file should contain one header line with variable names and one line with variable values per sample. Variable names must not contain any whitespace, comma or semicolon. Values can be seperated by whitespace, comma or semicolon but can not be mixed in one file. A typical call of ranger would be for example

```bash
ranger --verbose --file data.dat --depvarname Species --treetype 1 --ntree 1000 --nthreads 4
=========================
I took the Iris Data set in csv format as shown in the below link.

https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv

While executing am getting below error

./ranger --verbose --file iris.csv --depvarname Species --treetype 1 --ntree 1000 --nthreads 4
Starting Ranger.
Loading input file: iris.csv.
Error: Variable Species not found. Ranger will EXIT now.

I have below queries.

1. Please give an example input file format ? 

2. I would like to cross compile this Ranger application to execute on Android device , so that i can train and predict on the Android device. 

If you would have already done the CROSS_COMPILATION for any other platform please help in that too. 

3. Please give an elaborate README file for executing C++ application for training and predicting for particular variable with certain input data.

**Comment by mnwright** [comment]
Currently, only numeric values are possible in the standalone C++ version, see also #271. We should also improve the readme for the standalone C++ version. 

For cross compiling, there are some scripts in [cpp_version/cross_compile/](https://github.com/imbs-hl/ranger/tree/master/cpp_version/cross_compile).
