### ISSUE TITLE
Classification accuracy in the ranger model summary

### ISSUE THREAD

**Issue by thengl** [imbs-hl/ranger#282]
Currently if we use ranger and fit classification models we get:

```
> ranger(Species ~ ., data = iris, probability=TRUE)
Ranger result

Call:
 ranger(Species ~ ., data = iris, probability = TRUE) 

Type:                             Probability estimation 
Number of trees:                  500 
Sample size:                      150 
Number of independent variables:  4 
Mtry:                             2 
Target node size:                 10 
Variable importance mode:         none 
OOB prediction error:             0.03238261 

> ranger(Species ~ ., data = iris)
Ranger result

Call:
 ranger(Species ~ ., data = iris) 

Type:                             Classification 
Number of trees:                  500 
Sample size:                      150 
Number of independent variables:  4 
Mtry:                             2 
Target node size:                 1 
Variable importance mode:         none 
OOB prediction error:             4.00 %
```
in the first case (`probability=TRUE`) the model summary shows OOB prediction error = 0.032 (this is the average error in probability space). This number is rather abstract, in the second case the OOB prediction error number is easier to interpret (basically 96% accuracy). Most of users are probably more interested in the relative [prediction accuracy](https://rpubs.com/m3cinc/Benchmarking_20_Machine_Learning_Models_Accuracy_and_Speed) and/or [kappa](https://machinelearningmastery.com/machine-learning-evaluation-metrics-in-r/). Could you please add at the bottom of the model summary list also an OOB estimate of the OOB prediction accuracy (0-100%) so that regardless of the probability, hard classification or regression problem we get a single number of estimated prediction success? Thank you.

**Comment by mnwright** [comment]
For `probability=TRUE` the prediction error is the Brier score. For 2-class problems this is equivalent to the MSE (have to check the exact definition for multiclass). 
How would you define an estimate of the error on the 0-100% scale for probabilities?

**Comment by thengl** [comment]
From probabilities you can still derive most probable class and then also prediction accuracy and/or [kappa](https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/cv/cv_functions.R#L46). The other thing that comes to my mind is reporting [True Positives](https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/cv/cv_functions.R#L48) (per class). Reporting also is `OOB prediction error: 0.03238261` is fine, but it is just too abstract to get anything out of it (summary should quickly give user clear idea of the classification/prediction success).

**Comment by mnwright** [comment]
The problem is that all these methods involve thresholding for a hard classification. I don't think we should do that as a default but stick to measures involving the probabilities such as the Brier score or AUC. 

We should add information what kind of "prediction error" is computed to the output.
