### ISSUE TITLE
Duplicates and repetitions and their influence on the summary estimate of the prediction accuracy

### ISSUE THREAD

**Issue by thengl** [imbs-hl/ranger#283]
We have discovered through few case studies with spatial and spatiotemporal data that the ranger's measure of the OOB errors / prediction accuracy is often over-optimistic if measurements happen at same locations (see e.g. [Gasch et al. 2015](https://doi.org/10.1016/j.spasta.2015.04.001) and/or [Meyer et al. 2018](https://doi.org/10.1016/j.envsoft.2017.12.001)). This is in fact a serious issues as the difference between the reported and actual accuracy can be significantly high. Somehow the ranger model matches same locations in feature space, so that it has no problems predicting values in the repeated measurements. This problem could be solved if ranger would allow using an ID column that defines repetitions (if the ID is exactly the same, then it is a repeated observation / the same location), so that same IDs should not be used for internal validation (bagging). I do not know how to implement that exactly, but maybe my [code for leave-locations-out (LLO) cross-validation](https://github.com/ISRICWorldSoil/SoilGrids250m/blob/master/grids/cv/cv_functions.R#L164) could help you? Thanks

**Comment by fab4ap** [comment]
Is this an issue in randomForest() implementation too or is it unique to ranger? thanks.

**Comment by thengl** [comment]
It is a general problem basically with any data with duplicate locations in space or time.

**Comment by mnwright** [comment]
This can be solved with mlr. Either ID-based with [Blocking](https://mlr-org.github.io/mlr/articles/tutorial/devel/resample.html#stratification-and-blocking) or even specific to spatial data with spatial autocorrelation: [Tutorial with examples](https://mlr-org.github.io/mlr/articles/tutorial/devel/handling_of_spatial_data.html).

**Comment by thengl** [comment]
Thanks for sending this Marvin. Let me check that code to see if it is applicable to my problems (I hope it is a parallelized implementation). Will come back.

**Comment by thengl** [comment]
Tested using SpRepCV and [works fine](https://github.com/Envirometrix/PNVmaps/blob/master/R_code/PNV_mapping.R#L358) (note that the mean CV accuracy drops significantly from the number I get in ranger!). SpRepCV can also be parallelized via the parallelMap package.
