### ISSUE TITLE
Out of Bag Probabilities, Average Probabilities in Classification

### ISSUE THREAD

**Issue by cargomoose** [imbs-hl/ranger#288]
With classification:
Could we please have an option to return out-of-bag probabilities of all classes. Only the the out-of-bag predicted classes are returned currently.  One further request is that with those probabilities, we get the option of choosing either the average of the per-tree 0 or 1 class outcomes, or the average of their probabilities.

**Comment by mnwright** [comment]
Try `probability = TRUE` when calling ranger. 
For the average of 0-1 outcomes try `predict.all = TRUE` in `predict()`.

**Comment by cargomoose** [comment]
Thanks Marvin,

This is very helpful.
Is there a way of getting probabilities rather that 0/1 in the individual tree predictions ?

**Comment by mnwright** [comment]
If you use both `probability = TRUE` and `predict.all = TRUE`, you'll get an array of per-tree probabilities.

**Comment by dswatson** [comment]
Correct me if I'm wrong, @mnwright, but I believe the output of `predict.all` doesn't distinguish between in-bag and out-of-bag samples? To average across trees in a classification forest for just OOB cases, @cargomoose, you might want to try something like:

```r
# Simulate some data
x <- matrix(rnorm(1000), ncol = 10)
y <- rbinom(100, 1, prob = 0.5)
dat <- data.frame(x, y)

# Build model (be sure to set keep.inbag = TRUE)
rf <- ranger(y ~ ., data = dat, classification = TRUE, keep.inbag = TRUE)

# Identify OOB cases
oob_idx <- ifelse(simplify2array(rf$inbag.counts) == 0, TRUE, NA)

# Average over trees for just OOB cases
preds <- predict(rf, dat, predict.all = TRUE)$predictions
probs <- rowMeans(oob_idx * preds, na.rm = TRUE)
```

**Comment by mnwright** [comment]
Correct. The `$predictions` in the ranger object are OOB but if you use `predict()` you'll have to restrict on the OOB samples (as you have done here).

**Comment by MahdiSafarpour** [comment]
@mnwright
 I am using "0.1.6.33" version to detect interaction in our dataset. The point is that I cannot use "keep.inbag = TRUE" since it has not been defined for this version of R. Is there any solution for this problem?

**Comment by MahdiSafarpour** [comment]
May you please let me know whether in the following scenario, the probabilities are based on OOB or not:

rf=ranger(Species ~ . , data = iris, importance='pairwise', num.trees=100, probability=TRUE, write.forest=TRUE)
probabilities=predict(rf, data=iris)$predictions

My next question is about the difference between rf$predictions and predict(rf, data=iris)$predictions. I got two different results but I do not have any idea why it happens.

Any help is highly appreciated.

**Comment by mnwright** [comment]
I think the only solution would be to re-implement the pairwise importance measure in the current version. 

I answered the second question in #380. Please don't ask the same question twice.

**Comment by MahdiSafarpour** [comment]
Thanks a lot for your reply.
When you say in the current version, do you mean version ‘0.1.6.33’ or you mean the latest version of Ranger?

**Comment by mnwright** [comment]
With current I mean the latest version here on Github (CRAN is also quite outdated now and should be updated).

**Comment by cargomoose** [comment]
Hi Marvin,

Will you be making the new version available soon ?
Also, has MAE splitting for regression been impmentented in the new version ? I ask because I am about to get one of my team onto it if it hasn’t been done already.

best regards,

Eugene.

**Comment by mnwright** [comment]
The new version (0.13.1) is on CRAN now! A PR for MAE splitting would be very welcome.
