### ISSUE TITLE
type=se and se.method = "infjack" produces error

### ISSUE THREAD

**Issue by fab4ap** [imbs-hl/ranger#291]
ranger version: 0.9.0
R version: 3.4.4 
Windows 10 OS (128 GB RAM)

> xmod
Ranger result

Call:
 ranger(riv129 ~ ., data = xdata, num.trees = 1000, mtry = 20/3,      min.node.size = 5, splitrule = "variance", importance = "permutation",      write.forest = TRUE, num.random.splits = 5, always.split.variables = NULL,      scale.permutation.importance = TRUE, quantreg = FALSE, keep.inbag = TRUE) 

Type:                             Regression 
Number of trees:                  1000 
Sample size:                      48572 
Number of independent variables:  20 
Mtry:                             6 
Target node size:                 5 
Variable importance mode:         permutation 
OOB prediction error (MSE):       4.295161 
R squared (OOB):                  0.4105155

> xmodp.seinfjack = predict(xmod, data=xdata, predict.all=FALSE, type="se", se.method = "infjack")
**Error in if (B^2 > n * nrow(pred)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In n * nrow(pred) : NAs produced by integer overflow**

**Comment by mnwright** [comment]
Seems like `n * nrow(pred)` is larger than the maximal integer. I'll try to fix that check.

**Comment by fab4ap** [comment]
Marvin: Thanks very much - much appreciated.
Prasad

**Comment by mnwright** [comment]
Fixed.

**Comment by skgrange** [comment]
Hello Marvin,
I have an additional error which involves using `se = TRUE` and `se.method = "infjack"` on a regression forest. When predicting, I am getting this error: 

```
Error in approx(x = calib.x, y = calib.y, xout = vars) : 
need at least two non-NA values to interpolate
```

This error seems dependent on the size of the input data frame. Here is an example: 

```
# Load package
library(ranger)

# Load example
df <- readRDS(url("https://skgrange.github.io/data.service/arbitrary/example_set.rds"))

# 53 000 observations
dim(df)

# Train the model/grow the forest, only five trees
model <- ranger(
  value ~ ., 
  data = df,
  write.forest = TRUE,
  importance = "permutation",
  verbose = TRUE,
  num.trees = 5,
  mtry = 5,
  min.node.size = 5,
  splitrule = "variance", 
  seed = NULL,
  keep.inbag = TRUE
)

# Predict with se
prediction <- predict(
  model, 
  df,
  type = "se", 
  se.method = "infjack",
  seed = NULL,
  verbose = TRUE
)

# Error in approx(x = calib.x, y = calib.y, xout = vars) : 
# need at least two non-NA values to interpolate

# Predict with se, smaller df, works ok
prediction <- predict(
  model, 
  df[1:10000, ],
  type = "se", 
  se.method = "infjack",
  seed = NULL,
  verbose = TRUE
)

# Looks good
prediction
```

Am I missing something? Let me know if you want me to open a new issue. Many thanks,
Stuart.

**Comment by mnwright** [comment]
The problem seems to be that we are reaching infinity here https://github.com/imbs-hl/ranger/blob/cb3f2e030cfb23dda164ff7d5750500829e6ad7f/R/infinitesimalJackknife.R#L151

But only if we have a large number of prediction observations.
That code is written by Stefan Wager, @swager can you help?
