### ISSUE TITLE
Units of importance measures

### ISSUE THREAD

**Issue by skgrange** [imbs-hl/ranger#308]
Hello ranger team,
Great work on your implementation of random forest, it is great. I have a question regarding what units the importance measures are reported in. Let's say I ran the code below (this would be used in regression mode) and wanted to create an importance plot from the results, what would be an appropriate unit to display on the plot axes? I understand the **randomForest** package "scales" the importance measures by (pseudo) standard errors by default so the results are not immediately comparable. Is the "impurity" mode the recommended measure when the functions are used for regression? I am sorry if these are simple questions, I cannot seem to find the answers in the documentation. 

```
# Grow forest
model <- ranger::ranger(
  value ~ ., 
  data = dplyr::filter(data_example, set == "training"),
  write.forest = TRUE,
  importance = "impurity"
)

# Check
print(model)

# Extract importances
ranger::importance(model)
```

**Comment by mnwright** [comment]
The impurity importance measures sums of impurity measures, the permutation importance differences of predictions errors. Both are not proper units and one should be careful when comparing importance values between datasets. The scaled importance is biased in some cases and should be avoided (see [Nicodemus et al. 2010](https://doi.org/10.1186/1471-2105-11-110)). 

Generally, I'd recommend the permutation importance or the corrected impurity importance (`importance = "impurity_corrected"`, new in ranger 0.9.x), which is computationally faster.

**Comment by skgrange** [comment]
Great. Thanks for the guidance and advice.
