### ISSUE TITLE
When do you plan to release a new version on CRAN?

### ISSUE THREAD

**Issue by golivax** [imbs-hl/ranger#310]
With fix #306, you bumped the dev version to 0.9.8. Do you have any plans to release a new version on CRAN any time soon? Just curious, really. Thanks!

**Comment by mnwright** [comment]
Will probably take a few weeks. Any features or fixes that are urgent to be on CRAN?

**Comment by golivax** [comment]
No worries. For me personally, only #306. But I guess I can always use devtools to get the latest dev version. Thanks

**Comment by mnwright** [comment]
On CRAN now (binaries pending).
