### ISSUE TITLE
Probability Predictions with Sparse Matrices

### ISSUE THREAD

**Issue by illusive-git** [imbs-hl/ranger#312]
Hello,

I have an issue using the predict function when training the ranger on sparse matrices:
```R
library(Matrix)
library(ranger)
# create a random sparse matrix
A = Matrix(data = rbinom(1000*10000,size = 1,prob = 0.2),nrow = 10000,ncol = 1000,sparse = TRUE,
    dimnames = list(NULL,lapply(1:1000,as.character)))

# add the label and call it AAA
A_2 = cbind(A,rbinom(10000,size = 20,prob = 0.5))
A_2@Dimnames[[2]][length(A_2@Dimnames[[2]])] = "AAA"


# ranger call
large_ranger = ranger(data = A_2,
                      dependent.variable.name = "AAA",
                      classification = TRUE,
                      num.trees = 10,
                      importance = "impurity",
                      min.node.size = 1,
                      probability = TRUE)

# predictions in call
large_ranger$predictions[1]

# predict function
test = predict(large_ranger,data = A)
test$predictions[1]

```
The in-object predictions are completely fine, but if I call the predict function I receive a single zero every time. It also gives number of samples as 2. Error both on rstudio server ubuntu and R on mint.

My current workaround is to set Probability = FALSE and take the relative class occurence in the predict.all = TRUE output.

Thank you,
Max

**Comment by mnwright** [comment]
Thanks. This was a bug (`is.matrix()` isn't true for the `Matrix` package). 
This also solved other problems: 
* Sparse probability prediction is now also working without `classification=TRUE`
* The predictions are a k-dimensional numeric instead of a list now

**Comment by illusive-git** [comment]
Thanks a lot for the quick fix! A happy weekend to your from Berlin.
