### ISSUE TITLE
impurity variable importance using maxstat splitrule

### ISSUE THREAD

**Issue by michaellevy** [imbs-hl/ranger#313]
Doesn't seem to work.  Permutation importance works fine. Is this a bug, or is it just not possible? Thanks.

``` r
library(ranger)
data(mtcars)
rcars <- ranger(mpg ~ ., mtcars, importance = "impurity", splitrule = "maxstat")
rcars$variable.importance
#>  cyl disp   hp drat   wt qsec   vs   am gear carb 
#>    0    0    0    0    0    0    0    0    0    0
```

Created on 2018-05-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mnwright** [comment]
The impurity measure for maxstat splitting was not implemented yet. We already had a branch with this. It now returns the test statistic as impurity measure. Be careful, this is not tested very well.

**Comment by michaellevy** [comment]
Thanks for the quick response, @mnwright. I think we'll just stop supporting maxstat.

**Comment by JieyingJiao** [comment]
Hi,

Wants to follow up on this question. I'm using maxsplit for a survival model, and use "impurity" as feature importance. Is this option working properly? and if yes, is the feature importance returned being the sum of test statistics, which is the maximally selected rank statistics M? Thanks.

**Comment by mnwright** [comment]
Yes, exactly. It works properly and you are correct about the sum of test statistics.
