### ISSUE TITLE
raster prediction using rf fited via ranger package

### ISSUE THREAD

**Issue by sarash85** [imbs-hl/ranger#319]
Hi,
I have fitted a randomforest model to my dataset using ranger package in R.  when I want to predict new raster using the raster package and the fitted rf model, I just  get this error:
Error in p[-naind, ] <- predv : 
  number of items to replace is not a multiple of replacement length

does ranger has any problem with the raster prediction?

**Comment by mnwright** [comment]
It seems (from your email) that you are using `raster::predict()` for prediction. For this to work, the raster package has to support ranger, which seems not to be the case. If you want to use `ranger::predict()`, you'll have to have a `data.frame` or `matrix` with your data.

**Comment by sarash85** [comment]
Yes I couldnt predict using raster, so I needed to convert my raster to spatialpoint and predict using ranger. So, definitely the raster package doesnt support Ranger for now, right?

**Comment by mnwright** [comment]
Seems like it's not supported yet. Searching for `randomForest` in the raster code, it seems not too hard to add ranger support: https://github.com/mdsumner/raster-rforge/blob/2088b719c9bd17031dd5d75596f13b00e7247141/pkg/raster/R/predict.R#L54
I'll give it a try.

**Comment by mnwright** [comment]
Actually just a very small change is required, see mdsumner/raster-rforge#34.

**Comment by mnwright** [comment]
Just found another workaround which should also work with the change: 

```R
library(raster)

# create a RasterStack or RasterBrick with with a set of predictor layers
logo <- brick(system.file("external/rlogo.grd", package="raster"))
names(logo)

# known presence and absence points
p <- matrix(c(48, 48, 48, 53, 50, 46, 54, 70, 84, 85, 74, 84, 95, 85, 
   66, 42, 26, 4, 19, 17, 7, 14, 26, 29, 39, 45, 51, 56, 46, 38, 31, 
   22, 34, 60, 70, 73, 63, 46, 43, 28), ncol=2)

a <- matrix(c(22, 33, 64, 85, 92, 94, 59, 27, 30, 64, 60, 33, 31, 9,
   99, 67, 15, 5, 4, 30, 8, 37, 42, 27, 19, 69, 60, 73, 3, 5, 21,
   37, 52, 70, 74, 9, 13, 4, 17, 47), ncol=2)

# extract values for points
xy <- rbind(cbind(1, p), cbind(0, a))
v <- data.frame(cbind(pa=xy[,1], extract(logo, xy[,2:3])))

library(ranger)
rfmod <- ranger(pa ~., data=v)
r3 <- predict(logo, rfmod, type='response', progress='window', fun = function(model, ...) predict(model, ...)$predictions)
```

The only change is adding `fun = function(model, ...) predict(model, ...)$predictions` to raster::predict().

**Comment by sarash85** [comment]
I get this error now even with fun argument:
 Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "ranger"

**Comment by mnwright** [comment]
Is my example above running through?

**Comment by sarash85** [comment]
yes your example works.

**Comment by mnwright** [comment]
Could you post a reproducible example of your error?

**Comment by philiporlando** [comment]
I'm getting some puzzling results when trying to adapt `predict::ranger()` to work with `raster` data.

```
# Predictor stack
s <- stack(...)

# Convert to dataframe
df <- as.data.frame(s, xy = T, na.rm = T)

# Call ranger.predict
preds <- predict(model, data = df[, names(model$variable.importance)])

# Convert the prediction vector into a raster using the original stack as a template
s$predictions <- preds$predictions

```

Are there any glaring issues with this approach? My OOB summary statistics look great, and when I compare my prediction vector against my test data, I'm observing a strong R2 and a low RMSE. However, my predicted rasters do not make intuitive sense, and when I extract my training/test dataset from these new predicted rasters, the scatter plot does not look anything like the test regression. Please tell me it's a simple programming error on my part!

![test_regression](https://user-images.githubusercontent.com/24445174/53208738-b82cab80-35ec-11e9-9742-bcd45e94f053.png)


![2018_09_26_map_xyplot](https://user-images.githubusercontent.com/24445174/53208751-c5499a80-35ec-11e9-831d-8a8f547b3c61.png)

**Comment by mnwright** [comment]
Hm... I think I don't fully understand. What is the difference between the two scatter plots? Have to tried to simplify and run without raster and caret?

**Comment by pestack** [comment]
This link to mdsumner no longer works. Can it be updated? https://github.com/mdsumner/raster-rforge/blob/2088b719c9bd17031dd5d75596f13b00e7247141/pkg/raster/R/predict.R#L54
