### ISSUE TITLE
Predict sparse, binary matrix of terminal node membership

### ISSUE THREAD

**Issue by Zelazny7** [imbs-hl/ranger#335]
When predicting terminal node IDs it would be helpful to return a sparse, pattern matrix of type `ngCMatrix`. This binary matrix could be used for other purposes such as LASSO or clustering.

Something similar to what scikit learn does with [RandomTreesEmbedding](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomTreesEmbedding.html).

**Comment by mnwright** [comment]
That should be possible with the `dummies` package and some `cbind` and `apply`. I don't think we need to have this in the package.

**Comment by Zelazny7** [comment]
I don't think that's sufficient. The dummies package does not have options for a sparse format. If each tree has, for example, 100 terminal nodes and I build 100 trees. that's 100 x 100 columns of dense data. Effectively multiplying the storage required by 100.

A dataset with even 200k rows pushes 16gb in that case. This all *could* be done in R with the terminal nodes matrix if there was a way of knowing how many possible terminal nodes each tree produces. Then it would be trivial to construct the sparse matrix. I'll see if that's possible.

**Comment by mnwright** [comment]
You could try `Matrix.utils::dMcast()`.
