### ISSUE TITLE
NA predict when factor level dropped in response

### ISSUE THREAD

**Issue by stephematician** [imbs-hl/ranger#336]
As per title, I am not familiar enough with the code to propose a solution, but this does seem related in ranger.R

      result$forest$levels <- levels(droplevels(response))

Anyway here's a small and hopefully reproducible working example (not going to claim it is a MWE)

    require(ranger)
    set.seed(1)
    data_ <- mtcars
    
    integer_vars <- c('cyl', 'vs', 'am', 'gear', 'carb')
    data_[integer_vars] <- lapply(data_[integer_vars],
                                  as.factor)

    rf_fit<- ranger(data=data_[data_['cyl'] != 4,],
                    dependent.variable.name='cyl')

    Warning message:
    Dropped unused factor level(s) in dependent variable: 4. 

    predict(rf_fit, data=data_)$predictions
     [1] 8    8    8    8    <NA> 8    <NA> 8    8    8    8    <NA> <NA> <NA> <NA>
    [16] <NA> <NA> 8    8    8    8    <NA> <NA> <NA> <NA> 8    8    8    <NA> 8   
    [31] <NA> 8   
    Levels: 6 8

**Comment by mnwright** [comment]
Thanks, fixed.
