### ISSUE TITLE
num.threads not respected by ranger::ranger function

### ISSUE THREAD

**Issue by alexzwanenburg** [imbs-hl/ranger#339]
I implemented the ranger::ranger function within a loop that is externally parallelised (using parallel::parLapply). To avoid competition across processes, I set num.threads to 1. However, each process is still attempting to maximise CPU use, which indicates that more than one thread is created.

When I disable external parallelisation, ranger still tries to maximise CPU use, despite num.threads=1.

My call to the ranger::ranger function is shown below:
```
model_obj      <- ranger::ranger(formula, data=dt,
                                     num.trees = 2^param$n_tree,
                                     sample.fraction = param$sample_size,
                                     mtry = ceiling(param$m_try*length(feature_cols)),
                                     min.node.size = param$node_size,
                                     alpha = param$alpha,
                                     splitrule = param$split_rule,
                                     importance = vimp_method,
                                     probability = fit_probability,
                                     num.threads = 1)
```
In the above code snippet, `param` is a list with model hyper-parameters, and `vimp_method` and `fit_probability` are likewise provided. These parameters should not affect threading.

I tried `num.threads=1L`, but this did not have any different effect.

The operating system is Windows 7 SP1 Build 7601, running on Intel i7-3770 CPU with 4 (8) cores and 32 GB of RAM. The version of Ranger is 0.10.1, with R 3.5.0.

If I am missing something obvious please let me know.

**Comment by alexzwanenburg** [comment]
Current usage is to predict a multinomial outcome. This outcome is a factor with four classes.

**Comment by mnwright** [comment]
Are you sure it actually _uses_ more than once core? In the current implementation there is still one child process started to grow the trees but the main thread should idle during that time. 

We should change this behaviour and don't spawn a new thread for `num.threads=1`, but I wanted to wait for the old RTools to vanish to clean up that part, see also #41 (now over two years old...).

Nevertheless, it shouldn't _use_ more than one core. Does it?

**Comment by alexzwanenburg** [comment]
This issue may be closed.

**Comment by arturio333** [comment]
Hey Alex, are you using Linux or Windows machine? 
I am running into some execution time issues on a Linux machine while on Windows it works fine. 
I am wondering if there are any changes to the parallel processing for Linux that additionally needs to be placed for memory usage.
