### ISSUE TITLE
Ranger sets predictions to zero if 'max depth' is reached before minimum node size is satisfied.

### ISSUE THREAD

**Issue by wbnicholson** [imbs-hl/ranger#340]
Hello,

I came across an issue regarding the interaction between the recent addition of "max depth" and minimum node size.  In the event that the max depth threshold is reached and the terminal node cardinality is greater than the minimum node size, a prediction of zero is returned.  

For example, see
 
`
mod=ranger(Infant.Mortality ~ ., max.depth=1,data = swiss)
predict(mod,data=swiss)$predictions
`
Would it be possible to still return a prediction even in the event that the minimum node size isn't reached or throw an error/warning?

**Comment by mnwright** [comment]
Thanks. This was a bug, we stopped splitting after `max.depth` was reached but did not set the prediction for the remaining nodes. 
Fixed now.
