### ISSUE TITLE
Feature request - tibble data argument

### ISSUE THREAD

**Issue by stephematician** [imbs-hl/ranger#342]
Ranger fails when a tibble is passed instead of a data.frame, I think chiefly because subsetting is slightly 'cleaner' with tibbles compared to data.frames - i.e. `response <- data[,dependent.variable.name]` returns a tibble with one column, rather than a vector as I think is desired (using `drop=T` can remedy this).

```r
ranger(data=as_tibble(iris), dependent.variable.name='Species')
```

Output:

    Error: Variable none not found. Ranger will EXIT now.
    Error in ranger(data = as_tibble(iris), dependent.variable.name = "Species") : 
      User interrupt or internal error.

In this case, treetype is inferred to be a survival tree, as `is.factor(response)` no longer returns true - and so ranger internally looks for the 'none' status variable in the data, which does not exist.

**Comment by mnwright** [comment]
Thanks, fixed. 
(It was already working with the formula interface, now also with the `dependent.variable.name` interface)
