### ISSUE TITLE
Feature Request: Bagging with a randomized split rule

### ISSUE THREAD

**Issue by wbnicholson** [imbs-hl/ranger#347]
While I'm aware that the [original extratrees algorithm ](https://link.springer.com/content/pdf/10.1007/s10994-006-6226-1.pdf) uses the entire data set in every tree, I think that it would be a logical extension for ranger to allow the combination of bootstrapping and discretization of the parameter split space (i.e. the option num.random.splits combined with "variance" splitrule).  This would be similar to the functionality in  [randomForestSRC](https://cran.r-project.org/web/packages/randomForestSRC/randomForestSRC.pdf) with the nsplit parameter.

Would this be a straightforward extension?

**Comment by mnwright** [comment]
Actually that is the way it's implemented in ranger. We are using bagging and random subspace in nodes and the underlying splitrule in "extratrees" for regression is "variance".

**Comment by wbnicholson** [comment]
Great, thanks for the clarification.
