### ISSUE TITLE
Ranger fails to read valid input data

### ISSUE THREAD

**Issue by dancooke** [imbs-hl/ranger#353]
Hi Marven,

A came across a case where the C++ Ranger library was throwing an exceptional whilst trying to read an input data matrix for prediction. Specifically, it cut reading a row short when it encountered a [sub-normal floating point number](https://en.wikipedia.org/wiki/Denormal_number), and therefore throws an exception for too few columns.

Since it didn't look like Ranger was doing anything wrong, I opened a [StackOverflow question](https://stackoverflow.com/questions/52410931/why-does-clang-stdostream-write-a-double-that-stdistream-cant-read) detailing this behaviour. Unfortunately, it looks like this is a compiler bug, and more worryingly, a defect in the C++ standard.

It might be worth adding some code to guard against these cases in Ranger. As [this answer](https://stackoverflow.com/a/52414829/2970186) points out, the value is read correctly, but the streams failbit is incorrectly set. So I'm assuming we could just check the value and clear the failbit if it is a subnormal value, something like:

```cpp
#include <cmath>

bool is_subnormal(const double x) noexcept
{
    return std::fpclassify(x) == FP_SUBNORMAL;
}

std::istream& read(std::istream& in, double& token)
{
    if (!(is >> token) && is_subnormal(token) {
        in.clear(std::istream::failbit);
    }
    return in;
}
```

I'm about to submit bug reports to Clang and the C++ standard, so I'd also keep an eye on the SO question. 

Best, Dan

**Comment by mnwright** [comment]
Thanks, should be "fixed" now.
