### ISSUE TITLE
Treatment of missing data in ranger

### ISSUE THREAD

**Issue by ProfBiscuit** [imbs-hl/ranger#358]
In the documentation it is said that the ranger can handle missing data, "Note that missing values are treated as an extra category while splitting", but will cease if missing data exists.

  Check missing values
  if (any(is.na(data.selected))) {
    offending_columns <- colnames(data.selected)[colSums(is.na(data.selected)) > 0]
    stop("Missing data in columns: ",
         paste0(offending_columns, collapse = ", "), ".", call. = FALSE)
}

What can I do to enable ranger to handle missing values in the predictors?

**Comment by mnwright** [comment]
The sentence "Note that missing values are treated as an extra category while splitting." only applies to GWAS data. 
For other data, no method to handle missing values is implemented. You'll have to handle them externally, e.g. with `Hmisc::impute()` or `mice::mice()`. Another alternative might be [missRanger](
https://cran.r-project.org/package=missRanger).

**Comment by dfrankow** [comment]
What is GWAS data?

**Comment by parsifal9** [comment]
Genome Wide Association Studies. A library called  GenABEL allows data in a GWAS format to be used directly in ranger.  
This is a bid disturbing. Single Nucleotide polymorphism are often encoded as {0,1,2} as factors.  Does it make sense to split on  {0,1,2, NA}
