### ISSUE TITLE
can I compare the importance variable metrics across samples?

### ISSUE THREAD

**Issue by randomgambit** [imbs-hl/ranger#366]
Hello there!

I am using this pretty nice package and I wonder if variable importance score that I see (using the permutation method) are comparable across samples.

For instance, one can always compare r-square or rmse across samples. But does it make sense to say that the variable with the highest importance score in sample A does not matter because it is still way smaller than the importance score of another variable in sample B?

Does that make sense to you?

Thanks!

**Comment by mnwright** [comment]
Maybe [SE](https://stats.stackexchange.com) or similar would be a better place for your question? 

My thoughts: 
The permutation importance is a difference of prediction accuracies (averaged over trees). If your original model (without permutation) has about the same accuracy in two samples, the permutation importances might be comparable. One could also calculate relative differences for this purpose.
