### ISSUE TITLE
R package Ranger produces errors related to variable “none”

### ISSUE THREAD

**Issue by JonnoB** [imbs-hl/ranger#371]
Hi
   I have been having some problems when using the variable name "none", when using sparse matrices it causes an error to be thrown when I predict on the test dataset. The error is

```
Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  index larger than maximal 5002
```
where 5002 refers to the number of variables. 

I have a longer question and also a reprex on stackoverflow below.

https://stackoverflow.com/questions/53651842/r-package-ranger-produces-errors-related-to-variable-none

**Comment by mnwright** [comment]
Thanks, fixed.

**Comment by JonnoB** [comment]
Thanks for being so quick! is there a simple explanation of what happened? if not no worries and thanks again.

**Comment by mnwright** [comment]
The variable name for the censoring status in survival forests was set to `"none"` in the case of non-survival outcomes. In prediction the dependent and status variables are excluded from the data and this excluded the `"none"` column, which in your case was a predictor and not the status variable. This variable was then missing from the final data used for prediction, giving that index error.
