### ISSUE TITLE
Formula can't use values from parent.frame

### ISSUE THREAD

**Issue by GregorDeCillia** [imbs-hl/ranger#373]
Hello,

I am currently refactoring a project of mine that extensively uses the functionalities of this package and face error messages of the form

     Error in myTransformation(responseVar) : could not find function "myTransformation" 

whenever `myTransformation` is part of a formula and locally scoped (not part of the global environment). Here is a reproducible example

    library(ranger)

    callRanger <- function() {
      myTransformation <- function(x) { x }
      ranger(myTransformation(Species) ~ ., data = iris)
    }

    callRanger()
    #> Error in myTransformation(Species) : 
    #>   could not find function "myTransformation" 

I am pretty sure the issue lies in [formula.R#16](https://github.com/imbs-hl/ranger/blob/cb3f2e030cfb23dda164ff7d5750500829e6ad7f/R/formula.R#L16), where the parsing uses `base::eval` which becomes

    base::eval(myTransformation(Species), envir = iris, enclos = baseenv())

in this case. I would be glad to provide a PR that makes sure that variables from the calling environment can be used as well in formulas.

**Comment by mnwright** [comment]
Thanks. Yes, this implementation of the formula interface is somewhat limited. It works for adding/removing variables with `+` / `-` and for interactions with `:` / `*`. I'd welcome a PR.

Btw., I came up with my own implementation because I wasn't able to find a good implementation of the formula interface which supports this and is fast. Suggestions are very welcome!

**Comment by GregorDeCillia** [comment]
I just added a minimal fix which only affects the way the LHS is parsed. For the RHS of the formula it might be best to use `stats::model.frame` but I don't have time to further delve into this right now.

```r
model.matrix(am ~ wt*mpg, data = mtcars) %>% head
#>                   (Intercept)    wt  mpg wt:mpg
#> Mazda RX4                   1 2.620 21.0 55.020
#> Mazda RX4 Wag               1 2.875 21.0 60.375
#> Datsun 710                  1 2.320 22.8 52.896
#> Hornet 4 Drive              1 3.215 21.4 68.801
#> Hornet Sportabout           1 3.440 18.7 64.328
#> Valiant                     1 3.460 18.1 62.626
```

I supppse `model.matrix`  should have good performance given it is part of "the core" of R with a C backend.

**Comment by mnwright** [comment]
Thanks for the PR, it's merged already. 

On `model.frame` and `model.matrix`: 

````R
library(ranger)
library(microbenchmark)
n <- 1e6
p <- 1e2
dat <- data.frame(y = rbinom(n, 1, .5), replicate(p, rnorm(n)))
formula <- y ~ .

# Benchmark
microbenchmark(ranger = ranger:::parse.formula(formula, data = dat), 
               model.frame = model.frame(formula, data = dat), 
               model.matrix = model.matrix(formula, data = dat), 
               times = 10, unit = "s")

# Unit: seconds
# expr         min          lq         mean       median          uq         max neval
# ranger       0.000704505 0.000716551 0.0008193441 0.0008278805 0.000878998 0.001028889    10
# model.frame  2.117043560 2.212959064 2.2342427088 2.2362143065 2.298291479 2.304019956    10
# model.matrix 2.516874224 2.682357459 2.7099387068 2.7212754540 2.756497921 2.874697586    10
```

**Comment by GregorDeCillia** [comment]
Thaks for the merge.

That benchmark is very suprising to me. In this case it would probably be best to extend your implementation in case more flexibility is required for the RHS. 

That said, monotone transformations of independent variables are not really useful due to the nonparametric nature of RF. So from my point of view this issue can be closed.
