### ISSUE TITLE
std::bad_alloc error 

### ISSUE THREAD

**Issue by CaptainEmerson** [imbs-hl/ranger#377]
I was trying to do k-fold cross validation, but kept getting std::bad_alloc errors or my R process getting killed. Here's a reproducible example:

```
library(ranger)
set.seed(123)
data <- data.frame(replicate(404813,
                             sample(runif(100, 0.0, 100.0), 4753, rep = TRUE)))
print(1)
ranger(dependent.variable.name = 'X1', data = data[-c(100,200), ])
gc()
print(2)
ranger(dependent.variable.name = 'X1', data = data[-c(100,200), ])
gc()
print(3)
ranger(dependent.variable.name = 'X1', data = data[-c(100,200), ])
gc()
print(4)
ranger(dependent.variable.name = 'X1', data = data[-c(100,200), ])
gc()
```

Output:

```
Loading required package: RcppEigen
Loading required package: Matrix
Loading required package: grid
Loading required package: lattice
Loading required package: Rcpp
[1] 1
Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 31 seconds.
[1] 2
Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
[1] 3
Error: std::bad_alloc Ranger will EXIT now.
Error in ranger(dependent.variable.name = "X1", data = data[-c(100, 200),  : 
  User interrupt or internal error.
```

I'd expect either the script to fail at the first ranger call or complete the script. My wild guess is that there's a memory leak.

Environment info:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux buster/sid
ranger_0.10.1
```

Thank you for your otherwise excellent package.

**Comment by mnwright** [comment]
Hm... Hard to reproduce. Your example runs through on a linux machine with 96 GB. How much memory do you have? 
Could you try setting the same seed before each run?

**Comment by CaptainEmerson** [comment]
I have 64GB of memory.

I agree it's hard to reproduce -- I'm having trouble doing it myself now. Whether it can be reproduced seems dependent on the amount of memory other processes are consuming, because when this program is the only R process I've got running, it completes fine. That's an okay workaround for me at the moment.

If I have time to try to improve reproducibility, I'll set the same seed before each run as you suggest, and try to bound the amount of memory available to the R process with [control groups](https://unix.stackexchange.com/a/125024).

**Comment by mnwright** [comment]
On my 96 GB machine the memory usage was somewhere around 64 GB most of the time. It might just be random effects and no memory leak.

**Comment by CaptainEmerson** [comment]
That's fair. It seems like the message "std::bad_alloc" could be wrapped into something more R-ish.

**Comment by mkb007** [comment]
@mnwright The "std::bad_alloc" message and ranger termination on Windows may be due to memory fragmentation.   Both R and C++ have separate heaps within one Windows process.  If the R heap contains unused and unreleased memory that can be garbage collected when C++ is attempting to allocate memory from its heap, the C++ allocation may fail even with lots of virtual memory. 

The work around is to put a call to gc() immediately before the call to ranger() in the user's R code.  This may be in addition to using the save.memory option and may eliminate the need to use the save.memory option.

Hopefully, this helps others searching for solutions to "std::bad_alloc."

**Comment by marliwd** [comment]
I was originally getting std::bad_alloc error, and then I tried running gc() prior to calling ranger. Now I'm getting:

terminate called without an active exception

I can run with fewer rows as well. Currently attempting 1.5 million rows, 10 columns. I'm running on a Fedora HPC and have allocated 

rlimit_as(8e10)
options(future.globals.maxSize= 4e10)
