### ISSUE TITLE
Combination of case.weights and class-wise sampling not supported

### ISSUE THREAD

**Issue by Maziarrr** [imbs-hl/ranger#381]
I got an Error: Combination of case.weights and class-wise sampling not supported. I think this is important as the class imbalance problem occurs frequently in practice.

**Comment by mnwright** [comment]
Both options are changing the sampling probabilities for observations. How should the two work at the same time?

**Comment by Maziarrr** [comment]
For class imbalance problem, I suggest adding stratified sampling option (equal-sized bootstrapped samples from each strata, i.e. class). 
No matter what case weights one assigns, each tree should be trained on equal number of instances from each class. So, there is no need to use weights to mitigate the class imbalance problem.

**Comment by mnwright** [comment]
I think you misunderstood the `case.weights` argument (which is different from the way weights are implemented in many other packages). From the ranger R help: 

> Weights for sampling of training observations. Observations with larger weights will be selected with higher probability in the bootstrap (or subsampled) samples for the trees.

We currently have two options to change the sampling (e.g. for stratified sampling): 
- `case.weights`: Change sampling probabilities for every observation
- `sample.fraction`: Change class-wise sampling probabilities (See https://github.com/imbs-hl/ranger/issues/167#issuecomment-358294215 for an example) 

These two options cannot be used at the same time (the error message you got).

There is one option for "classical" weighting: `class.weights`, which weights the classes in the splitting rule and in the majority voting (if not in probability mode). 

A combination of stratified sampling and class weights is possible. Is that what you want to do?
