### ISSUE TITLE
What does sampling without replacement mean in ranger?

### ISSUE THREAD

**Issue by Mazata** [imbs-hl/ranger#386]
Hello there!

First of all, thank you for this great package! I am using the C++ implementation extensively and am just now noticing that there is a --noreplace argument one can use. At first I thought that when a fraction of the training data has been used to grow one tree, it is not reused to grow another tree, but that would mean that a fraction value above 0.5 would limit the forest to 1 tree or create trees with vastly different depths.
Therefore I am wondering what --noreplace does in ranger.
Can you help?

Thanks a lot,
Theo Bernier

**Comment by mnwright** [comment]
With `--noreplace` (`replace = FALSE` in R), each tree just randomly draws observations without replacement (independent of other trees). The number of observations is set with the sample fraction argument.

**Comment by Mazata** [comment]
So you mean that without the --noreplace argument, the same training point can be used several times in the growth of a single tree?  It hadn't occurred to me that this was a possibility, thank you for clearing things up!

**Comment by mnwright** [comment]
Yes. That is how bagging usually works.
