### ISSUE TITLE
Estimated time remaining highly inaccurate

### ISSUE THREAD

**Issue by LukeTheGit** [imbs-hl/ranger#392]
Hi there,

Not so much of an issue as it is a note. I am running ranger using caret's `train` function over ~200k records with 23 variables with the following parameters:
metric="ROC",
method="ranger",
tuneGrid = expand.grid(
                    mtry = c(2, 5, 8, 18,23),
                    splitrule = c("gini", "extratrees"), 
                    min.node.size=c(1,5,10)),
trControl = trainControl(
  summaryFunction = twoClassSummary,
  classProbs = TRUE,
  verboseIter = FALSE,
  savePredictions = TRUE,
  index = myFolds
)
myFolds = 5 folds

While running this, I got some progress updates:
Growing trees.. Progress: 66%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 31 seconds.

In reality, it took over 15 mins to run even after these updates said it would only take ~20 more seconds. The % may have been correct (even the fact it was backtracking), but with backtracks it isn't super helpful.

I don't know if there is a solution to this apart from removing these notices or just having pedants like myself live with it!

Cheers,

Luke

**Comment by mnwright** [comment]
That's a problem with caret, not ranger. `caret::train()` runs several ranger models for parameter tuning and the output is of the single `ranger()` calls. However, `caret::train()` has a `...` argument and you should be able to pass `verbose = FALSE` to disable the progress output of ranger.

**Comment by LukeTheGit** [comment]
That makes sense, I will copy this over to that area, then. Thanks for the quick response!
