### ISSUE TITLE
Survival forest: How can I see if ranger treats a variable as ordered or unordered?

### ISSUE THREAD

**Issue by l47y** [imbs-hl/ranger#396]
Hey, 

On my dataset I have some factor variables which are ordered and some which are unordered. I would like to tell ranger which of my variables are unordered and which of them are ordered. And I would like to avoid converting the ordered factor variables to integer or dummy variables. Now, by reading some other Issues and by my actual understanding I would do the following: 

```R
train <- data.table("eins" = sample(c("a", "b", "c"), n, replace = T), 
                    "drei" = sample(c("a1", "a2", "a3", "a4" ,"a5"), n, replace = T))
train$eins <- factor(train$eins, ordered = T)
train$drei <- factor(train$drei, ordered = F)
```
And later: 
```R
ranger(...(other arguments), respect.unordered.factors = T)
```
Now I should have ranger treating "eins" as an ordered factor variable and "drei" as an unordered one. Is that correct? I tried to check that by looking at the split values of treeInfo of some trees. The split values gave me for "drei" only values 1.5, 2.5, 3.5, 4.5, which for me seems like if ranger treated "drei" as well as ordered. I tried to check if the execution time of ranger differs when setting "drei" to ordered or unordered, but in my experiments there was no difference, even for "drei" having 20 factors. 

I made another observation: Setting splitrule to "extratrees" leads to really different split values in treeInfo: Now there are values like 2.32343, 2.8742. I was wondering if there was a different handling in ranger of the "orderness" of a variable when setting splitrule to "extratrees". 

Edit: I guess the splitpoint in extratrees is just the random number which you use to randomly assign a splitpoint, right? 

So my final question is: How can I force ranger to treat some variables as ordered and some as unordered? And how can I check after the ranger execution that my factor variable ordering was treated in the way I wanted to? And maybe would you explain something about how to interpret the splitvalues given for a tree by the treeInfo() function. 

Thanks alot again for you help! 

PS: Here is the code which I used to play around and SessionInfo(): 
```R
library(ranger)
library(survival)
library(data.table)

n  <- 10000

target <- sample(1:100, n, replace = T)
event <- sample(c(0,1), n, replace = T, prob = c(0.8, 0.2))
mySurv <- Surv(time = target, event = event)

train <- data.table("eins" = sample(c("a", "b", "c"), n, replace = T), 
                    "drei" = sample(c("a1", "a2", "a3", "a4" ,"a5"), n, replace = T))
train$eins <- as.factor(train$eins)
train$drei <- as.character(train$drei)


model <- ranger(mySurv ~ ., data = train, num.trees = 2000, splitrule = "extratrees", 
max.depth = 12, importance = "impurity", num.threads = 10, verbose = TRUE, 
write.forest = T, respect.unordered.factors = T)
```
```R
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS/LAPACK: /applvg/os/usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.11.8 survival_2.41-3   ranger_0.11.1    

loaded via a namespace (and not attached):
[1] compiler_3.4.3  Matrix_1.2-12   tools_3.4.3     yaml_2.2.0      Rcpp_1.0.0      splines_3.4.3   grid_3.4.3      lattice_0.20-35
```

**Comment by l47y** [comment]
Okay I have found my error after playing around a bit again:
Setting respect.unordered.factors = "partition" does exactly what I want. treeInfo() has now the desired output. This is also stated in your documentation. I was confused, because setting respect.unordered.factors to TRUE according to my understanding would have given me a result with unordered factors. So just a finishing question: Why does respect.unordered.factors = TRUE correspond to respect.unordered.factors = "order"?

**Comment by mnwright** [comment]
With `respect.unordered.factors = TRUE` aka `respect.unordered.factors = "order"`, the factor levels are pre-sorted, see [http://dx.doi.org/10.7717/peerj.6339](http://dx.doi.org/10.7717/peerj.6339) for details. The resulting order is saved in `rf$forest$covariate.levels`, where `rf` is your ranger object. 

With `respect.unordered.factors = "partition"`, every **un**ordered factor or character will be splitted with trying all 2-partitions. However, there is an exception for `splitrule = "extratrees"`, where we use the original approach for extremely randomized trees, described in [Geurts et al. (2006)](https://doi.org/10.1007/s10994-006-6226-1).

Sorry for the confusing interface, it's very hard to change existing arguments with reverse dependencies and we needed a third option for unordered factors.

**Comment by l47y** [comment]
Thanks for you answer; now everything is clear for me and I understand that its very complicated to change afterwards.
