### ISSUE TITLE
Depth of terminal node prediction

### ISSUE THREAD

**Issue by BlindApe** [imbs-hl/ranger#397]
I'm interested in predict in a new dataset, for each tree, the terminal node and the depth of each of them. Is there a way to do it?
Are the number of each node a kind of fixed sequence that let to know the depth?
By example, if 0 is the root node, 1 and 2 are always used for depth 1, (3, 4, 5, 6) for depth 2 and so on we may compute the depth, but if you assing the node number in other way, could you help us to get the depth of each terminal node?

Thanks

**Comment by talegari** [comment]
@BlindApe 
[depth_terminalNodes](https://github.com/talegari/solitude/blob/master/R/predict.R) is an unexported function from 'solitude' package to get the depths of terminal nodes. 

``` r
m <- ranger::ranger(Species ~., data = iris)
solitude:::depth_terminalNodes(ranger::treeInfo(m, 1))
#>  2  7  9 10 11 13 14 15 
#>  1  3  3  4  4  4  5  5
```

**Comment by mnwright** [comment]
Cool. I didn't know that function. It just seems it uses 1-indexing while `treeInfo()` uses 0-indexing, be careful!
