### ISSUE TITLE
Complie Error in Linux： expected unqualified-id before ‘.’ token

### ISSUE THREAD

**Issue by wangdaiyin** [imbs-hl/ranger#398]
when i complie ranger with reference to this description: 

>Standalone C++ version
>To install the C++ version of ranger in Linux or Mac OS X you will need a compiler supporting >C++11 (i.e. gcc >= 4.7 or Clang >= 3.0) and Cmake. To build start a terminal from the ranger >main directory and run the following commands

>cd cpp_version
>mkdir build
>cd build
>cmake ..
>make

in the "make" step, error happens:$make
[  5%] Building CXX object CMakeFiles/ranger.dir/src/Forest/Forest.o
/home/WDY/ranger-master/cpp_version/src/Forest/Forest.cpp:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/Forest.cpp
 ^
make[2]: *** [CMakeFiles/ranger.dir/src/Forest/Forest.o] Error 1
make[1]: *** [CMakeFiles/ranger.dir/all] Error 2
make: *** [all] Error 2

How can I solve this error？Thanks

**Comment by wangdaiyin** [comment]
![image](https://user-images.githubusercontent.com/10666762/54741612-f623ec00-4bf9-11e9-8bf6-3667aa29c729.png)

**Comment by mnwright** [comment]
This looks like the symbolic links are not correctly working on your system. How did you download the package? Was a Windows system involved somewhere (Windows cannot handle symbolic links)? Please check your `cpp_version/src/Forest` directory, you should find symbolic links to the files in `src/`.

**Comment by wangdaiyin** [comment]
Thanks for your answer. The issue has been resolved.

**Comment by systek17** [comment]
How was the issue resolved???
