### ISSUE TITLE
quantile regression sampling from the distribution

### ISSUE THREAD

**Issue by laurapoggio-sptools** [imbs-hl/ranger#399]
In the package quantregForest it is possible to use the predict to get N sampled observations from the conditional distribution:
Example:
`## sample 10 new observations from conditional distribution at each new sample
newSamples <- predict(qrf, Xtest,what = function(x) sample(x,10,replace=TRUE))
`
Is it possible to get the same from the predict in ranger from a model obtained with `quantreg = TRUE`?

Thanks in advance for any pointers.

**Comment by sheffe** [comment]
There is probably an official answer from Marvin & team that improves on this, but I've been using `ranger` to replace that feature in a three-step process: 

1. for each tree, take the OOB samples and predict their terminal node IDs; get a 4-column table of train_obs_ID, y_train, tree_ID, and node_ID.
2. for each tree, for each new observation, predict the terminal node ID; get a 3-column table of new_obs_ID, tree_ID, and node_ID.
3. join the tables by tree_ID and node_ID, group on tree_ID and new_obs_ID, and (for a target sample size of N) sample N/n_tree observations of y_train using your preferred sampling scheme.

(Not directly answering your question, but I've found it helpful to use `data.table` and its `by=.EACHI` feature for joins like this -- especially for large problems the join-then-downsample pattern can blow up in size. You might need `allow.cartesian = TRUE`, basically overruling a feature in `data.table` that prevents accidental misspecified joins that often look like this. For *really huge* problems, I try to do a stratified subsample of the training observations before attempting a join, and you can test whether your sample quantiles look similar by doing that a few times. You can also go slowly, and do a handful of new observation samples at a time that you later row-bind. This amounts to a similar concept as the `.EACHI` suggestion but gives extra flexibility.)

**Comment by laurapoggio-sptools** [comment]
Thanks a lot. This really helps to solve the problem.

**Comment by mnwright** [comment]
Thanks for the suggestion, added. Actually, it was just a single line of code to add (besides adding the argument and some tests and docs). :)

**Comment by sheffe** [comment]
> There is probably an official answer from Marvin & team that improves on this.

Well, *that* was an easy prediction.

Thank you! This is extremely useful -- allows construction of full prediction intervals, straight from ranger.

**Comment by laurapoggio-sptools** [comment]
Thank you very much! Very useful
