### ISSUE TITLE
conditional variable importance scores for correlated explanatory variables

### ISSUE THREAD

**Issue by brfitzpatrick** [imbs-hl/ranger#405]
I realise that I can use 'party' for this however the ability to combine some of ranger's other features (e.g. split.select.weights) with 'party' style conditional variable importance scores would make ranger applicable to an even broader set of use cases.  If there is an alternative method I'd also be very interested to know.  Thanks for the great package.

**Comment by mnwright** [comment]
The conditional variable importance in party has several issues: 
- It's extremely computationally intensive
- It's dependent on `mtry` and often requires `mtry = p`
- It doesn't provide an option for statistical testing

I would use our recently proposed **cpi** method, described [here on arXiv](https://arxiv.org/abs/1901.09917v3), available [here on GitHub](https://github.com/dswatson/cpi). Example: 

````R
library(mlr)
library(cpi)

# Convert 2-level factor to binary
task <- createDummyFeatures(bh.task, method = "reference", cols = "chas")

# Run CPI
cpi(task = task, learner = makeLearner("regr.ranger"), 
    resampling = makeResampleDesc("CV", iters = 5))
````

You can use any supervised learner you like 
````R
cpi(task = task, learner = makeLearner("regr.svm"), 
    resampling = makeResampleDesc("CV", iters = 5))
````

And for ranger I just added an option to use out-of-bag data: 
````R
cpi(task = task, learner = makeLearner("regr.ranger", keep.inbag = TRUE), 
    resampling = "oob")
````

**Comment by brfitzpatrick** [comment]
Impressive, thank you!
