### ISSUE TITLE
Implementation of RF for bounded outcomes

### ISSUE THREAD

**Issue by bryorsnef** [imbs-hl/ranger#407]
I just came across the paper (https://arxiv.org/pdf/1901.06211.pdf), which seems to have a feature I'd be very interested in trying out, since I'm working with some bounded data. The paper says this is already implmented in ranger, but I don't see any information in the documentation or in discussions here. Is the feature implemented by not documented? Or are there plans to enable it?

**Comment by mnwright** [comment]
It's currently in the "betasplit" branch here on Github. To install use `devtools::install_github("imbs-hl/ranger", ref = "betasplit")`. It will be merged into the master later. 

Btw., we have an updated version of the preprint, I'll ask my co-authors to update it on arXiv.
