### ISSUE TITLE
extratrees: add note to docs with difference to original 

### ISSUE THREAD

**Issue by mnwright** [imbs-hl/ranger#408]
The original [Extremely randomized trees](http://dx.doi.org/10.1007/s10994-006-6226-1) do not use bagging, see https://stats.stackexchange.com/questions/406666/what-exactly-is-the-extratrees-option-in-ranger. 

We should note this in the docs and give an example how to run the original version.

**Comment by DeFilippis** [comment]
What was the reason that the default implementation of extratrees decided to use bagging?

**Comment by mnwright** [comment]
As noted in a comment on SE (link above): The other parameters shouldn't change when just selecting another split rule.

**Comment by mnwright** [comment]
Docs changed in #701.
