### ISSUE TITLE
[Benchmark] Comparison with Intel DAAL RF (suspicious chart)

### ISSUE THREAD

**Issue by fradav** [imbs-hl/ranger#409]
Hello,

Have you seen this (especially the benchmark chart at the end) ?
https://software.intel.com/en-us/articles/intel-data-analytics-acceleration-library-decision-forest

The fact this is compared against "Apache Ranger 0.7.1" (which doesn't have to do anything with random forests) seems to be highly suspicious. A quick look at the code there : https://github.com/intel/daal/tree/daal_2019_update3/algorithms/kernel/dtrees
shows nothing but ordinary implementation (but I may be wrong) of breiman's RF.
If their RF implementation were so clearly above ranger's one in computation efficiency, I would like to see a breakthrough paper about this but I can't find any.

**Comment by mnwright** [comment]
We haven't compared against DAAL. I agree that "Apache Ranger" looks suspicious. Also a benchmark on three datasets without any information on parameter settings is close to useless as a general guideline. 

A proper benchmark would be very interesting.

**Comment by mnwright** [comment]
Please reopen if you find a proper comparison.
