### ISSUE TITLE
Add restriction for unique.death.times

### ISSUE THREAD

**Issue by nblaffey** [imbs-hl/ranger#410]
Would it be possible to add functionality to restrict the number of unique.death.times used? I am working with a data set with a very large number of unique death times, and considering matrices are calculated showing the survival and CHF at each time index for every observation it really slows down computation and increases memory usage. Randomforestsrc has a "ntime" variable that will calculate the survival probability for only a subset of the actual unique death times, would it be possible to implement this in ranger or are there any workarounds?

**Comment by mnwright** [comment]
Related to https://github.com/imbs-hl/ranger/issues/202#issuecomment-313876174. 

I think we should add the option. It would also be nice to specify the exact time points to use. 

Workaround: Manually restrict the time points in the data. You could check the code of RFSRC to see what exactly they do.

**Comment by mnwright** [comment]
Btw., RFSRC is using (see https://github.com/kogalur/randomForestSRC/blob/fefe2aa44a184f522136079b1419163f67fb6cd6/src/main/resources/cran/R/utilities.survival.R#L95-L98)
````R
time.interest <- time.interest[unique(round(seq.int(1, length(time.interest), length.out = ntime)))]
````
where `time.interest` are sorted unique event times and `ntime` is the number of timepoints to use (default 150). Any they also allow the user to specify the time points to be used.

**Comment by mnwright** [comment]
Done in #700.
