### ISSUE TITLE
Slightly general interface for the response

### ISSUE THREAD

**Issue by mayer79** [imbs-hl/ranger#411]
Rangers, here two ideas to be slightly more flexibel regarding the response variable:

1) If response is of type logical, we get an error

```
library(ranger)

iris$setosa <- iris$Species == "setosa"

# Logical response could be mapped to binary classification
fit <- ranger(setosa ~ Sepal.Width, data = iris)
# Gives: Error: Unsupported type of dependent variable.
```
It would be fantastic if `ranger` would convert it to 0-1 automatically and go for classification per default. Default could be overwritten by `probability` and `classification` arguments. Predictions would be either 0/1 or class probabilities.

2) The description of `classification` argument is: "Only needed if data is a matrix. Set to TRUE to grow a classification forest." To stress the fact that this argument can be used to grow a classification forest even if the data is a data.frame and the response is numeric, you could instead say: "Set to TRUE to grow a classification forest. Only needed if the data is a matrix or the response is numeric."

**Comment by mnwright** [comment]
Thanks, I agree on both suggestions.

**Comment by mayer79** [comment]
Maybe we could also convert character responses to factors like e.g. "lm" does?
