### ISSUE TITLE
Facing the error "Error in x[, i] <- frame[[i]] :    number of items to replace is not a multiple of replacement length".

### ISSUE THREAD

**Issue by madhurgupta27** [imbs-hl/ranger#413]
Hi there.
I'm using the ranger package for survival forests on large data (~0.5 million observations).
Since the package seems to be stuck when I mention the formula instead of dependent.variable.name, I am first creating a Survival object as a variable in the dataset by using the function Surv()  and then running the ranger function on that.
I'm attaching the data (note that monthlap is the month of churn and islapsed is indicator if the customer is churned). 
The code is as follows:

```
# Making the survival object variable
train$surv_obj <- Surv(train$monthlap, train$islapsed)

# Running the ranger model
ranger_model = ranger(dependent.variable.name = "surv_obj",
                           data=train4, num.trees = 100, mtry = 4, verbose = TRUE, 
                           seed = 1000 )

# ERROR:
Error in x[, i] <- frame[[i]] : 
  number of items to replace is not a multiple of replacement length
```

[sample_data.zip](https://github.com/imbs-hl/ranger/files/3341612/sample_data.zip)

Please help! I'm in urgent need.

**Comment by mnwright** [comment]
To use the `dependent.variable.name` interface with survival data use: 

````R
library(ranger)
library(survival)
#ranger(Surv(time, status) ~ ., data = veteran)
ranger(dependent.variable.name = "time", status.variable.name = "status", data = veteran)
````

I will check whether your option with a survival object in the `dependent.variable.name` is also possible to implement.

**Comment by mnwright** [comment]
This should work since version 0.11.5 (not on CRAN yet):

````R
library(ranger)
library(survival)
dat <- data.frame(surv = Surv(veteran$time, veteran$status), veteran[, c(-3, -4)])

# These are all the same 
ranger(Surv(time, status) ~ ., data = veteran)
ranger(dependent.variable.name = "time", status.variable.name = "status", data = veteran)
ranger(dependent.variable.name = "surv", data = dat)
ranger(y = Surv(veteran$time, veteran$status), x = veteran[, c(-3, -4)])
ranger(y = veteran[, 3:4], x = veteran[, c(-3, -4)])
```
