### ISSUE TITLE
Which RNG are you using?

### ISSUE THREAD

**Issue by nalzok** [imbs-hl/ranger#414]
Hi there,

I wonder which random number generator are you using? A quick search revealed that you are using `std::mt19937_64` in many places, but I think it's better to confirm with you guys.

If it is, would you consider switching to [xoshiro256**](http://xoshiro.di.unimi.it) or the [PCG-family](http://www.pcg-random.org), which appear to be state-of-the-art PRNGs? Both seem to have superior speed and quality compared to the Mersenne Twister (MT19937-64), so you might want to check it out if random number generation is your bottleneck.

**Comment by mnwright** [comment]
Yes, we are using `std::mt19937_64`. To be honest, we didn't spend much thought on it and just went for the standard. What I think we should do is: 

1. Make it easy to change the RNG, e.g., by a wrapper 
2. Investigate whether the RNG is the bottleneck somewhere

**Comment by nalzok** [comment]
Cool. Hopefully, that won't be too much work.

**Comment by mnwright** [comment]
Let's continue in #688.
