### ISSUE TITLE
Allow mtry to be a function of number of variables

### ISSUE THREAD

**Issue by talegari** [imbs-hl/ranger#415]
Hi Marvin,

**Request**: `mtry` should accept a function that considers number of variables and returns an positive integer

**Background**: I ran into this while implementing an variant of RFE and tuning mtry. Sometimes, it might be user friendly to say 'use half of variables available' or some heuristic.

Let me know if this is a good idea and you are open for a PR.

Regards,
Srikanth

**Comment by mnwright** [comment]
Yes, that's a very good idea. PR very welcome!

**Comment by mnwright** [comment]
Thanks for the PR, merged.
