### ISSUE TITLE
Using case.weights with cross validation

### ISSUE THREAD

**Issue by marisalyn** [imbs-hl/ranger#419]
Hi,

I'm trying to use ranger with case.weights and cross validation via caret. 

I can use ranger with caret successfully with the case.weights, however, when I introduce CV, I get the error "Number of case weights not equal to number of samples". 

Is there a way to successfully incorporate case.weights with cross validation?

Thanks!

**Comment by mnwright** [comment]
The problem is probably that caret does not select the appropriate case weights when training on the CV folds. If you do the CV manually, it's easily done: 

````R
library(ranger)

n <- nrow(iris)
num_folds <- 10

case_weights <- runif(n)

folds <- split(sample(n), cut(1:n, num_folds, labels = FALSE))

sapply(folds, function(fold) {
  test <- iris[fold, ]
  train <- iris[-fold, ]
  
  rf <- ranger(Species ~ ., train, case.weights = case_weights[-fold])
  pred <- predict(rf, test)$predictions
  mean(pred != test$Species)
})
````

**Comment by marisalyn** [comment]
Hey Marvin ,

Thanks for the response and example code! This is what I assumed, and I went ahead and wrote up my own CV, as you suggested. I'm glad you could confirm this was the likely issue. 

Marisa
