### ISSUE TITLE
predictions in the model is different from prediction by predict()

### ISSUE THREAD

**Issue by hideaki** [imbs-hl/ranger#421]
I might be missing something, but predictions returned as part of the model is different from prediction made by predict().
It seems generally much worse than the one made by predict().
Shouldn't they give same result?

Reprex:
```
model <- ranger::ranger(mpg~cyl+hp, mtcars)
predictions_in_model <- model$predictions
predictions_by_predict <- predict(model, mtcars)
predictions_by_predict$predictions - predictions_in_model # The result is not vector of zeros.
```

**Comment by mnwright** [comment]
The `model$predictions` are out-of-bag predictions. These should usually be worse than predictions on the training data because they are an estimate of out-of-sample predictions.

**Comment by hideaki** [comment]
That makes sense. Thank you for the explanation!
