### ISSUE TITLE
Predictions in case of equal number of tree votings for all classes

### ISSUE THREAD

**Issue by LNA28** [imbs-hl/ranger#422]
Could you tell me how the outcome class is determined if the random forest predictions lead to the same number of trees for every class? E.g. I have a binary classification problem and I used 500 trees for my calculation. For some datapoints 250 of the trees vote for class "0" and 250 trees vote for class "1" (according to the predict command using paramter 'predict.all=TRUE'). It seems the outcome is selected by some random procedure, because the outcome class produced by the predict command (with 'predict.all=FALSE') differs for these cases. For some datapoints the output is class '0', for some '1'.

**Comment by mnwright** [comment]
Yes, in case of ties one class is selected randomly. The same applies to terminal nodes in the trees.
