### ISSUE TITLE
Large negative importance value for class weight < 1

### ISSUE THREAD

**Issue by limeng12** [imbs-hl/ranger#438]
Hi, 

I want to use class weights to correct unbalance dataset,
But when I set class weight < 1, the importance of many features < 0, especially some actually important features.

**Comment by mnwright** [comment]
Could you try to provide a reproducible example with simulated data? Thanks!

**Comment by limeng12** [comment]
Here it is:
`library(ranger);

data<-data.frame(Res=c(rep(1,200),rep(2,100)),
                 b=runif(300,0,1),
                 d=runif(300,0,1) ,
                 e=runif(300,0,1),
                 a=c(rep(3,200),rep(5,100)) );

data[,"Res"]<-as.factor(data[,"Res"]);

Y<-data[,"Res"];
w <- 1/table( Y );
w <- w/sum(w)
weights <- rep(NA, length(Y));
weights[Y == rownames(w)[1]] <- w[rownames(w)[1]];
weights[Y == rownames(w)[2]] <- w[rownames(w)[2]];

#w<-w/min(w);
#randomForest_model<-ranger(formular,data,importance="impurity_corrected",case.weights=weights);

randomForest_model<-ranger(Res~.,data,importance="impurity_corrected",
                           num.trees=500,class.weights= as.numeric(w) );


importance(randomForest_model )`

**Comment by mnwright** [comment]
Thanks, fixed.
