### ISSUE TITLE
Predict function returns same survival predictions for all subjects

### ISSUE THREAD

**Issue by jmpanfil** [imbs-hl/ranger#440]
Relevant setup info

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

ranger_0.11.2
```
I am using a sparse matrix as input with ~45,000 subjects, 2 independent variables (one continuous, one binary 0/1). If I use an input without the time and event fields for the predict function, the predictions are the same for each individual. If I use an input with either the original time and event fields, or just made up values for those fields, then the predictions vary for each subject. Why is that? When new data comes in, I would not want to have to add meaningless columns to get a proper prediction.

Code: 
```
surv <- 
  ranger(data = sparse_inp, 
         num.trees = 500, 
         dependent.variable.name = "Time",
         status.variable.name = "Event", 
         seed = seed, 
         max.depth = NULL)

pred <- predict(surv, data = sparse_inp[ , c("x1", "x2")])
```

The sparse input has columns x1, x2, Time, Event.

**Comment by mnwright** [comment]
Thanks, should be fixed with the interface changes I just merged.
