### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by rtlprmft** [imbs-hl/ranger#446]
It would be amazing to have a simple progress indicator. My suggestion is to add
*verbose_out << "." << std::flush;
after
trees[i]->grow(variable_importance);
in Forest::growTreesInThread in src/Forest.cpp.
Maybe there could even be a command line flag to turn this feature on/off.

**Comment by mnwright** [comment]
We already have a progress indicator, see here: https://github.com/imbs-hl/ranger/blob/dfcd9660ee53e592c7e1eff14e90a39306fae763/src/Forest.cpp#L1007

Every 30 seconds, it shows the percentage of already finished trees and gives an estimate of the remaining time.

**Comment by rtlprmft** [comment]
Thanks for the answer, The 30s are the culrpit, my training right now does not take 30s. My mistake.

I stumbled over the idea when I realized that training with --splitrule 6 (BETA) never finishes and I wanted to see whether it is just slow or runs into an endless loop (actually the last is the case, it never finishes calculation of the first tree, or I was not patient enough). 

So I assume that the mentioned progress indicator is only shown when a tree was successfully grown, because I do not see it (running BETA for at least 15min).

**Comment by mnwright** [comment]
> So I assume that the mentioned progress indicator is only shown when a tree was successfully grown, because I do not see it (running BETA for at least 15min).

Yes, exactly. 

Could you open a new issue with the the BETA splitting problem? Best with a data example or good description of the data. Maybe it can be improved.

**Comment by rtlprmft** [comment]
Will so.
