### ISSUE TITLE
Problem with BETA splitting

### ISSUE THREAD

**Issue by rtlprmft** [imbs-hl/ranger#449]
I tried to use --splitrule 6, but while training with all other rules finished in a few seconds, this one never finishes, or I am too impatient to wait. I am using the most recent "git clone".

The command, I am using is
ranger --file ranger.txt --outprefix ranger --depvarname True --verbose --treetype 3 --impmeasure 1 --write --splitrule 6

The input file is attached. (Actually, that is a subset of the columns that I am using in real life to keep it simple)

[ranger.txt](https://github.com/imbs-hl/ranger/files/3779661/ranger.txt)

**Comment by mnwright** [comment]
The BETA splitting rule only works for outcome data on the (0,1) unit interval*. We added a check for that in the R version, but not the C++ version. I just fixed that in #450. 

With (0,1) data, the BETA splitrule is still quite slow compared to the other ones but it shouldn't compute forever. 

* Actually, we also accept values in the closed interval [0,1] and add/subtract `std::numeric_limits<double>::epsilon()` if necessary. 
Also check our preprint for details on the method: https://arxiv.org/pdf/1901.06211.pdf.
