### ISSUE TITLE
Inconsistent splitvarID by treeInfo

### ISSUE THREAD

**Issue by nalzok** [imbs-hl/ranger#455]
When you feed a formula to `ranger`, the `splitvarID` column returned by `treeInfo` is 1-indexed.

```
> set.seed(42L)
> iris.ranger <- ranger(Species ~ ., iris)
> head(treeInfo(iris.ranger, tree=1), n=3)
  nodeID leftChild rightChild splitvarID splitvarName splitval terminal prediction
1      0         1          2          4  Petal.Width      0.7    FALSE       <NA>
2      1        NA         NA         NA         <NA>       NA     TRUE     setosa
3      2         3          4          1 Sepal.Length      7.1    FALSE       <NA>
```

However, if you specify a `dependent.variable.name` instead, then `splitvarID` will become 0-indexed.

```
> set.seed(42L)
> iris.ranger <- ranger(data=cbind(iris[, -5], y=iris[, 5]), dependent.variable.name='y')
> head(treeInfo(iris.ranger, tree=1), n=3)
  nodeID leftChild rightChild splitvarID splitvarName splitval terminal prediction
1      0         1          2          3  Petal.Width      0.7    FALSE       <NA>
2      1        NA         NA         NA         <NA>       NA     TRUE     setosa
3      2         3          4          0 Sepal.Length      7.1    FALSE       <NA>
```

According to the document, `splitvarID` should be 0-indexed:

> Node and variable ID's are 0-indexed, i.e., node 0 is the root node.

**Comment by mnwright** [comment]
Since version 0.11.5 (not on CRAN yet) it should always be 0-indexed. 

However, if you read the docs carefully it says 
> If the formula interface is used in the ranger call, the variable ID's are usually different to the original data used to grow the tree. Refer to the variable name instead to be sure.

That is exactly what happened in the previous versions: The outcome variable was put first by the formula interface, so it was still 0-indexed but variable 0 was the outcome.

**Comment by nalzok** [comment]
Ahh I see. Thanks for the response!

Just saying, I think it would be nice to have `splitvarID` being the index of the corresponding column in `data`. This is because "Refer to the variable name" suggests using `splitvarName` as indices. While dealing with high dimensional data, however, subscripting with integers is much more efficient than with character indices:

```
> library(microbenchmark)
> training <- as.data.frame(matrix(rnorm(5000000), c(100, 50000)))
> index.int <- sample.int(n=50000, size=100, replace=TRUE)
> index.string <- names(training)[index.int]
> microbenchmark(training[, index.int], training[, index.string])
Unit: microseconds
                     expr      min        lq       mean    median       uq      max neval
    training[, index.int]   43.982   50.5155   61.35934   60.2335   70.271  152.621   100
 training[, index.string] 1570.780 1841.6010 1985.99311 1889.0320 2017.344 5038.279   100
```

It is true that we can do `result$splitvarID <- match(result$splitvarName, names(data))`, and then use `splitvarID` as indices, but I fear many people are unaware of the performance issue. Wouldn't it be great if things are simply performant by default?

**Comment by mnwright** [comment]
I agree. The problem is that `treeInfo()` does not know exactly how `ranger()` was called (or it is very difficult to parse). It's easy for `ranger(data = ..., dependent.variable.name = ...)` and a formula with `~ .`, but can get complicated for other formulas.
