### ISSUE TITLE
Error using max.depth and oob.errors arguments

### ISSUE THREAD

**Issue by goleng** [imbs-hl/ranger#458]
Hi, 

I don't know why I kept getting this error message when I tried to set values to the arguments **max.depth** and **oob.error** in the ranger function. 
```
Error in ranger::ranger(y ~ ., data = d, num.trees = 105, mtry = 10,  : 
  unused arguments (max.depth = 4, oob.error = FALSE)
```

Please, any clue as to why is appreciated!

**Comment by mnwright** [comment]
That sounds like you have an old version. Which version is installed?
