### ISSUE TITLE
predict with version  < 0.11.5

### ISSUE THREAD

**Issue by brunaw** [imbs-hl/ranger#468]
Hey Marvin, 

I have a few old `ranger` objects saved, for which I would like to obtain the predictions in new data, but at this point, I get the 

```
Error: Invalid forest object. Is the forest grown in ranger version <0.11.5? Try to predict with the same version the forest was grown.
```

message. I see that there have been a few changes since I've run those models, so is there a hacky/easy way to predict with this version of the package without having to install it from CRAN (which has now an earlier version)?  

If this option exists, would you recommend using it or just updating my model objects to the newest version (running it all again)?

**Comment by mnwright** [comment]
I wouldn't recommend any hacks in this case. We made quite some changes when switching to x/y interface internally and all `splitvarIDs` etc. changed.

**Comment by brunaw** [comment]
That makes sense. `ranger` is so fast that it wasn't so much trouble to run it all again anyway. Thanks Marvin!

**Comment by mnwright** [comment]
To prevent failing reverse dependencies, I found a simple solution, see #474. 

With the current Github version you should be able to predict with the old models (with a warning). It might be a little slow for very big forests but should work.
