### ISSUE TITLE
Install error in utility.h

### ISSUE THREAD

**Issue by myloginid** [imbs-hl/ranger#47]
hi.. Install error as below in utility.h.. Any suggestions?

Environment - Red Hat Enterprise Linux Server release 6.5 (Santiago)
R --version
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

sudo R CMD INSTALL ranger_0.3.0.tar.gz
* installing to library ‘/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library’
* installing *source* package ‘ranger’ ...
** package ‘ranger’ successfully unpacked and MD5 sums checked
** libs
g++ -std=c++0x -I/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/include -DNDEBUG -DR_BUILD -I/usr/local/include -I"/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/Rcpp/include"   -fpic  -g -O2 -c Data.cpp -o Data.o
In file included from Data.cpp:36:
utility.h: In function ‘void saveVector2D(std::vector<std::vector<T, std::allocator<_CharT> >, std::allocator<std::vector<T, std::allocator<_CharT> > > >&, std::ofstream&)’:
utility.h:111: error: expected initializer before ‘:’ token
Data.cpp:216: error: expected primary-expression at end of input
Data.cpp:216: error: expected ‘;’ at end of input
Data.cpp:216: error: expected primary-expression at end of input
Data.cpp:216: error: expected ‘)’ at end of input
Data.cpp:216: error: expected statement at end of input
Data.cpp:216: error: expected ‘}’ at end of input
make: *** [Data.o] Error 1
ERROR: compilation failed for package ‘ranger’
* removing ‘/usr/lib64/RRO-8.0.2/R-3.1.2/lib64/R/library/ranger’

Thanks,
Manish

**Comment by mnwright** [comment]
Looks like your gcc version is too old to support C++11. You probably have to upgrade to 4.7 or newer. See also #7.
