### ISSUE TITLE
Speed improvement of the quantile regression

### ISSUE THREAD

**Issue by dplecko** [imbs-hl/ranger#473]
Hi,

@lorismichel and I have tried working out a speed improvement for the quantile regression step in `ranger` (`quantreg == TRUE, keep.inbag == TRUE`). In particular, I am attaching two things:

1) The file [ranger.R.zip](https://github.com/imbs-hl/ranger/files/3980512/ranger.R.zip) that cotains an adaptation of the original `ranger.R`. It allows you to use our code and also the original code (aware that this is not standard practice, but might be easiest if you want to try it out yourself). We have added an extra argument `oob.code` to `ranger()` which is a logical. `oob.code == TRUE` uses our code and FALSE uses the currently available code in `ranger`. 

2) A benchmarking summary [quantreg.pdf](https://github.com/imbs-hl/ranger/files/3980651/quantreg.pdf) that compares the two options. You will notice the speed gain is already visible. We also compare the estimated quantiles with the true theoretical quantiles to show that our approach is equally good. You will note that our (current) approach drops some trees for the oob prediction (the difference is not at all large in the examples), but this is in no way inherent to our approach. In fact, in C++, the cost of adapting the current version to lose no trees would probably be negligible.

We believe that a sizeable speed gain could be obtained from this. We are both more than happy to discuss and help out. Please let us know what you think.

Best,
Drago

**Comment by mnwright** [comment]
Thanks. This is related to #459. 

If I understand correctly, the difference in your version is that, when selecting a random observation in the same terminal node, you first allow this to be the observation itself and later remove these by setting them to NA. Correct?

**Comment by mnwright** [comment]
See #475 for a solution in C++ (using all trees as in the original approach).

**Comment by mnwright** [comment]
Merged the C++ version in #475.
