### ISSUE TITLE
How to get leaf indices that each sample was assigned to in the forest

### ISSUE THREAD

**Issue by moldach** [imbs-hl/ranger#476]
In Python's `scikit-learn` the `ExtraTreesClassifier` function returns a numpy array which contains the leaf indices that each sample was assigned to in the forest.

I'm trying to get similar information from `ranger` package.

I've documented the problem extensively [in this StackOverflow post](https://stackoverflow.com/questions/59360387/extracting-leaf-indices-that-each-sample-was-assigned-to-in-the-forest-from-rand).

In the post I was able to get this information from the `randomForest` package, but due to speed/accuracy would prefer to use the `ranger` package.

Is it possible to get this information from your package and if not could it be a feature request?

**Comment by mnwright** [comment]
Try `predict(..., type = "terminalNodes")`.
