### ISSUE TITLE
Classification with imbalance dataset

### ISSUE THREAD

**Issue by loetters** [imbs-hl/ranger#480]
Hi,

I have a question concerning using Ranger for imbalanced datasets. In my case the classes are distributed 99% False to 1 % True.  I use the R implementation of Ranger in the current version. I studied the cran description but I'm still not sure, if ranger does an automatic subsampling to create equally weighted classes.

The RandomForest implementation has an easy to use parameter called sampsize, so that for every tree to grow a fixed number of samples are drawn from each class. Is their something equivalent in ranger ?

Thank you 
Regards Lukas

**Comment by mnwright** [comment]
Yes, try `sample.fraction` with a vector argument, e.g. 
````R
ranger(y ~ ., dat, sample.fraction = c(0.5, 0.5), keep.inbag = TRUE)
````
to sample `nrow(dat)/2` observations of each class.

**Comment by loetters** [comment]
Hey,

thanks for this little hint. I think it worked.

Lukas

**Comment by talegari** [comment]
When I was exploring `sample.fraction`, I found that running the following code crashes R session:

```
library("tidyverse")
library("modeldata")
data("attrition", package = "modeldata")
attrition = as_tibble(attrition)
glimpse(attrition)

m = ranger::ranger(Attrition ~ .
                   , data = attrition
                   , sample.fraction = c(0.3, 0.1)
                   , keep.inbag = T
                   , replace = FALSE
                   )

**Comment by mnwright** [comment]
Thanks, there was a bug mixing up the order of `sample.fraction` and the factor levels, causing the crash. Should be fixed in #484. 

`sample.fraction` doesn't have to sum to 1. It will sample `nrow(data) * sample.fraction[i]` observation, so e.g. use the same number for each class to balance.

**Comment by loetters** [comment]
I think i diddn't get it.

Let's say we have a dataset with 900 False and 100 True.

How big will the sample be for the following sample.fractions

1) sample.fractions = c(0.5,0.5)
2) sample.fractions = c(0.1,0.9)
3) sample.fractions = c(0.2,0.4)

Thx Lukas

**Comment by mnwright** [comment]
The `sample.fraction` is always applied to the total sample size (same as for non-vector argument). In your examples: 

1. `sample.fraction = c(0.5, 0.5)`: 500 FALSE, 500 TRUE
2. `sample.fraction = c(0.1, 0.9)`: 100 FALSE, 900 TRUE
3. `sample.fraction = c(0.2, 0.4)`: 200 FALSE, 400 TRUE

All of these work only with replacement because you upsample the minority class. 

To check yourself:

````R
library(ranger)

p <- 4
x <- replicate(p, rnorm(1000))
y <- sample(c(rep(0, 900), rep(1, 100)))
dat <- data.frame(y = factor(y), x)

rf <- ranger(y ~ ., dat, num.trees = 5, 
             sample.fraction = c(0.5, 0.5), 
             replace = TRUE, keep.inbag = TRUE)
inbag <- do.call(cbind, rf$inbag.counts)
colSums(inbag[y == "0", ])
colSums(inbag[y == "1", ])
````
