### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by gaetan-dion** [imbs-hl/ranger#487]
Hi,

We currently use ranger for different cases, and now we need to deploy it in production.
So I would like to know if a release version is planed?
Because in your tags I only see pre-releases versions, and the CRAN is in 0.12 version (https://cran.r-project.org/web/packages/ranger/index.html)
Release version would anounce stability officialy.

**Comment by mnwright** [comment]
The releases on Github are not well maintained and are mostly Windows binaries. 

We don't have an official release but CRAN versions are well tested and should be quite stable.

**Comment by gaetan-dion** [comment]
The thing is in development, when you publish a package somewhere, you need to put a tag on github, thanks to that I can link commit/source to a version published.
When I look on CRAN repo, I see 0.12 version, but I'm unable to link this one to a github version.
According to the dates, your 0.12 cran version seems to be this commit : https://github.com/imbs-hl/ranger/commit/dfa696fe82572ccef8c68d2762bbe2d88aa87b6c

So is it possible to put a tag before publishing on cran repo?

More generally it's a open source problem, because we track CVSS vulnerability on github, but if someone crack your cran account and publish a bad source, we can't check it. Because source and publishing are not directly linked.

**Comment by mnwright** [comment]
I agree that it's a good idea to tag the CRAN versions. You found the correct commit and I just tagged it.

**Comment by gaetan-dion** [comment]
Thank you it's perfect, you can keep going this practice.
