### ISSUE TITLE
Permutations and Probability-Forests

### ISSUE THREAD

**Issue by mayer79** [imbs-hl/ranger#488]
Hello Marvin

One question on permutation importance with probability-forests. Is the performance drop calculated using Brier-Score (like the OOB-prediction error) or is it based on changes in some other measure?

**Comment by mnwright** [comment]
The permutation importance is measures in the same way as the OOB prediction error, which for probability forests is the Brier score.

**Comment by mayer79** [comment]
I see, thanks.
