### ISSUE TITLE
Warning: Paralellization deactivated (regularization used).

### ISSUE THREAD

**Issue by frehbein** [imbs-hl/ranger#491]
Hi Marvin,

since pulling the most recent version of ranger I get the following message:

`Warning: Paralellization deactivated (regularization used).`

It only runs on a single core (Number of threads:1), previously it ran on all 4 cores of my CPU.
I execute ranger from shell using

`./ranger --file input_file.csv --depvarname Energy --treetype 3 --verbose  --impmeasure 1 --outprefix ranger --write`

Even adding the `--nthreads` option does not seem to change anything.
As I am quite unexperienced with ranger, I hope that you may have an idea of what is going wrong (either some kind of bug or a mistake on my side).

Regards, Florian

**Comment by mnwright** [comment]
Fixed, **that** was a stupid bug. Thanks for reporting.

**Comment by frehbein** [comment]
Thank you!
