### ISSUE TITLE
predict.ranger: Forest was grown with 'impurity_corrected' variable importance. 

### ISSUE THREAD

**Issue by RJ333** [imbs-hl/ranger#494]
Hey ranger team,

thanks for developing this awesome package. I'm currently writing my own package to feed microbiome data from the phyloseq package to ranger.  In my code I use the `impurity_corrected` method as recommended to generate a model on my train set. However, when I want to predict my test set I will receive this warning: `In predict.ranger(object = RF_train, data = test_set) :
  Forest was grown with 'impurity_corrected' variable importance. For prediction it is advised to grow another forest without this importance setting.`

Could someone explain in more detail to me what this means and how I should react?

I'm sorry if this is already described somewhere else, I looked in many places and also went through the issue tracker here...

**Comment by mnwright** [comment]
The `impurity_corrected` importance splits on non-informative (permuted) features to correct the bias of the `impurity` importance. Thus, the prediction performance might be slightly worse than without the `impurity_corrected` importance. For details, see our paper: [https://doi.org/10.1093/bioinformatics/bty373](https://doi.org/10.1093/bioinformatics/bty373) (open access). 

My recommendation is: 
- If interested only in prediction, don't use `importance = "impurity_corrected"`
- If interested only in variable importance, use `importance = "impurity_corrected"`
- If interest in both prediction and variable importance, grow two forests, one with `importance = "impurity_corrected"`, one without

**Comment by RJ333** [comment]
Perfect, exactly what I needed to know. Thank you!
