### ISSUE TITLE
Easier way to get the observations used to form the prediction

### ISSUE THREAD

**Issue by shangzhi-hong** [imbs-hl/ranger#497]
Is there an easy way to get the observations to a certain prediction?
For example, a prediction for a certain observation of a single tree is the average of values c(1, 2, 3, 4, 5), how to get such vector for a single tree?
Thank you.

**Comment by mnwright** [comment]
Currently, we don't save these values but just the average.

**Comment by sheffe** [comment]
@shangzhi-hong this is demonstrated in the `forestError` package [starting here](https://github.com/benjilu/forestError/blob/dde64a6fff949281f945bd32c74062c9e37c3bc5/R/quantforesterror.R#L186). The basic strategy is to find the terminal nodes for all train predictions, then the terminal nodes for predictions where you want a new observation's vector of values, and join them. This results in some quite large joins, so be careful with memory issues if you have huge forests or lots of observations. (Another note here -- it requires that you train the forest with `keep.inbag = TRUE` if you want to make sure the vector of values is oob only.)

**Comment by shangzhi-hong** [comment]
Thanks for the answers, @mnwright and @sheffe. 

As John pointed out, the implementation in `forestError` can have memory issues and it needs additional despondencies on other R packages.

So I wrote my function for this problem based on matrices, and it can be found [here](https://github.com/shangzhi-hong/RfEmpImp/blob/master/R/query.rf.pred.idx.R#L40).

I'm closing this issue.
