### ISSUE TITLE
Testsuite fails on some architectures (arm64, ppc64el and s390x)

### ISSUE THREAD

**Issue by daissi** [imbs-hl/ranger#498]
Hi,
The testsuite fails on some architectures (at least on arm64, ppc64el and s390x) as you can see on the original Debian [bug report](https://bugs.debian.org/949361).

```
> test_check("ranger")
── 1. Failure: maxstat corrected impurity importance is positive (on average) (@
mean(rf$variable.importance) is not strictly more than 0. Difference: NaN

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 647 | SKIPPED: 10 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: maxstat corrected impurity importance is positive (on average) (@test_maxstat.R#41) 
```

Best,
Dylan

**Comment by tillea** [comment]
Do you need any more information to track this down?

**Comment by mnwright** [comment]
Any suggestion on how to debug on these platforms? I tried with Travis in #505 but I cannot get it to work.

**Comment by tillea** [comment]
On Mon, May 04, 2020 at 03:41:19AM -0700, Marvin N. Wright wrote:
> Any suggestion on how to debug on these platforms? I tried with Travis in #505 but I cannot get it to work. 
I guess arm64 works with qemu.  If you have real trouble to setup this I might try my pinebook - but not in this week where I'm basically on vac.
Kind regards, Andreas.

**Comment by daissi** [comment]
I had private discussion with Jeroen about the support of Travis for non-amd64 arches. No work in this direction is planned as the R community is moving away from Travis in favor to GitHub Actions. Maybe in some future, we will be able to enable GH for non-amd64 arches.

Back to our issue, the regression is due to the increase of num.trees there:

https://github.com/imbs-hl/ranger/blob/5151df0bc10531cceaa278fccf7b6ab9324e5103/tests/testthat/test_maxstat.R#L39

It works fine up to num.trees=20, it starts to fail with 21, at least on an ARM64 Debian porterbox.

**Comment by mnwright** [comment]
Update: I'm able to reproduce with Docker and `docker buildx build --platform linux/arm64 `. Will try to fix it soon.

**Comment by tillea** [comment]
On Thu, May 07, 2020 at 12:46:51PM -0700, Marvin N. Wright wrote:
> Update: I'm able to reproduce with Docker and `docker buildx build --platform linux/arm64 `. Will try to fix it soon. 
Thanks a lot, Andreas.

**Comment by mnwright** [comment]
Fixed.
