### ISSUE TITLE
It's that possible to export a cpp-version with only license MIT?

### ISSUE THREAD

**Issue by WangHaomao** [imbs-hl/ranger#503]
Hi mnwright, I would like to use ranger cpp-version under license MIT, but the R-package licensed with GUN, which is trouble for some reasons.
It's that possible to export an individual branch(a repository will be better) with only cpp-version license MIT? Thanks.

best,
haomao

**Comment by mnwright** [comment]
Why not just copy the `cpp_version` directory or fork the repository and remove the GPL files?

**Comment by WangHaomao** [comment]
> Why not just copy the `cpp_version` directory or fork the repository and remove the GPL files?

Thanks for your permission.
