### ISSUE TITLE
Hiding variable importance warning in predict.ranger

### ISSUE THREAD

**Issue by jonathanishhorowicz** [imbs-hl/ranger#511]
Is is possible to hide the warning `"Forest was grown with 'impurity_corrected' variable importance. For prediction it is advised to grow another forest without this importance setting."` when using `predict.ranger`? I am in a situation where I need both variable importance and prediction.

Thank you in advance!

**Comment by mnwright** [comment]
What exactly do you mean by hide? You can always hide warnings with `suppressWarnings()` but my suggestion would be to grow a second forest without `importance = "impurity_corrected"` and use that for prediction.

**Comment by jonathanishhorowicz** [comment]
I am using ranger for recursive feature elimination with `caret::rfe`, so at each iteration of the feature selection algorithm I build a tree, evaluate feature importance (to decide which features to retain) and evaluate its performance on held-out data.

I would prefer not to suppress all warnings (for obvious reasons) but growing a second tree seems a bit cumbersome.

**Comment by mnwright** [comment]
My suggestion is still to treat the warning as an error and grow an additional forest. However, I think there are ways to suppress specific warnings in R.
