### ISSUE TITLE
Can I change the licence to MIT and release after removing all GPL files in my fork-repository

### ISSUE THREAD

**Issue by WangHaomao** [imbs-hl/ranger#512]
Hi @mnwright, Can I change the licence to MIT and release after removing all GPL files in my [fork- repository](https://github.com/WangHaomao/ranger).

Sorry to bother, I am a freshman to Github and I would like to know whether it's authorized, thanks.

best,
haomao

**Comment by mnwright** [comment]
I guess so but I'm also no license expert. I just created a release with only the MIT licensed files: https://github.com/imbs-hl/ranger/releases/tag/0.12.3_mit_only

Does that help?

**Comment by WangHaomao** [comment]
> I guess so but I'm also no license expert. I just created a release with only the MIT licensed files: https://github.com/imbs-hl/ranger/releases/tag/0.12.3_mit_only
> 
> Does that help?

This helps a lot, thanks!
