### ISSUE TITLE
Correct use of `inbag` argument

### ISSUE THREAD

**Issue by brfitzpatrick** [imbs-hl/ranger#515]
Hello, have I understood how to use the `inbag` argument correctly?

 1. each element in the list supplied to `inbag` determines the observations that are used to fit one of the trees in the random forest

 2. each element of this list should be a vector of integers of length equal to the number of observations in the data supplied to ranger

 3. the i'th element of j'th such vector sets the number of times the observation from the i'th row of the data is present in the sample of data used to fit the j'th tree in the random forest

**Comment by mnwright** [comment]
Yes, exactly.

**Comment by brfitzpatrick** [comment]
Thank you.
