### ISSUE TITLE
Understanding inbag argument -- issues with predictions

### ISSUE THREAD

**Issue by bzki** [imbs-hl/ranger#517]
I understand a recent clarifying note was posted about `inbag`: see [Issue](https://github.com/imbs-hl/ranger/issues/515). 

I'm having trouble understanding why the predictions from the two following fits should be different. I tried to make the example simple and reproducible. In one fit, I use the inbag argument to specify counts of the observations in question -- I am sampling half of the original data frame, and using each of those points twice. In the second fit, I manually create a data.frame that is equivalent to the first in that I have a data frame consisting of the sample points (twice), and I set the `inbag` argument so that every count is 1. I set `mtry` equal to the total number of independent variables. I run a single tree in each case with the same seed -- the point of all this is that I would expect them to produce the exact same predictions, and there should be no variability. 

I may be making a very simple conceptual or programming error. Thanks for the great work on this package. 

```r
library(ranger)
set.seed(1212)
n = 500
x1 <- rnorm(n)
x2 <- rnorm(n)
y <- x1 + x2 + rnorm(n)
df_full <- data.frame(x1 = x1, x2 = x2, y = y)
set.seed(1212)
sample_index <- sample.int(n = nrow(df_full), size = n/2, replace = FALSE)
# Sample each of these points twice
inbag_index <- rep(sample_index, 2)
inbag_count <- rep(NA, nrow(df_full))
for (i in seq(length(inbag_count))) {
  inbag_count[i] <- sum(inbag_index == i)
}
df_inbag <- df_full[inbag_index, ]

rfit1 <- ranger(y ~ x1 + x2, data = df_full, mtry = 2, 
                num.trees = 1, 
                inbag = list(inbag_count), keep.inbag = T, 
                seed = 1)

rfit2 <- ranger(y ~ x1 + x2, data = df_inbag, mtry = 2, 
                num.trees = 1, 
                inbag = list(rep(1, nrow(df_inbag))), keep.inbag = T,
                seed = 1)

rpred1 <- predict(rfit1, df_full)$predictions
rpred2 <- predict(rfit2, df_full)$predictions

testthat::expect_equal(rpred1, rpred2)
# Exactly 6/500 observations produce different predictions
```

**Comment by mnwright** [comment]
That's because two different splits resulting in the exact same splitting criterion but evaluated in a different order. Try `df_inbag <- df_full[sort(inbag_index), ]` and you see the same results

If you want to know all the details: We select a splitting algorithm (here: https://github.com/imbs-hl/ranger/blob/c70d5d4d7de25b7d9d341e1532e3cd6cb6d5cdeb/src/TreeRegression.cpp#L155) based on the number of samples and the number of unique values in the dataset. In your first example you have 500 unique values in the variables but throw away 250 by fixing `inbag`. However, the splitting algorithm is chosen based on the 500 in the full dataset (which are only 250 from the start in the second example). 
Is should be possible to fix this somehow...

**Comment by bzki** [comment]
Can I break this down to see if I am understanding this correctly? `df_inbag <- df_full[sort(inbag_index), ]` gets the exact same predictions as our first fit, but `df_inbag <- df_full[inbag_index, ]` does not for the following reason. Of the 500 unique values in the original data, there are several unique split values that are optimal for splitting based on the 250 training observations (e.g. the full data may contain unique values 0.1 and 0.101 but we only actually observe 0.1 in our desired training data). Because there are splits that are equally good, we pick different splits just based on the ordering of the data -- that's why `df_inbag <- df_full[sort(inbag_index), ]` gets the same splits as the first fit, but `df_inbag <- df_full[inbag_index, ]` does not.  

If we make predictions on the training dataset, these predictions will always be equal across the two fits, but out-of-sample, our predictions could be slightly different depending on the ordering of the data. 

```r
# These should always be equal
rtrain1 <- predict(rfit1, df_inbag)$predictions
rtrain2 <- predict(rfit2, df_inbag)$predictions
testthat::expect_equal(rtrain1, rtrain2)
# Passes
```

Is my understanding correct? I have some trouble parsing C++ admittedly, though I would like to go through and better understand the source code.

Thank you for your quick response.

**Comment by mnwright** [comment]
Your are right, that didn't make sense. It's a numerical problem: We sum up the outcome variable of all observations in a node, here: https://github.com/imbs-hl/ranger/blob/c70d5d4d7de25b7d9d341e1532e3cd6cb6d5cdeb/src/TreeRegression.cpp#L139
 and if the data is in a different order the sum is slightly different (about 1e-16). 
Any suggestions?

**Comment by bzki** [comment]
I see! I *think* that explanation is consistent with my observation that if I just use `y` and `x1` and set `mtry = 1`, all 3 fits produce the same predictions. When I add in `x2` and set `mtry = 2` as in my code above, that's when we get different predictions for some portion of the non-training sample -- we now have more than 1 feature to choose from for each split, so the 1e-16 difference can push us to pick a different feature -- does that make sense to you? 

I will think this over for suggestions to handle this numerically, though I'm not sure I have any ideas -- it's quite possible no change is needed, and in any event I would defer to your expertise in handling this. My main concern was that `inbag` was not producing the correct training data that I wanted. Based on our discussion, it seems that's not the case, and the training data is what we want intended (a relief). Thanks again.

**Comment by bzki** [comment]
I was just thinking of a couple of things to research and look into in order to gather more information (I can do this as time permits, but I will be very slow):

- Do other Random Forest implementations produce slightly different fits based on reordering of data? If not, how are they calculating MSE to determine the split for each node? How much more expensive is the computation? 
- Are there reasonable numerical methods for getting more precise sums? For example, the [Kahan Summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm). Would this be worth the computational cost and added complexity?

**Comment by bzki** [comment]
Just for reference, here is the same issue occurring in `randomForest`. Re-ordering a data.frame can result in slightly different predictions for a subset, despite all other parameters set so that in theory, there should be no variability in the results. 

I cannot precisely tell the package to not resample at all, so I set `replace = FALSE` and `sampsize = nrow(df_inbag)`, but the data will still be re-sorted.

```r
library(randomForest)
set.seed(1)
rf_fit2 <- randomForest(y ~ x1 + x2, data = df_inbag, 
                        mtry = 2, ntree = 1, keep.inbag = T,
                        replace = FALSE, sampsize = nrow(df_inbag))
set.seed(1)
rf_fit3 <- randomForest(y ~ x1 + x2, data = df_inbag2, 
                        mtry = 2, ntree = 1, keep.inbag = T,
                        replace = FALSE, sampsize = nrow(df_inbag2))
rf_pred2 <- predict(rf_fit2, df_full)
rf_pred3 <- predict(rf_fit3, df_full)
rf_train2 <- predict(rf_fit2, df_inbag)
rf_train3 <- predict(rf_fit3, df_inbag)
testthat::expect_equal(rf_train2, rf_train3) # Passes
testthat::expect_equal(rf_pred2, rf_pred3) # 9 mismatches

# Try with just x1 and mtry = 1
set.seed(1)
rf_fit2b <- randomForest(y ~ x1, data = df_inbag, 
                        mtry = 1, ntree = 1, keep.inbag = T,
                        replace = FALSE, sampsize = nrow(df_inbag))
set.seed(1)
rf_fit3b <- randomForest(y ~ x1, data = df_inbag2, 
                        mtry = 1, ntree = 1, keep.inbag = T,
                        replace = FALSE, sampsize = nrow(df_inbag2))
rf_pred2b <- predict(rf_fit2b, df_full)
rf_pred3b <- predict(rf_fit3b, df_full)
rf_train2b <- predict(rf_fit2b, df_inbag)
rf_train3b <- predict(rf_fit3b, df_inbag)
testthat::expect_equal(rf_train2b, rf_train3b) # Pass
testthat::expect_equal(rf_pred2b, rf_pred3b) # Pass
```

I don't think any further action is needed.

**Comment by mnwright** [comment]
Cool, thanks for your analysis!
