### ISSUE TITLE
betaLogLik in ranger/src/utility.cpp has a data race

### ISSUE THREAD

**Issue by michaelquinn32** [imbs-hl/ranger#518]
A Google-internal thread-sanitizer (https://github.com/google/sanitizers/wiki#threadsanitizer) has found a data race in the betaLogLik function. Here's a partial traceback of the failure.

```
    #8 ranger::Forest::grow() ranger/src/Forest.cpp:516:13 (ranger.so)
    #9 ranger::Forest::run(bool, bool) ranger/src/Forest.cpp:295:5 (ranger.so)
    #10 rangerCpp(unsigned int, Rcpp::Matrix<14, Rcpp::PreserveStorage>&, Rcpp::Matrix<14, Rcpp::PreserveStorage>&, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >, unsigned int, unsigned int, bool, unsigned int, unsigned int, bool, unsigned int, unsigned int, std::__tsan::vector<std::__tsan::vector<double, std::__tsan::allocator<double> >, std::__tsan::allocator<std::__tsan::vector<double, std::__tsan::allocator<double> > > >&, bool, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >&, bool, bool, Rcpp::Vector<19, Rcpp::PreserveStorage>, Rcpp::Matrix<24, Rcpp::PreserveStorage>, bool, bool, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >&, bool, bool, unsigned int, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, double, double, bool, unsigned int, unsigned int, Eigen::SparseMatrix<double, 0, int>&, bool, bool, bool, unsigned int, std::__tsan::vector<std::__tsan::vector<unsigned long, std::__tsan::allocator<unsigned long> >, std::__tsan::allocator<std::__tsan::vector<unsigned long, std::__tsan::allocator<unsigned long> > > >&, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, bool) ranger/ranger/src/rangerCpp.cpp:197:13 (ranger.so)
```

Unfortunately, this isn't an especially easy error to reproduce, as you need to rebuild R with thread sanitizer support. Some hints are here: https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual

I'm also having trouble digging through your code to find a solution. TBH, C++ is a bit outside of my wheelhouse. But I could pass along other pointers if that helps.

Best wishes,
Michael

**Comment by mnwright** [comment]
Hm... Which ranger version is this? Could you post the R code causing the data race?

**Comment by michaelquinn32** [comment]
It's in the most recent version of the package. The error appeared while running the unit tests.

Sorry, but I see the traceback from the cpp side, not the R side. The best I can say is it happened during a call of `_ranger_rangerCpp`

```
    #9 ranger::Forest::run(bool, bool) third_party/R/packages/ranger/ranger/src/Forest.cpp:295:5 (ranger.so+0x44748)
    #10 rangerCpp(unsigned int, Rcpp::Matrix<14, Rcpp::PreserveStorage>&, Rcpp::Matrix<14, Rcpp::PreserveStorage>&, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >, unsigned int, unsigned int, bool, unsigned int, unsigned int, bool, unsigned int, unsigned int, std::__tsan::vector<std::__tsan::vector<double, std::__tsan::allocator<double> >, std::__tsan::allocator<std::__tsan::vector<double, std::__tsan::allocator<double> > > >&, bool, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >&, bool, bool, Rcpp::Vector<19, Rcpp::PreserveStorage>, Rcpp::Matrix<24, Rcpp::PreserveStorage>, bool, bool, std::__tsan::vector<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> >, std::__tsan::allocator<std::__tsan::basic_string<char, std::__tsan::char_traits<char>, std::__tsan::allocator<char> > > >&, bool, bool, unsigned int, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, double, double, bool, unsigned int, unsigned int, Eigen::SparseMatrix<double, 0, int>&, bool, bool, bool, unsigned int, std::__tsan::vector<std::__tsan::vector<unsigned long, std::__tsan::allocator<unsigned long> >, std::__tsan::allocator<std::__tsan::vector<unsigned long, std::__tsan::allocator<unsigned long> > > >&, bool, std::__tsan::vector<double, std::__tsan::allocator<double> >&, bool, bool) ranger/src/rangerCpp.cpp:197:13 (ranger.so+0x9ee84)
    #11 _ranger_rangerCpp ranger/src/RcppExports.cpp:62:34 (ranger.so+0x68a9d)
```

**Comment by mnwright** [comment]
> It's in the most recent version of the package.

From CRAN or Github?

**Comment by michaelquinn32** [comment]
From CRAN. Sorry.

**Comment by mnwright** [comment]
This is indeed hard to reproduce. Does anyone know a docker container with R built with ThreadSanitizer?

**Comment by michaelquinn32** [comment]
Not sure. Dirk Eddelbuettel @eddelbuettel has a docker recipe for an undefined behavior sanitizer:
https://hub.docker.com/r/rocker/r-devel-san/dockerfile

I don't use docker, TBH, but I think it would be worth a shot to replace instances of "-fsanitize=undefined" with "-fsanitize=thread" and see how far that gets you.
https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html

**Comment by eddelbuettel** [comment]
RHub has one instance labelled as 'Debian Linux, R-devel, GCC ASAN/UBSAN'.

(These can be finicky.  Just because one such detector found behavior in the code it doesn't mean this one does.  But it is quick first try -- it may work.  If you do need to instrument R accordingly...)

**Comment by mnwright** [comment]
> Not sure. Dirk Eddelbuettel @eddelbuettel has a docker recipe for an undefined behavior sanitizer:
> https://hub.docker.com/r/rocker/r-devel-san/dockerfile
> 
> I don't use docker, TBH, but I think it would be worth a shot to replace instances of "-fsanitize=undefined" with "-fsanitize=thread" and see how far that gets you.
> https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html

Thanks. I can reproduce the issue with this...

> RHub has one instance labelled as 'Debian Linux, R-devel, GCC ASAN/UBSAN'. See `rhub::platforms()` or at https://builder.r-hub.io/advanced.
> 
> (These can be finicky. Just because one such detector found behavior in the code it doesn't mean this one does. But it is quick first try -- it may work. If you do need to instrument R accordingly...)

... but not with this.

**Comment by mnwright** [comment]
The problem is that `std::lgamma()` is not thread safe, see here: https://en.cppreference.com/w/cpp/numeric/math/lgamma. 

Any suggestions?

**Comment by eddelbuettel** [comment]
Interesting.  Next line of that page, mabe?  

> Some implementations provide `lgamma_r`, which takes a pointer to user-provided storage for singgam as the second parameter, and is thread-safe.

My Linux manual page says 'since glibc 2.19' which seems to imply since 2014 or 2015. May even be good enough to be used without a `configure` test...  Assuming macOS has it too.

**Comment by mnwright** [comment]
Thanks, `lgamma_r` seems to be working on macOS (clang) and the r-devel-san (Debian, g++) container. What confuses me is that it is `std::lgamma_r` with clang and  `lgamma_r` (no std) with g++. Why is it in in the standard library in clang but not in g++?

**Comment by eddelbuettel** [comment]
Maybe because it's a C function with no sibbling in the `cmath` header?

**Comment by eddelbuettel** [comment]
Yup:

```sh
edd@rob:~$ grep lgamma_r /usr/include/c++/9/cmath 
edd@rob:~$ grep lgamma /usr/include/c++/9/cmath 
#undef lgamma
#undef lgammaf
#undef lgammal
  using ::lgamma;
  using ::lgammaf;
  using ::lgammal;
  lgamma(float __x)
  { return __builtin_lgammaf(__x); }
  lgamma(long double __x)
  { return __builtin_lgammal(__x); }
    lgamma(_Tp __x)
    { return
```

**Comment by mnwright** [comment]
OK. Is there a nice solution to catch both the one defined in global namespace and the one in std? In #521 I used a local `using namespace std;`...

**Comment by eddelbuettel** [comment]
Use a `#ifdef` test ?

**Comment by mnwright** [comment]
> Use a `#ifdef` test ?

Cannot check the function definition with preprocessor directives, so we'd have to check the compiler, right?

Btw... mingw doesn't have `lgamma_r` so we have to fall back to `lgamma`. However, we never use the sign of the gamma function (which causes the race), so we shouldn't have a problem.

**Comment by eddelbuettel** [comment]
Yes.  Existing directives can tell you whether you are being used by clang or g++.  

There are also autoconf (or cmake) tricks to test / confirm if you think you need to test more.  (I.e. a common "more rigorous" scheme is to actually compile short test function with configure; I am not sure you need that yet.)

Similarly for `mingw`.  If it doesn't have it ... well then use a mutex and non-parallel code.  Correctness comes first.
