### ISSUE TITLE
Add predictions of quantiles

### ISSUE THREAD

**Issue by clbieganek** [imbs-hl/ranger#52]
(Feature request.) It would be handy if **ranger** could predict conditional quantile functions, as in the **quantregForest** package:

https://cran.r-project.org/web/packages/quantregForest/index.html

**Comment by mnwright** [comment]
Check out Philipp's project: https://github.com/PhilippPro/quantregRanger

**Comment by clbieganek** [comment]
Great! Thanks!

**Comment by mnwright** [comment]
Now included in ranger, see #207.
