### ISSUE TITLE
depth-varying mtry

### ISSUE THREAD

**Issue by philippegc** [imbs-hl/ranger#520]
Hi,

I was wondering whether there would be way to get mtry to vary along the tree fitting process. For example, having a lower mtry for early splits and a higher one for splits that occur at higher depth (or the other way around). Many thanks.

Philippe

**Comment by mnwright** [comment]
I think it should be sufficient to make `mtry` dependent on `depth` in `Tree::createPossibleSplitVarSubset:` https://github.com/imbs-hl/ranger/blob/c70d5d4d7de25b7d9d341e1532e3cd6cb6d5cdeb/src/Tree.cpp#L268

`depth` is a member variable defined here: https://github.com/imbs-hl/ranger/blob/c70d5d4d7de25b7d9d341e1532e3cd6cb6d5cdeb/src/Tree.h#L228
