### ISSUE TITLE
Quantile Regression computes for long times without producing results.

### ISSUE THREAD

**Issue by Droelf-source** [imbs-hl/ranger#522]
Hello,

I try to do a quantile regression with ranger using ~60k observations and 17 predictor variables. I use the following command to start **ranger**:

```
quant_forest <- ranger(formula = form_miss, data = data_train,
                      num.trees = opt_pars[[i,2]],
                        min.node.size = opt_pars[[i,3]],
                        num.threads = 1, keep.inbag= TRUE,
                        quantreg = TRUE, oob.error = FALSE,
                        importance = "none", verbose = TRUE,
                        replace = FALSE)
```

In first tries computing time was very long and no results were produced even after 10+ hours. I used verbose=TRUE to see if there is any progress happening. After using the above command after some minutes the following message was generated

_Growing tress.. Progress: 60%. Estimated remaining time: 20 seconds._

Well that was 5 hours ago. I was asking myself if somehow I can check if ranger is stuck in calculation or why no results are produced. If I use **ranger** without quantreg calculation takes only some minutes. 

And on a side note if I use **quantregRanger** calculations are very fast and I get results but the predict function of **quantregRanger** doesn't work sadly.

**Comment by mnwright** [comment]
See https://github.com/imbs-hl/ranger/issues/207#issuecomment-643909527.

**Comment by Droelf-source** [comment]
Okay great thanks. 
So this version isn't on CRAN yet? Is it possible to download the master.zip and install from there? Using install_local on the whole .zip doesn't work.
Sadly I can't use direct github install as its corporate proxy and not sure if I can get access there.

**Comment by Droelf-source** [comment]
Ok I have cheated the system and got it to work.
Now quantreg is as fast as normal ranger.

Great work I really like your package. And thanks for the help.
