### ISSUE TITLE
subsampling trees in forest

### ISSUE THREAD

**Issue by ecoquant** [imbs-hl/ranger#524]
I'm exploring the possibility of sampling trees in the forest which ranger builds in order to get a handle on variability in predicted response.  I don't mind writing code myself, but do you know if there's a particular piece of source code which documents how the $forest object returned from ranger is formatted and structured?

My idea is to sample the number of trees randomly, pick some subset, then stuff back into a replica of the ranger object and do predictions. 

Is this completely out to lunch with the ranger implementation?

**Comment by mnwright** [comment]
For docs on the `$forest` object see [FAQ](https://github.com/imbs-hl/ranger/wiki/FAQ#how-are-trees-saved-in-ranger). 

If you just want to predict with subsets of trees, you can also use `predict.all = TRUE` in `predict()` and subset these predictions.

**Comment by ecoquant** [comment]
Thanks much. That should work.
