### ISSUE TITLE
Mysterious fault and error report from "predict"

### ISSUE THREAD

**Issue by ecoquant** [imbs-hl/ranger#525]
`Predicting.. Progress: 0%. Estimated remaining time: 4 days, 11 hours, 7 minutes, 58 seconds.
Error in eval(ei, envir) : argument "x" is missing, with no default
> traceback()
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("reproPredictError.R")
`
Below is a link to an archive with a minimally reproducible example. 

https://drive.google.com/file/d/1f8g7vXCebRN08sAtBa7ZHZXYLK4VxXcZ/view?usp=sharing

I placed a link because I need to create the state to assure reproducing the error and cannot do so without a training set that's pretty big. 

The .RData should be loaded and then _reproPredictError.R_ should be sourced. As configured, it contains a local and slightly modified version of _predict.ranger_ whereby I was hoping to get a fault out of the **R** code. Unfortunately, it looks like it is in the C++ code call.

Certainly willing to support further isolation. I will continue and try with a smaller number of trees.

**Comment by ecoquant** [comment]
Reduced number of trees to 3000 to see if error reproduces, and it does.  That's too small to solve what I'm trying to do, but figuring out this bug is critical. This could be my fault, misusing _ranger_ somehow.  It's just that the error message is so opaque and gives no location information that I don't know where to begin to look.

Zip archive with same as linked above attached.

[20200621MinimallyReproducibleSmaller.zip](https://github.com/imbs-hl/ranger/files/4810562/20200621MinimallyReproducibleSmaller.zip)

**Comment by mnwright** [comment]
That seems to be working here. Could you try to post a reproducible example? Do you use the same ranger version for model fitting and prediction?

**Comment by ecoquant** [comment]
*sigh*

Yes, only one package loaded.  Note this is on Windows, so I install the binary package. 

I don't know the version number so I installed 

Is there any win to be had for isolation by installing directly from Github?

**Comment by ecoquant** [comment]
Installed 0.12.3 from Github, build notes attached. 

Re-ran full 300,000 tree calculation on Windows. Same error. 


[20200622Ranger0p12p3InstallFromGithub.zip](https://github.com/imbs-hl/ranger/files/4814117/20200622Ranger0p12p3InstallFromGithub.zip)

**Comment by ecoquant** [comment]
On a hunch, I disabled all the loads of packages at the top of the script. These were not strictly necessary for the minimally reproducible case, but I left them in on the hunch that there might be an interaction between _ranger_ and another package. Instead of loading them, I altered the script to call out each individually, e.g., **zoo::rollmean(...)**. 

In fact, the **predict.all=TRUE** ran successfully in that case. 

I'm curious, were these removed in the test reported as successful above?

I am proceeding to make a series of runs in order to isolate which package may be the culprit.

**Comment by ecoquant** [comment]
So, apparently the package _pspline_ doesn't manage the export of its _predict.smooth.Pspline_ function properly, known externally as simply _predict_.  If I load that last using _library_, in a context which has all the other packages, including _ranger_, doing _pspline::predict(.)_ fails. 

While I have not tracked down what _pspline_ is doing, if I switch to _AdaptFitOS_ instead of _pspline_, _ranger_ works just fine. 

And that's all I wanted to accomplish.  

_That_ was a long one to find!
