### ISSUE TITLE
Error: Missing data in columns: .

### ISSUE THREAD

**Issue by tenFnAN** [imbs-hl/ranger#526]
The question is about ranger 0.12.1. What is the difference between calls:

1. 
 `ranger::ranger( formula = Sepal.Length~.,
                     data = iris ,
                     num.trees       = 5,
                     mtry            = 3,
                     min.node.size   = 3, 
                     sample.fraction = 0.7,
                     quantreg = T,  
                     replace = F, 
                     respect.unordered.factors = 'order', 
                     seed = 1234 )`
##result

> Error: Missing data in columns: .

2.
  `ranger::ranger( formula = Sepal.Length~.,
                     data = iris ,
                     num.trees       = 5,
                     mtry            = 3,
                     min.node.size   = 3, 
                     sample.fraction = 0.7,
                     quantreg = T,  
                     replace = F,  
                     seed = 1234 )`
 

> done

In the previous version of the package 0.11.2, the first call was correct. From what I've observed, when I change parameter quantreg to FALSE and set respect.unordered.factors = 'order', in the second call, it's ok, but why : )?

Iris is just benchmark, i tried this on definitely larger data

**Comment by mnwright** [comment]
This is already fixed in version 0.12.3 (on Github, not on CRAN yet). It seems to be about time for a new CRAN release...
