### ISSUE TITLE
Possible to do no predictions for train data?

### ISSUE THREAD

**Issue by Droelf-source** [imbs-hl/ranger#527]
Hello,

is it possible to call ranger (with quantreg) such that predictions on the training data isn't done? 
Thanks for help.

Best Regards.

**Comment by mnwright** [comment]
What do you mean exactly? No Out-of-bag predictions? Or do not prepare Out-of-bag quantreg predictions?

**Comment by Droelf-source** [comment]
Well, if you activate verbose in a ranger call it always goes like:
"Growing trees ... "
"Predicting..."
"Aggregating..."

And I don't really understand how the predicting is necessary if I don't want to estimate training errors. I just want the trees and predict for new data. So is it possible to do only the first step?

**Comment by mnwright** [comment]
With quantreg the prediction step is required to get the terminal node IDs. Out-of-bag predictions can be turned off with `oob.error = FALSE`.

**Comment by Droelf-source** [comment]
Ah okay. Thanks.
