### ISSUE TITLE
Feature "importance"

### ISSUE THREAD

**Issue by lnicola** [imbs-hl/ranger#528]
Sorry for using the issue tracking for a support question, but it might be useful for other users, too.

Is it possible to get a measure of how "important" each feature in a model is? That is, if my dataset has 500 features and 50 of them are either noise or highly correlated with others, can I determine which?

**Comment by Droelf-source** [comment]
There is the option "importance" in a ranger call which you can use to get a measure for this. Currently implemented with 4 options I think. This give you back which feature brings the greatest improvements in impurity when option is chosen with "impurity" or "impurity_corrected". You can't really tell about the correlation part though.

**Comment by lnicola** [comment]
Thanks, I misread the docs. The importance values are available as `variable.importance`.
