### ISSUE TITLE
Issue with x,y interface vs formula/data

### ISSUE THREAD

**Issue by vonGameTheory** [imbs-hl/ranger#530]
I use ranger constantly -- have been for a long time.  Recently using v0.12.1 with R, I started using x=data, y=target rather than the usual formula=target ~., data=data that I have always used up until now (I prefer x/y and I just noticed its existence -- is that a newer option? ) Anyway, today I was getting some random problems where the predictions would all come back as NaNs with some forests.  But if I remade the forest with the same data and the same seed, then it would work, so the problem seems truly random.  (If I set up a loop where it is making a forest and doing predictions though, it would always fail with a bad forest within 10-20 tries though.)  Went back to formula interface, and everything (seemingly) works fine everytime.  So kind of a vague bug report I know, but there seems to be something there...

**Comment by mnwright** [comment]
That's very strange. Any chance for a reproducible example? 

> I prefer x/y and I just noticed its existence -- is that a newer option?

Yes, we have it since version 0.11.5.

**Comment by vonGameTheory** [comment]
Yes, I will try to simplify and see if I can isolate an example that fails (or fails often anyway).  Slight suspicion it might have to do with allowing matrix data instead of data.frame and maybe it isn't actually the x/y thing (or only with both).  Have to isolate all the options.
