### ISSUE TITLE
variable importance p-value for the c++ version

### ISSUE THREAD

**Issue by renhuachung** [imbs-hl/ranger#531]
Hi, is there a similar function in the c++ version such as importance_pvalues() in the R version to calculate the p-values for the variable importance? Thanks very much.
Sincerely.

**Comment by mnwright** [comment]
Unfortunately not. However, it's not very difficult to implement. Do you want to use permutations or the Janitza approach for high dimensional data?

**Comment by renhuachung** [comment]
Thanks for your response. I would like to use the permutation-based method.

**Comment by mnwright** [comment]
Sorry for the delay. The code for permutation p-values is here: https://github.com/imbs-hl/ranger/blob/c70d5d4d7de25b7d9d341e1532e3cd6cb6d5cdeb/R/importance.R#L144-L160
