### ISSUE TITLE
Could not open input file. Too few columns in row 0. Are all values numeric?

### ISSUE THREAD

**Issue by ambrofos** [imbs-hl/ranger#538]
Hi  Martin - I am getting errors when working with the current version of Ranger downloaded 7/27/2020.  

I am on a MAC platform, using the c++ Ranger version: 0.12.4, which I pulled and made today, checking to make sure that all software is the latest versions.

If I call it with this 

./ranger --verbose --file iris.txt --depvarname Species --treetype 1 --probability --impmeasure 3 --write --outprefix irismodel

there no problem;  however the following call

./ranger --verbose --file iris.txt --depvarname Species --treetype 1 --probability --predict irismodel.forest --write --outprefix irismodel

produces an error

Loading input file: iris.txt.
Error: Could not open input file. Too few columns in row 0. Are all values numeric? Ranger will EXIT now.

If I use earlier Ranger versions specifically  0.11.4, or any previous version, no error results

The input file which works with Ranger  0.11.4 but  does not work with Ranger 0.12.4 is attached

[iris.txt](https://github.com/imbs-hl/ranger/files/4985618/iris.txt)

as its so small I will put it in plain text below

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
5.7 4.4 1.5 0.4 1
5.4 3.9 1.3 0.4 1
5.1 3.5 1.4 0.3 1
5.7 3.8 1.7 0.3 1
5.1 3.8 1.5 0.3 1
5.1 3.5 1.4 0.2 1
4.8 3.4 1.9 0.2 1
6.7 3.1 4.7 1.5 2
6.3 2.3 4.4 1.3 2
6.9 3.1 4.9 1.5 2
6.3 2.8 5.1 1.5 3
6.1 2.6 5.6 1.4 3
6.7 2.5 5.8 1.8 3
7.2 3.6 6.1 2.5 3
6.5 3.2 5.1 2 3

**Comment by mnwright** [comment]
It seems the current version doesn't like the `--depvarname Species` in the `--predict` call. I'll fix that but in the meantime you can just run prediction without `--depvarname Species`.

**Comment by mnwright** [comment]
Fixed.
