### ISSUE TITLE
Acquire number of observation in each node.

### ISSUE THREAD

**Issue by maksymiuks** [imbs-hl/ranger#541]
Hi,

Is there any way to acquire information about how many observation has each node seen? Additionaly, is there any way to get change in loss function after each split?

I've digged through Your documentation but didn't find any information about that.

**Comment by mnwright** [comment]
Currently, we don't save this. I think we need an (memory hungry) option to save split statistics.

**Comment by maksymiuks** [comment]
Would be awesome as split statistics are necessary for fast computations of shapley values for tree ensable models.

**Comment by mnwright** [comment]
Added in #690.
