### ISSUE TITLE
Performance issues when specifying in-bag counts with `inbag`

### ISSUE THREAD

**Issue by brfitzpatrick** [imbs-hl/ranger#544]
Hello, I'm really interested in specifying the in-bag counts for observations in large random forests but am finding such random forest very computationally expensive.  Would fitting multiple smaller random forests using `inbag` and averaging the predictions be more efficient than fitting a single large random forest using `inbag` and a number of trees equal to the total number of trees from the random forests averaged in the alternative approach?

**Comment by mnwright** [comment]
Is it slower than not using `inbag`? I think that shouldn't be the case. Could you post a reproducible example?
