### ISSUE TITLE
pairwise variable importance

### ISSUE THREAD

**Issue by MahdiSafarpour** [imbs-hl/ranger#551]
Hi,

I have just read an article about the version of the software package
ranger with the pairwise permutation importance measure. The article provides an additional file containing this version.
However, there is no information about the way this version can be installed. If you have any idea about the way I can set  "permutation importance measure" to "pairwise" in ranger, please inform me. Please note that I aim to detect interaction in my dataset. Therefore other measures for permutation importance such as "impurity" or "permutation" are not applicable.

In the following, you can find the article mentioned above:
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0995-8

**Comment by mnwright** [comment]
We did not keep that method in the package because it did not work well in the simulations. 

Here is the link to the package in the supplementary material of the paper: https://static-content.springer.com/esm/art%3A10.1186%2Fs12859-016-0995-8/MediaObjects/12859_2016_995_MOESM1_ESM.gz 

I have no idea why they renamed the file (it should be a tar.gz file). I have uploaded the file again here:  [ranger_0.1.6.33.tar.gz](https://github.com/imbs-hl/ranger/files/5970783/ranger_0.1.6.33.tar.gz)

**Comment by MahdiSafarpour** [comment]
Thanks for your reply.
Do you mean that we are not able to set "permutation importance measure" to "pairwise" in ranger!

**Comment by mnwright** [comment]
You'll have to install the package version 0.1.6.33 posted above.

**Comment by MahdiSafarpour** [comment]
Thanks for your reply. 
Could successfully install the package using the following command:
install.packages (path_to_source, repos = NULL, type="source")

**Comment by MahdiSafarpour** [comment]
As you mentioned earlier, you did not keep pairwise permutation importance measure in the package because it did not work well in the simulations. Does it mean that the results were not valid or your points refer to computational issues?
I am eager to know whether I can use this package to detect epistasis interaction or you do not recommend using this package for mentioned purpose anymore?

**Comment by mnwright** [comment]
> Does it mean that the results were not valid or your points refer to computational issues?

I wouldn't say "not valid" but we observed low power with the method, see the BMC Bioinformatic paper. It's also **very** computational if you consider all possible pairs of variables. 

> I am eager to know whether I can use this package to detect epistasis interaction or you do not recommend using this package for mentioned purpose anymore?

Currently, I cannot recommend the package (or actually the method of random forests) for this purpose. I think we would need changes to the random forest algorithm to better detect interactions. Maybe there are some newer RF-based methods available in the literature?

**Comment by MahdiSafarpour** [comment]
Thanks a lot for your valuable answers. We are working on other methods such as pRF and iRF as well. Our first priority was Ranger due to it's capability for handling big data as well as  it's power for detecting epistasis interaction. Now, it seems like that it is better to concentrate on other approaches.
