### ISSUE TITLE
variable importance by class

### ISSUE THREAD

**Issue by randomgambit** [imbs-hl/ranger#552]
Hello there! I hope all is well and thanks again for this beautiful package.

I am using `ranger` for a multi-class classification prediction and I wonder if the importance measures can tell me whether a variable is more important for discriminating one class or another. It seems that the `permutation` metrics, for instance, only returns one numerical value (the importance) for each variable even though I have many different classes. Instead, I would like to know the best variables to predict class 1, the best to predict class 2 and so on.

What do you think?
Thanks!

**Comment by mnwright** [comment]
You could use local variable importance, e.g.: 
````R
library(ranger)
rf <- ranger(Species ~ ., iris, importance = "permutation", 
             local.importance = TRUE)
rf$variable.importance.local
````

and then summarize by class, e.g.:
````R
colMeans(rf$variable.importance.local[iris$Species == "setosa", ])
colMeans(rf$variable.importance.local[iris$Species == "versicolor", ])
colMeans(rf$variable.importance.local[iris$Species == "virginica", ]
````
or with data.table or the like.

**Comment by randomgambit** [comment]
very interesting, thanks! did you come up with the measure or there is an academic paper about it?

**Comment by mnwright** [comment]
See #273 for discussions and #439 and #444 for implementation details. In #273 there is also a link to a publication.
