### ISSUE TITLE
scaled permutation

### ISSUE THREAD

**Issue by YingxiaLiu** [imbs-hl/ranger#558]
How the scaled permutation did and why?

**Comment by YingxiaLiu** [comment]
ranger(... scale.permutation.importance = FALSE)

**Comment by mnwright** [comment]
This scales the variable importance by the standard error over the trees. The idea is to make the variable importance comparable across different RF runs or datasets. However, some people reported problems with the scaling (see e.g. https://www.zeileis.org/papers/Strobl+Zeileis-2008.pdf) so I would recommend the unscaled importance.

**Comment by YingxiaLiu** [comment]
Thanks for the explanation. This really removed my doubts and let me breathe a sigh of relief.
