### ISSUE TITLE
Prediction error of new (test) data for survival models

### ISSUE THREAD

**Issue by CYGUBICKO** [imbs-hl/ranger#560]
In survival setting, is there a way to obtain the prediction error (1-C) for the test data (new data after fitting the model)? For example

library(ranger)
library(survival)
fit <- ranger(Surv(time, status)~., data = veteran)
I can get prediction error (1-C) from fit but suppose I do prediction using a new data set and I want to get the associated error?

new_data <- veteran[1:20, ]
pred <- predict(fit, data = new_data)

**Comment by mnwright** [comment]
You could use 

````R
Hmisc::rcorr.cens(rowSums(pred$chf), Surv(new_data$time, new_data$status))["C Index"]
````

Without `1-` because you compare the chf (hazard) with survival. 

But there are many implementations in different packages I think.

**Comment by edwoodbrice** [comment]
Hi @mnwright, do you mind sharing the names of the packages [that you were thinking of here](https://github.com/imbs-hl/ranger/issues/560#issuecomment-831124396)? I am familiar with survival::survConcordance() (now deprecated) and the survival::concordance() function that superseded that, but I haven't come across others that are compatible with ranger model objects. 

Doing what you suggested with Hmisc::rcorr.cens() works, but I was curious about the other implementations. Thank you!
