### ISSUE TITLE
mtry

### ISSUE THREAD

**Issue by YingxiaLiu** [imbs-hl/ranger#569]
Why you set sqrt (number of explanary variables), not 3/1 of number of explanary variables as mtry?

**Comment by mnwright** [comment]
To have the same default for all outcomes.

**Comment by YingxiaLiu** [comment]
But 1/3 can also make the same default for all outcomes. Why sqrt?

**Comment by mnwright** [comment]
No specific reason. We had to choose something and it's not entirely clear which value would be the best default.
