### ISSUE TITLE
Suggestion - combining ranger objects (ie. pooling forests together)

### ISSUE THREAD

**Issue by alenxav** [imbs-hl/ranger#572]
I have a minor suggestion for the package - a function to combine ranger objects, to pool two forests together.
 (below I wrote a simple example that would work).

c.ranger = function(f1,f2){
  f3 = f1
  f3$num.trees = f1$num.trees + f2$num.trees
  f3$prediction.error = c(f1$prediction.error,f2$prediction.error)
  f3$r.squared = c(f1$r.squared,f2$r.squared)
  f3$num.samples = c(f1$num.samples,f2$num.samples)
  f3$replace = c(f1$replace,f2$replace)
  f3$forest$num.trees = f1$forest$num.trees+f2$forest$num.trees
  f3$forest$child.nodeIDs = c(f1$forest$child.nodeIDs,f2$forest$child.nodeIDs)
  f3$forest$split.varIDs = c(f1$forest$split.varIDs,f2$forest$split.varIDs)
  f3$forest$split.values = c(f1$forest$split.values,f2$forest$split.values)
  return(f3)}

Example:
model1 = ranger(y~.,df1)
model2 = ranger(y~.,df2)
model3 = c(model1, model2)

###

Why bother implementing that?

1) Lazy loading - to fit models where the data does not fit in memory and it is split into different files (or something like an hdf5). Thus, we can fit a small set of trees in subsets of the entire data, keep merging the smaller forests, and looping over the entire dataset to get "epochs".

2) In some genetic analysis (genomic prediction), the random forest approach does great at capturing population structure but it performs poorly at capturing LD and cosegregation, consequently, it has bad performance on the within-subpopulation basis. However, that can be remediated by training smaller forests within subpopulations. So having a function that combines forests together would enable that.

3) That would also enable some boosting of a sort, by training sequentially and using the residuals from the current set of trees to reweight the observations for the next set of trees.

**Comment by mnwright** [comment]
See #356. A PR with such a function would be welcome.
