### ISSUE TITLE
save.memory

### ISSUE THREAD

**Issue by GoulongWang** [imbs-hl/ranger#584]
Hi, I am a newbie in ranger. Recently I studied the paper "ranger: A Fast Implementation of Random Forests for High Dimensional Data in C++ and R" and I have a question. I want to know how does ranger reduce memory usage with save.memory option?  I've read the document about `save.memory` and it says "This option slows down the tree growing, use only if you encounter memory problems."

![image](https://user-images.githubusercontent.com/23274642/128464092-8d1fb93d-0042-4470-8ada-6e3210b2af47.png)

But I want to know how the code work. So which part of the source code can anyone suggest me to read about my question? 
I will appreciate your help!

**Comment by mnwright** [comment]
The `save.memory` option disables pre-sorting and consequently uses only the splitting algorithm which does not need pre-sorted data. To see the code, best search for `memory_saving_splitting`: https://github.com/imbs-hl/ranger/search?p=2&q=memory_saving_splitting&type=
