### ISSUE TITLE
Inconsistency in the numbering of splitVarIDs

### ISSUE THREAD

**Issue by animusnaturae** [imbs-hl/ranger#588]
Let's start with a small random forest:

```
set.seed(0)
rf <- ranger(Species ~ .
             , data = iris
             , write.forest=TRUE # default
             , num.trees = 20
             # , probability = T
)
```

If you want to extract which variables a certain tree uses, you can use two ways. 
Either by extracting it from the function treeInfo: 
```
sort(unique(treeInfo(rf, 1)$splitvarID))
```
Leading to the splitvarIDs 0, 2, 3, since leafs use NA as splitvarIDs

Or you try to extract them directly by the splitvarIDs object in the forest:
```
sort(unique(rf$forest$split.varIDs[[1]]))
```
Now you get also 0 because here leafs are coded with 0, but the first splitting variable is also coded with 0.
You can see this by comparing both lists for the second tree:
```
treeInfo(rf, 2)$splitvarID
 > 3 NA  0  2  2 NA NA NA NA
rf$forest$split.varIDs[[2]]
 > 3 0 0 2 2 0 0 0 0
```

**Comment by mnwright** [comment]
A 0 in `split.varIDs` is not a sufficient condition for splitting at variable 0 or a terminal node, you have to check `child.nodeIDs`. `treeInfo()` does this check for you and gives NA to the terminal nodes.
