### ISSUE TITLE
Returning NaN reproducible example

### ISSUE THREAD

**Issue by portolan75** [imbs-hl/ranger#589]
Hi @mnwright , I think I have a reproducible example that display how the issue highlighted in #201 is still an issue. 

Took me a while, because it happens when dealing with imbalanced data, when the imbalance ratio is below a certain threshold
I'm very happy with the speed and capabilities of ranger but unfortunately I can't use much due to this problem.
_The idea in general is to balance the bagged sample within the chosen samplesize._

Here's the reproducible example.

> Data for reproducible example
> data(mtcars)
> table(mtcars$am)
> class(mtcars)
> 
> Create a heavy class imbalance situation (can be even more heavy in reality)
> Make am my variable to predict as.factor (classification)
> mtcars$am[1:30] <- 0
> mtcars$am <- as.factor(mtcars$am)
> table(mtcars$am)
> 
> Calculate weights to assign to each obs. to re-balance the sample to 50% each class.
> (think of it when it's really class-imbalanced and this weights are more extreme)
> w_am = 1/table(mtcars$am)
> w_am = w_am/sum(w_am)
> weights_am <- ifelse(mtcars$am %in% 0, w_am[1], w_am[2])
> 
> Replicate 20 times
> OOB_RMSE_W <- vector(mode = "numeric", length = 20)
> for(i in seq_along(OOB_RMSE_W)) {
>   
>   train model
>   optimal_ranger_w <- ranger(
>     formula         = am ~ ., 
>     data            = mtcars,
>     num.trees       = 500,
>     mtry            = 7,
>     min.node.size   = 3,
>     sample.fraction = .8,
>     splitrule       = "gini",
>     classification  = TRUE,
>     probability     = TRUE, 
>     importance      = "impurity",
>     replace         = TRUE,
>     case.weights    = weights_am,
>     keep.inbag      = TRUE
>   )
>   
>   add OOB error to grid
>   OOB_RMSE_W[i] <- sqrt(optimal_ranger_w$prediction.error)
> }
> which(is.na(optimal_ranger_w$predictions))

_Originally posted by @portolan75 in https://github.com/imbs-hl/ranger/issues/201#issuecomment-952858886_

**Comment by mnwright** [comment]
Let's continue in #201.
