### ISSUE TITLE
how does ranger generate tree when the training data has missing value？

### ISSUE THREAD

**Issue by A-Pai** [imbs-hl/ranger#590]
how does ranger generate tree when the training data has missing value？

**Comment by mnwright** [comment]
Not at all, it should give an error.

**Comment by A-Pai** [comment]
> Not at all, it should give an error.

--you mean ranger can not handle dataset with missing value？

**Comment by mnwright** [comment]
Yes, you'll have to handle missing values externally, e.g. with `Hmisc::impute()` or `mice::mice()`. Another alternative might be [missRanger](https://cran.r-project.org/package=missRanger).
