### ISSUE TITLE
Cross compilation for Windows 

### ISSUE THREAD

**Issue by shaikthouheed** [imbs-hl/ranger#596]
Hi I am trying to cross compile for Windows.
But I am facing issues with compilation. Could you provide the latest binaries please.

**Comment by mnwright** [comment]
I've released Windows binaries here: https://github.com/imbs-hl/ranger/releases/tag/v0.13.1

Also #598 fixed the cross compilation on Ubuntu 20.04 for me.

**Comment by shaikthouheed** [comment]
@mnwright Thanks.
