### ISSUE TITLE
Error in rangerCpp(treetype, x, y.mat, independent.variable.names, mtry, :

### ISSUE THREAD

**Issue by prithvimenon** [imbs-hl/ranger#603]
My colleague and I were trying to train a Boruta model using the following snippet : 

    library(Boruta)

    # Set seeding number for reproducibility
    set.seed(1234)

    # Train Boruta Model
    trainmodel <- Boruta([dependent variable]~., data=[dataset], doTrace=2, maxRuns=50)
    
    # Each iteration of importance stats
    importance_stats <- as.data.frame(trainmodel$ImpHistory)

and whilst it ran fine for me, my colleague got the following error : 

`Error in rangerCpp(treetype, x, y.mat, independent.variable.names, mtry,: `

My laptop currently still has version 0.12.1 for ranger whereas my colleague has the latest version 0.13.1 . Noticed that you updated ranger to 0.13.1 a few months ago and didn't know why the new version would cause the workflow to error.

**Comment by mnwright** [comment]
Could you provide a reproducible example? I cannot reproduce the error.
