### ISSUE TITLE
Issues with S3 exports

### ISSUE THREAD

**Issue by courtiol** [imbs-hl/ranger#610]
Hi Marvin,

I have problem in a package I am creating which rely on ranger.
My problem stems from S3 function from ranger not being exported.
This is easy to reproduce: for example, `ranger::predict.ranger` yields no result (while `ranger:::predict.ranger` reveals the non-exported function).
I am mystified because I did check your code and what Roxygen did based on your `@export calls`, and you do have the proper declaration of the export in your NAMESPACE file.
So I don't understand what's going on but there is an issue somewhere...
What do you think?
Alex

**Comment by courtiol** [comment]
I understood: Roxygen turn the @export into "S3method(predict,ranger)" only but does not create the "export(predict.ranger)" that would be needed in the NAMESPACE file.
I will check if this is bug or feature in Roxygen, and how to come around that.

**Comment by courtiol** [comment]
https://github.com/r-lib/roxygen2/issues/1322

**Comment by mnwright** [comment]
Seems to be fine according to https://github.com/r-lib/roxygen2/issues/1322.
