### ISSUE TITLE
what is the point of "scale.permutation.importance = TRUE" in function ranger ?

### ISSUE THREAD

**Issue by A-Pai** [imbs-hl/ranger#613]
what is the point of "scale.permutation.importance = TRUE" in function ranger ?

**Comment by mnwright** [comment]
That's mostly there for compatibility with `randomForest`. It was suggested to use that for statistical testing but is has been shown that it's a bad idea.

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  Li Gang
