### ISSUE TITLE
R crashing while using ranger to classify 1 GB raster tif

### ISSUE THREAD

**Issue by krispj** [imbs-hl/ranger#614]
Hi, I'm trying perform vegetation classification on a raster composite '.tif' file of around 1GB size using ranger / random forest, and R session aborts while trying to classify. I'm using Windows 64 bit and 32GB RAM.  My code works on a smaller subset of the file. Any solutions? Thanks!

**Comment by mnwright** [comment]
Are you running out of memory? Can you create a reproducible example?

**Comment by mnwright** [comment]
I think NA or Inf shouldn't be the problem. Aborted R session and that it works on smaller subset still sounds like memory problems, but it's hard to say without being able to reproduce.

**Comment by krispj** [comment]
Thanks, looks like it was memory issues. I was able to run it after splitting the raster into smaller bits.
