### ISSUE TITLE
Case Specific Random Forests function (csrf): problem in weights calculation

### ISSUE THREAD

**Issue by jmm34** [imbs-hl/ranger#615]
Dear Marvin,

I have a concern with your code associated to the Case Specific Random Forests method. I think the following line (used for the calculation of the weights of the training dataset) does not return the right answer.

num.same.node <- rowSums(terminal.nodeIDs.test[i, ] == terminal.nodeIDs.train)

Here is a toy example that shows the problem

set.seed(1974)
x1 <- rnorm(100)
x2 <- rnorm(100)
x3 <- rnorm(100)
y <- 3*x1+x2^2+exp(x3)+12+rnorm(100)
training <- data.frame(y,x1,x2,x3)
test <- data.frame(x1=rnorm(1),x2=rnorm(1),x3=rnorm(1))
rf.proximity <- ranger(y~., data = training, write.forest = TRUE, num.trees = 10, num.threads = 10, keep.inbag = TRUE )
terminal.nodeIDs.train <- predict(rf.proximity, training, 
                                  type = "terminalNodes")$predictions
terminal.nodeIDs.test <- predict(rf.proximity, test, 
                                 type = "terminalNodes")$predictions
res <- rowSums(terminal.nodeIDs.test[1, ] == terminal.nodeIDs.train)
res[3]
lulu <- sum(terminal.nodeIDs.test[1, ]==terminal.nodeIDs.train[3, ])

res[3] and lulu are not equal!

I think the corrected version should be

res_cor <- rowSums(matrix(rep(terminal.nodeIDs.test[1, ],100),100,10,byrow=TRUE) == terminal.nodeIDs.train)
res_cor[3]
sum(terminal.nodeIDs.test[1, ]==terminal.nodeIDs.train[3, ])

Thank you very much for your answer,
Best regards,

Jean-Michel

**Comment by mnwright** [comment]
Good catch, thanks. I think this should also work: 
`colSums(terminal.nodeIDs.test[i, ] == t(terminal.nodeIDs.train))`

**Comment by jmm34** [comment]
Thank you Marvin, do you plan to submit a corrected version to the CRAN or an updated GitHub version?
Best regards,
Jean-Michel

**Comment by mnwright** [comment]
Fixed.
