### ISSUE TITLE
estimated RAM for DNA methylation set (tweet from june 20)

### ISSUE THREAD

**Issue by lorbaer** [imbs-hl/ranger#625]
Hi,
I'm currently working with 850K methylation array data for 72 samples.
So far I used the method from this [nature paper](https://www.nature.com/articles/nature26000)

> For efficient computation, the probes were split into 43 sets of approximately 10,000 probes. For each set, 100 trees were fitted using 654 randomly sampled candidate features at each split (mtry parameter, square root of 428,799, as would be used by default when not splitting into sets).[..]his procedure was repeated 100 times, essentially fitting 10,000 trees per probe. Finally, features are selected by the permutation-based variable importance measure[..]We selected features by ranking them using the minimal rank of the variable importance measures across all classes.

In short: Divide the set, calculate, combine the best outcomes, calulate again

After reading your tweet https://twitter.com/MarvinNWright/status/1538776353641836545 I have read your paper about the advantages of ranger and wanted to give it a try.
After some prefiltering steps I'm down to ~330k , therefore your tweet was a perfect fit. 
 
However my first try stopped with an "cannot allocate vector of 406GB" error. 
Is this in the expected range and/or is there a way to lower the memory used? I have seen the save.memory option and will give it a try. 

Could you tell me about the memory size and running time you needed for the stated 383,000 features?

cheers

**Comment by mnwright** [comment]
There shouldn't be much memory overhead, definitely not 400GB. When using the right interface and `save.memory=TRUE` there should be almost no memory overhead (<1GB) I think. Two things to try:
1. Use an interface that avoids copying the data. In recent ranger versions this is `ranger(y = y, x = x, ...)`. Don't use the formula interface for high-dimensional data. 
2. Use `save.memory=TRUE`. But this will slow down in some cases, use with care.

**Comment by lorbaer** [comment]
Hi,
thanks for the fast answer and the super-fast ranger package!
Changed from formula to x,y as you suggest. 
No memory problems at all and super fast results. Absolute bliss! Even 731k CpGs aren't any kind of a problem.

best

**Comment by mnwright** [comment]
We definitively need a warning when the formula interface is used with high-dimensional data, as suggested in #516.
