### ISSUE TITLE
treeInfo prediction has wrong class labels depending on class levels

### ISSUE THREAD

**Issue by mkb007** [imbs-hl/ranger#626]
Thanks for producing one of the best packages in R. 

The following shows a defect and its fix for the prediction data produced by treeInfo().

    library(ranger)
    rf <- ranger(dependent.variable.name = "Species", data = iris, num.trees = 1, sample.fraction = 1, replace = FALSE)
    ti <- treeInfo(rf)
    psNodes <- as.vector(predict(rf, data = iris, type = "terminalNodes")$predictions)
    # TRUE as expected
    show(all(ti$prediction[psNodes + 1] == iris$Species))

    # permute the iris data
    irisPerm <- rbind(iris[51:150,], iris[1:50,])
    rf <- ranger(dependent.variable.name = "Species", data = irisPerm, num.trees = 1, sample.fraction = 1, replace = FALSE)
    ti <- treeInfo(rf)
    psNodes <- as.vector(predict(rf, data = irisPerm, type = "terminalNodes")$predictions)
    # FALSE is *not* expected
    show(all(ti$prediction[psNodes + 1] == irisPerm$Species))

    # tiP is the fixed ti$prediction factor 
    tiP <- factor(factorCodes <- as.integer(ti$prediction), labels = rf$forest$levels[rf$forest$class.values])
    show(all(tiP[psNodes + 1] == irisPerm$Species))

**Comment by mnwright** [comment]
Thanks, fixed.
