### ISSUE TITLE
Install ranger on server

### ISSUE THREAD

**Issue by PhilippPro** [imbs-hl/ranger#63]
Hi, 

I want to install ranger on a server, but I get following error: 
```
I/home/hpc/ua341/di49ruw/R/lib64/R/include -DNDEBUG -DR_BUILD -I/usr/local/include -I"/home/hpc/ua341/di49ruw/R/lib64/R/library/Rcpp/include"      -c AAA_check_cpp11.cpp -o AAA_check_cpp11.o
/bin/sh: I/home/hpc/ua341/di49ruw/R/lib64/R/include: Datei oder Verzeichnis nicht gefunden
```
And many more times the error, that it does not exist. In fact only R/include exists and not R/lib64.
Can I solve this error somehow?

**Comment by mnwright** [comment]
Strange. Is this only the case for `ranger`? What about other `Rcpp` packages, such as `dplyr`?

**Comment by rmflight** [comment]
If it is a server running something like CentOS, it could be interesting getting stuff compiled properly that uses `Rcpp`. I haven't debugged all our issues, but I know one needs a very particular setup to properly compile `Rcpp` stuff on CentOS.

**Comment by PhilippPro** [comment]
Installing `dplyr` via `devtools::install_github(cran/dplyr)`  is not a problem. I use `devtools::install_github(cran/ranger)` and this normally works.

**Comment by mnwright** [comment]
Which version of gcc is running on the server? 

By the way, why do you install CRAN packages using `devtools::install_github`?

**Comment by PhilippPro** [comment]
gcc 4.9.3

Normal installation does not work because of some reason. (I am a very recent user of the server structure) But that is not the reason.

**Comment by mnwright** [comment]
Is this solved on your side?

**Comment by PhilippPro** [comment]
Yes. It was solved by setting 

CXX_STD = g++
CXX=g++
PKG_CPPFLAGS= -std=c++11 -DRBUILD

in the ranger/src/Makevars file. But I think Bernd has written you more about this.

**Comment by mnwright** [comment]
Great. He said they solved it locally without modifying the ranger Makevars (CXX shouldn't be set in a package).
