### ISSUE TITLE
Why do NAN and 0 appear when the argument is SE for function predict?

### ISSUE THREAD

**Issue by A-Pai** [imbs-hl/ranger#635]
library(ranger)

ames <- as.data.frame(AmesHousing::make_ames())
set.seed(111)
I <- sample(nrow(ames), nrow(ames) * 0.99)
rf <- ranger(Sale_Price ~ ., data = ames[I, ], keep.inbag = TRUE, seed = 111)
pred1 <- predict(rf, ames[-I, ], type = "se") # se.method="infjack"(default)
pred2 <- predict(rf, ames[-I, ], type = "se", se.method = "jack")

cat(pred1$se)
cat("\n\n")
cat(pred2$se)
![image](https://user-images.githubusercontent.com/5112397/184500377-0effd820-769a-4d7f-96cd-a4929560f2e6.png)

**Comment by mnwright** [comment]
#633
