### ISSUE TITLE
about the reproducibility of predictions

### ISSUE THREAD

**Issue by UnixJunkie** [imbs-hl/ranger#637]
I have some trained regressor models from about two years ago.
If I run them today, on the same test data (though on a different computer, with a different version of the OS), I don't get exactly the same results.
There is a very high correlation between the predictions (R2 ~= 0.97), but they are not exactly the same.
Is this a known phenomenon?
Are there known ways to avoid this in the future?
E.g. I should have put everything into a VM and stored this instead of just the trained models.

**Comment by mnwright** [comment]
Is one of the OS's a Mac? See #533.

**Comment by UnixJunkie** [comment]
No, it was all on Ubuntu Linux.

**Comment by UnixJunkie** [comment]
I was pretty annoyed by this at the time: if a stored model cannot reproduce exactly past predictions, this is bad.
If you need to freeze all software present on the computer along with the saved model, this is really inconvenient.

**Comment by mnwright** [comment]
I think that shouldn't happen when both systems run Ubuntu. Would you mind sharing a reproducible example and some more info on the systems?

**Comment by UnixJunkie** [comment]
I can share with you privately one of those models.
As for the systems, I only have access to the new one.

Are we supposed to fix a random seed at prediction time?

**Comment by mnwright** [comment]
To be clear: The only problem in reproducibility is between Mac and other systems, see #533. If anyone encounters another problem, please re-open.

**Comment by UnixJunkie** [comment]
Great! Thanks for the fix!
