### ISSUE TITLE
Tree-wise probabilities are based on OOB or all training instances?

### ISSUE THREAD

**Issue by blenback** [imbs-hl/ranger#645]
I'm sorry if this is a simple question or it has already been anwsered but there is one detail I am not certain of from reading the function documentation/code/other issues

When using predict.ranger() on test data with a probability type ranger model in a binary classifcation setting, I understand that the tree-wise prediction probabilities are calculated from the relative proportions of the true values of the training data in the terminal node that the test instance arrives in for each tree. 

What I am unsure of is: are these training instances only the out of bag instances (i.e. similar to what is returned by model$predictions)  or are they all instances (both in and out of bag) from the training data (the equivalent to calling the predict() function on the training data) ? 

I am interested in calculated entropy-based measures of uncertainty for point predictions and so I am interested in the latter i.e. probablisitic predictions calculated from all instances of the training data.

**Comment by mnwright** [comment]
Only the in-bag data is used to calculate the probabilities in the leaves. Out-of-bag data is not used at all in the training.
