### ISSUE TITLE
Performance Evaluation of Models

### ISSUE THREAD

**Issue by DarioS** [imbs-hl/ranger#646]
Could there be some discussion of predictive model evaluation added to the documentation? For example, would `rowSums(predictions$survival)` and C-index for model comparison be a good idea or is something else recommended?

**Comment by mnwright** [comment]
See #560 and #617. I think a full discussion of evaluation is beyond the scope of the documentation. But we could add more details on how the C-index is calculated internally.

**Comment by DarioS** [comment]
> But we could add more details on how the C-index is calculated internally.

Yes, please. It seems to be a popular request now that I see the other questions.

**Comment by mnwright** [comment]
Done in #701.
