### ISSUE TITLE
split candidates

### ISSUE THREAD

**Issue by markusloecher** [imbs-hl/ranger#653]
What is the default for the candidate splits that the tree split algorithm (exhaustively) searches over ?
I am assuming that it is either

1. the (n-1) unique values of the predictor(s) in the respective node
2. their midpoints, or
3. a grid which can be defined via quantiles
4. a combination of the above: a grid for large node sample sizes and unique values for smaller nodes

The latter would lead to a computational speedup for large N?
If option 3 is supported, can we specify the size of the grid.

Thanks!

**Comment by mnwright** [comment]
It's 2. (midpoints). We should definitely implement what you suggest, i.e. histogram splitting. See also #258.
