### ISSUE TITLE
Error: Missing data in columns: predictor1, predictor2....

### ISSUE THREAD

**Issue by nikosGeography** [imbs-hl/ranger#662]
I performed a regression task at a coarse spatial resolution and I wanted to make predictions at a finer spatial scale. When I use the function `predict(model, newdata)` I am getting this error: `Error: Missing data in columns: pop030, tirs030, road030, ndvi030 `(pop030, tirs030 and ndvi030 are some of my predictors). I tried solutions like:

1. `p = predict(m2$model, newdata = as.data.frame(s), na.rm = TRUE)`
2. `p = predict(ft$model, newdata = as.data.frame(s), na.action = na.omit)`
3. `p = predict(ft$model, newdata = as.data.frame(s), na.action = na.exclude)`
But none seems to work.

Basically, for the prediction, I converted my fine resolution rasters to a `data.frame` in order to passed it to the `predict `argument.
How can I use the `predict `function to create a fine spatial resolution raster of my target variable (it's called _ntl_)?

Here is the code:
```
library(ranger)
library(tuneRanger)
library(mlr)
library(terra)

wd = "path/"

# data.frame containing the variables at the coarse spatial scale (null values were removed)
block.data = read.csv(paste0(wd, "block.data.psf.csv"))

# keep the target variable and some predictors
block.data = subset(block.data, select = c(ntl, pop030, tirs030, agbh030, 
                                           road030, ndvi030, red030, 
                                           blue030, nir030, swir030))

# default ranger model
m1 <- ranger(ntl ~., 
             data = block.data, 
             importance = 'impurity', 
             min.node.size = 5)
print(m1)

#tuning
set.seed(123)
tune_model = makeRegrTask(data = block.data, target = "ntl")
m2 = tuneRanger(tune_model, measure = list(rsq), iters = 70, 
                num.threads = 15, num.trees = 1000, 
                parameters = list(replace = FALSE, 
                                  respect.unordered.factors = "order"))

m2
m2$model

# predictors at a fine spatial resolution
pop = rast(paste0(wd, "pop.tif"))
tirs = rast(paste0(wd, "tirs.tif"))
agbh = rast(paste0(wd, "agbh.tif"))
ndvi = rast(paste0(wd, "ndvi.tif"))
poi = rast(paste0(wd, "poi.tif"))
road = rast(paste0(wd, "road.tif"))
red = rast(paste0(wd, "red.tif"))
blue = rast(paste0(wd, "blue.tif"))
nir = rast(paste0(wd, "nir.tif"))
swir = rast(paste0(wd, "swir.tif"))

s = c(pop, tirs, agbh, road, ndvi, red, blue, nir, swir)
names(s) = c('pop030', 'tirs030', 'agbh030', 'road030', 'ndvi030', 'red030', 
             'blue030', 'nir030', 'swir030')

p = predict(ft$model, newdata = as.data.frame(s), na.rm = TRUE)
```

**Comment by mnwright** [comment]
ranger does not handle missing values yet. You'll have to exclude/impute your missing values outside of ranger.
