### ISSUE TITLE
Incorrect bounds check in beta log probability

### ISSUE THREAD

**Issue by stephematician** [imbs-hl/ranger#663]
https://github.com/imbs-hl/ranger/blob/407dc5853814d371d6d7363f0a87c6b3e3df6fdb/src/utility.cpp#L682

Seems like a very tiny corner case but the check should be `else if(phi > ...)`

**Comment by mnwright** [comment]
Thanks, good catch.

**Comment by stephematician** [comment]
In fact, that check should be ditched altogether, I forgot there isn't any upper limit on phi.
