### ISSUE TITLE
`ranger()` finished, but `rsession` is still running

### ISSUE THREAD

**Issue by kadyb** [imbs-hl/ranger#665]
I have a problem with training a probability model. After training, the model is returned in the environment, but the `rsession` process is still running and is blocking RStudio. In the `probability = FALSE` case everything works fine.

```r
library("ranger")
n = 10000
class = factor(c("A", "B", "C"))
df = data.frame(class = sample(class, n, replace = TRUE),
                x1 = rnorm(n))
mdl = ranger(class ~ x1, df, probability = TRUE)
```

<details>
<summary>Session Info</summary>

```
RStudio 2023.03.0 Build 386

R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ranger_0.14.1

loaded via a namespace (and not attached):
[1] compiler_4.1.2  Matrix_1.4-0    tools_4.1.2     rstudioapi_0.14 Rcpp_1.0.10    
[6] grid_4.1.2      lattice_0.20-45
```

</details>

**Comment by mnwright** [comment]
Hm... I cannot reproduce (on Ubuntu 20.04). Anyone else?

**Comment by kadyb** [comment]
Did you also try running this example on RStudio (Server) 2023.03.0 Build 386? In the R console, this problem does not occur for me.

**Comment by mnwright** [comment]
Just tried, works fine also with RStudio Server 2023.03.0 Build 386 on Ubuntu 20.04.

**Comment by stephematician** [comment]
On Ubuntu you could run a debugger like GDB i.e. from a terminal:

```
R -d gdb --vanilla
(gdb) run
```

Then paste your code, run it, and once its finished (or even if it doesn't) press `ctrl` + `c` to get back to the debugger and check what threads are lying around:

```
(gdb) info threads
```

I get the expected output (one thread):

```
  Id   Target Id                             Frame 
* 1    Thread 0x7ffff7ec5c40 (LWP 80863) "R" 0x00007ffff771b7ed in __GI___select (nfds=1, readfds=0x7ffff7ec02c0, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ../sysdeps/unix/sysv/linux/select.c:69
```

If it didn't finish, you could also check where the program is held up via:

```
(gdb) where
```

**Comment by kadyb** [comment]
I can't reproduce this in the R terminal. Maybe it is possible to debug this thread in RStudio somehow?

![rstudio](https://user-images.githubusercontent.com/35004826/229524391-401dcb7e-7f5f-4b2f-8f3d-a80a3584760f.png)

**Comment by stephematician** [comment]
Probably not the issue here .... but I think ranger could stuck in the progress display loop if all the worker-threads throw exceptions (and fail) before the progress loop releases the mutex (and waits for notifications - which will never arrive). However, I've yet to encounter this in practise.

**Comment by mnwright** [comment]
Please re-open if necessary.
