### ISSUE TITLE
Trying to spatially predict(type="se")$se and the output has many null values and what look like spatial offsets?

### ISSUE THREAD

**Issue by KWB4484** [imbs-hl/ranger#668]
In short, I've trained regression models for 20 ecological units across the US by mapping this function to nested training datasets for each unit. Example:
```
train%>%
  mutate(fit = future_map(data, ~ ranger(y ~ x1+x2...,num.trees=500, data = .x, keep.inbag=TRUE,importance='impurity',min.node.size=10), .options = furrr_options(seed = 44)))%>%
  {.->>EcoModels}  
```
I then create a raster stack of covariates, I join ecological unit boundaries to the "EcoModels" tibble and essentially map a function where for each row the raster stack gets crop/masked using the ecological unit boundary, the model is applied to the raster stack and the output is written to disk. 

```
 for(i in 1:nrow(EcoModels)){
  filename<-paste("./Out/UnitTL01_",EcoModels$UnitName[[i]], ".tiff",sep="")
  ras<-raster::crop(ras_stack,extent(EcoModels$unit_boundary[[i]]))
  ras<-raster::mask(ras,EcoModels$unit_boundary[[i]])
  out<-predict(ras, EcoModels$fit[[i]], type='se', progress='window', fun = function(model, ...) predict(model, ...)$se)
  writeRaster(out, filename=filename, datatype='FLT4S', overwrite=TRUE)
  removeTmpFiles(h=0.001)
}
```
This worked well for response predictions, but my computer ran out of memory when trying to get standard errors. Luckily, I was just given the opportunity to use a computer with a ridiculous amount of RAM and I got it to run....but the output had lots of null values and spatial chunks that look like some offset was applied.

I checked the raster stack and it appears fine. Is there something that I'm doing wrong or is this normal because of xyz? Thanks for any ideas you can provide for troubleshooting this.

Standard Errors
![image](https://user-images.githubusercontent.com/80982349/230397578-da63eade-c070-4477-9791-35c9bffcb8ee.png)

Response predictions
![Layout3](https://user-images.githubusercontent.com/80982349/230404209-83f5fae7-38b3-4c78-89d8-292571afd787.png)

Units
![image](https://user-images.githubusercontent.com/80982349/230398721-2db534af-8a42-46dd-b33d-277028d27de8.png)

Example SE for one unit
![image](https://user-images.githubusercontent.com/80982349/230399362-459d2e53-975a-4ec3-a21b-ce2521ded863.png)

**Comment by rvalavi** [comment]
I had the same issue @KWB4484! I solved it by converting the raster to data.frame. But the bigger problem was that my raster is so big (more than 111 million cells) so I had to tile it and do this in parallel. While doing that realized the "se" calculating varies between the tiles!!!!

**Comment by KWB4484** [comment]
Thanks for the suggestion @rvalavi! I'll give it a try. I'm assuming you can retain xy and convert it back to raster after calculating the standard errors? Fingers crossed I have enough memory.

**Comment by rvalavi** [comment]
My pleasure, @KWB4484!
Yes, you need xy to convert back to raster. But the main issue is that predicting se with a model on two datasets with different lengths produces different results (even if one is just a subset of the other and you have set a random seed)! I need to read its paper and check the code in more detail to see what is the issue. It might be something in the proposed method but ideally, it shouldn't be like that!

The model fitting with ranger is fantastic with very little RAM requirement, but I wish the prediction would have been the same story.

**Comment by mnwright** [comment]
See also #136. Also consider quantile regression or the forestError package?

**Comment by KWB4484** [comment]
@rvalavi Well I tried going the data.frame route but I'm in the same boat -- too big --  

> "Error in .local(x, y, ...) :  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102"

 and given your experience with tiling I'll just quit now. Thanks for saving me time! 

Thanks @mnwright, I'll try the forestError package.
