### ISSUE TITLE
Poor handling of character string predictors

### ISSUE THREAD

**Issue by jgellar** [imbs-hl/ranger#673]
I have a predictor in my model that is a character string. I noticed this issue when I tried to compute the marginal effect of the predictor, as follows:

```
mod <- fit(Y ~ ., data = dat)

dat0 <- dat %>%
    mutate(myvar = "A")
dat1 <- dat %>%
    mutate(myvar = "B")
preds0 <- predict(mod, dat0)
preds1 <- predict(mod, dat1)
identical(preds0$predictions, preds1$predictions)   # TRUE!
```
After a lot of banging my head against a wall, I think what is happening is that `ranger` is turning the character predictor into a factor before fitting the model. Then when I want to predict, it turns `dat0$myvar` and `dat1$myvar` into factors, but since these variables don't have all the same levels as the original variable used to fit the model, it is assuming that both of them are the lowest level.

This is a very subtle error. Yes, of course it could have been avoided if I made the variable a factor to begin with, but I think there are better ways for `ranger` to handle string predictors. At the very least it should keep track of the levels of a factor variable, so that if someone wants to make a prediction, it can convert the string to a factor with the same levels.

**Comment by mnwright** [comment]
Thanks. Could you please make a reproducible example out of this?

**Comment by jgellar** [comment]
If it wasn't clear from the example, `s` is a character variable. If you predict on a data.frame that only has one value for the character string, the predictions will be identical regardless of what value you use. Here, the predictions for `datB` are made as if the value for `s` is `"A"`, even though we set it to `"B"`. I believe this is because ranger turns `datB$s` into a factor, and since the only level is `"B"`, it is predicting as if this is the first level of the original factor.

I believe the solution would be for `ranger` to keep track of the levels of all the factors in the original data that was used to fit the model.

**Comment by mnwright** [comment]
Which version are you using? I get FALSE in the `identical(pA, pB)` line. But I think there was a related bug which was fixed in version 0.15.1. 

Also I guess you want to do `rbind()` instead of `cbind()` in the `pAB <- ... ` line?

**Comment by mnwright** [comment]
> I believe the solution would be for `ranger` to keep track of the levels of all the factors in the original data that was used to fit the model.

That's exactly what we are doing but it was missing for characters in previous versions. See also #627 and #628.

**Comment by jgellar** [comment]
Ah, I'm using 0.14.1, that explains it. Glad you already fixed the issue!

And yes, I meant `rbind` :-)
