### ISSUE TITLE
make fails => cannot compile C++ source on Mac

### ISSUE THREAD

**Issue by plark42** [imbs-hl/ranger#675]
I get the following error when I run cmake and then make.  Please advise.  Thanks!

build> cmake ..
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.4 is not supported by CMake >= 3.0.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

Compiler with C++14 support found.
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/fac_rubin/Downloads/ranger-master/cpp_version/build
build> make
**[  6%] Building CXX object CMakeFiles/ranger.dir/src/main.o
/Users/fac_rubin/Downloads/ranger-master/cpp_version/src/main.cpp:59:96: error: too few arguments to function call, expected 31, have 30
      arg_handler.randomsplits, arg_handler.maxdepth, arg_handler.regcoef, arg_handler.usedepth);
                                                                                               ^
/Users/fac_rubin/Downloads/ranger-master/cpp_version/src/Forest/Forest.h:41:8: note: 'initCpp' declared here
  void initCpp(std::string dependent_variable_name, MemoryMode memory_mode, std::string input_file, uint mtry,
       ^
1 error generated.
make[2]: *** [CMakeFiles/ranger.dir/src/main.o] Error 1
make[1]: *** [CMakeFiles/ranger.dir/all] Error 2
make: *** [all] Error 2**
build>

**Comment by denisld** [comment]
I'm seeing this exact issue, also on Mac.

**Comment by mnwright** [comment]
Thanks, fixed.
