### ISSUE TITLE
num.threads causing crashes inside caret recursive feature elimination wrapper

### ISSUE THREAD

**Issue by jcherzig** [imbs-hl/ranger#680]
Hi, 
I have implemented ranger inside the caret RFE wrapper function. This works perfectly on my Mac OS machine locally - however, when I run this in parallel using the Parallel package on my university computer cluster, ranger is spawning additional sub-processes beyond the number of cores specified.

I thought this would be an easy fix by setting `num.threads=1` to prevent each iteration of ranger generating its own sub-processes; however, when I try this I get the following error:
`Error in { : task 1 failed - "Stopping"`
`Calls: rfe ... rfe.default -> nominalRfeWorkflow -> %op% -> <Anonymous>`

This second error seems to be a generic error that RFE always throws when interrupted while running in parallel.

I found this similar issue but I have ensured I am setting num.threads for every call of the ranger function (`train`, `predict` and  `importance_pvalues`) and I still get the same error:
https://github.com/imbs-hl/ranger/issues/339

Here is an example of the code which implements and runs ranger inside caret's RFE wrapper, I am not sure this will be reproducible as it works fine on my machine but on my university computing cluster it is causing problems:
```R
require(caret)
require(caTools)
require(ranger)
require(doParallel)

# get number of cores from environment variable set in jobscript
numCoresAllowed <- as.numeric(Sys.getenv("MC_CORES", unset=1))

# implement ranger inside helper function to pass to RFE
rangerFuncs <- list(
  fit=function(x, y, first, last, ...) {
    out <- train(x, y,
                 method="ranger",
                 importance = if(first) "impurity" else "none",
                 metric="AUC",
                 # write.forest=T,
                 trControl=trainControl(method="repeatedcv",
                                        number=10,
                                        repeats=20,
                                        classProbs=TRUE,
                                        savePredictions = TRUE,
                                        verboseIter=TRUE,
                                        summaryFunction=prSummary),
                 tuneGrid = expand.grid(
                   .mtry = round(seq(from=2,to=ncol(x),length.out=if((ncol(x))==5) {
                     4
                   } else {
                     5
                   })),
                   .splitrule = "extratrees",
                   .min.node.size = 1
                 ),
                 # tuneLength=n.hparam.iter,
                 num.threads=1,
                 ...)
    return(out$finalModel)
  },
  pred=function(object, x) {
    out <- as.data.frame(predict(object, data=x, type="response",num.threads=1)$predictions)
    out$pred <- factor(colnames(out)[apply(out,1,which.max)], levels=sort(colnames(out)))
    rownames(out) <- rownames(x)
    return(out)
  },
  rank=function(object, x, y) {
    varimps <- as.data.frame(ranger::importance_pvalues(object, method="altmann",
                                                        formula=y~.,num.threads=1, data=as.data.frame(cbind(y,x))))
    #varimps <- as.data.frame(importance_pvalues, method="janitza")
    varimps$var <- colnames(x)
    varimps <- varimps[order(varimps$importance, decreasing=TRUE),]
    colnames(varimps)[[1]] <- "Overall"
    return(varimps)
  },
  selectSize=pickSizeBest,
  selectVar=pickVars,
  summary=prSummary
)

# define rfe control object
RFctrl <- rfeControl(functions = rangerFuncs,
                     method = "repeatedcv",
                     number=10,
                     repeats=20,
                     returnResamp = "all",
                     verbose = T)


# create list of subset sizes to try
subsets <- c(5,10,15,20,30,40)

# set up parallel cluster
cl <- makePSOCKcluster(numCoresAllowed)
registerDoParallel(cl)

rfProfile <- rfe(predictors, outcomes, sizes = subsets, rfeControl = RFctrl)
stopCluster(cl)
```
Do you have any idea why the `num.threads=1` call is causing problems inside the RFE wrapper?

Thanks for your help, and apologies if I've made an obvious mistake. I'm not very experienced in parallel computing so it's very possible I'm missing something!

UPDATE:
I have now tried passing the `num.threads=1` argument inside the rfe call rather than in the function where I define the calls to ranger, e.g.
```R
rfProfile <- rfe(predictors, outcomes, sizes = subsets, rfeControl = RFctrl, n.threads=1)
```

This seems to mostly alleviate the issue - however, I still get spikes of very high load with additional subprocesses spawning. I suspect this approach may prevent the training step from using additional cores but one of the additional ranger functions (`predict` or `importance_pvalues`) is still trying to multithread separately. 
In the rfe documentation it specifies that additional options are passed to the model fitting function which suggests to me they may only be passed to the train portion of the helper function and not the predict and rank portions.

UPDATE 2: I have now added the `num.threads=1` argument back to the `predict` and `importance_pvalues` functions but not the `train` call (as this should be inheriting the argument from the wrapper). This no longer causes the original error and all functions that call ranger should now be using 1 thread only so I'm hopeful this has fixed the issue. I still don't understand why setting `num.threads=1` directly for `train`, `predict` and `importance_pvalues` caused crashes though, possibly some strange interaction with the parallelisation of the `rfe` wrapper?

**Comment by mnwright** [comment]
I'm not sure what is exactly hapenning in `rfe` and if we have a problem in ranger. I guess the spikes before your last update were coming from `predict()` not being set to `num.threads=1`. 

We now finally got rid of the old Rtools and could make the change indicated in https://github.com/imbs-hl/ranger/issues/339#issuecomment-409884801, but I'm not sure if that fixes anything for this problem.
