### ISSUE TITLE
Decision Tree Build

### ISSUE THREAD

**Issue by DarioS** [imbs-hl/ranger#689]
It would be useful to compare a random forest against a simple decision tree for accuracy differences. Would this be achieved by:

- `num.trees = 1`
- `mtry = ncol(data)` (Variables are columns)
- `replace = FALSE`
- `sample.fraction = 1`.

If so, it might be helpful to state that somewhere in the documentation.

**Comment by mnwright** [comment]
Yes, that's correct. I agree that we should add this to the docs.

**Comment by mnwright** [comment]
Done in #701.
