### ISSUE TITLE
Random forest prediction intervals using the out-of-bag predictions errors.

### ISSUE THREAD

**Issue by nikosGeography** [imbs-hl/ranger#693]
Firstly I'd like to thank you for the creation of the package. This is not an issue rather a suggestion, feel free to delete this post if you think it has no place here.

I know that `ranger` has an implementation for quantile random forest (QRF) by setting the argument `quantreg = TRUE` in the `ranger` function. Yesterday I came accross the paper of Zhang et al., (2020) [Random Forest Prediction Intervals](https://www.tandfonline.com/doi/10.1080/00031305.2019.1585288). They proposed a method based on the empirical distribution of the out-of-bag predictions errors. Through simulations and the analysis of real data sets, they found that the intervals constructed using their method have coverage rates close to the nominal levels and tend to be narrower than competing methods such as QRF.

If you think that their method worth your attention that's good to hear, otherwise you can ignore the post.

Looking forward to your comments on this.

**Comment by mnwright** [comment]
Isn't that approach implemented in the [`rfinterval` package](https://github.com/haozhestat/rfinterval)? Maybe it would make sense to include that (or parts of it) in ranger?

**Comment by nikosGeography** [comment]
I apologize I just found this as well (https://github.com/haozhestat/RFIntervals) where the authors mention rhe package.
