### ISSUE TITLE
Is there a way to fit an isolation forest using ranger?

### ISSUE THREAD

**Issue by S-AQ** [imbs-hl/ranger#694]
Hi, 
Thank you for your package. 

I was wondering whether it would be possible to fit an [isolation forest](https://dl.acm.org/doi/abs/10.1145/2133360.2133363) by tweaking some parameters in the existing functions. 

An isolation forest is meant to detect anomalies by keeping track of the data that leaves the regression tree at the first split. Conceptually, I think it might not be so hard to implement, but I am not so familiar with the ins and outs of this package. 

Looking forward to your answer.

**Comment by mnwright** [comment]
No, we don't have that implemented in ranger. What about [isotree](https://github.com/david-cortes/isotree)?
