### ISSUE TITLE
Add C++14 specification (`std::make_unique` is only avaiable from C++14 onwards)

### ISSUE THREAD

**Issue by fenguoerbian** [imbs-hl/ranger#705]
When I try to install the package from the source, I got the error message that 

> `std::make_unique` is only avaiable from C++14 onwards

Now that the package is switched to C++14 standards, I suggest to add some requirement in the package to indicating a use of C++ complier at least C++14.

Maby in DESCRIPTION

> SystemRequirements: C++14

Or specify the C++ standard in src/Makevars (and even src/Makevars.win)

> CXX_STD = CXX14

These are recommended in [Writing R extensions](https://cran.r-project.org/doc/manuals/R-exts.html#:~:text=%5D%5BIndex%5D-,1.2.4%20Using%20C%2B%2B%20code,-R%20can%20be)

**Comment by mnwright** [comment]
See #669. 

But I just noted that they do write 

> This is also good practice for a requirement of C++14.

For what is described above. I think that was different when the change to C++14 was made by CRAN. So we'll probably change this. 

Note to myself: Also require R 3.4.0.

**Comment by fenguoerbian** [comment]
Thanks.
