### ISSUE TITLE
Matrices without colnames.

### ISSUE THREAD

**Issue by SamGG** [imbs-hl/ranger#708]
Hi,
I use ranger with matrices and I get the "Error: No covariates found." error.
In fact, my matrices don't have colnames, so the variable names are not defined.
https://github.com/imbs-hl/ranger/blob/dcaee8ddce8598466c2a40da345605041506996b/R/ranger.R#L367
I think there should be a check here to compare the length of colnames(x) and ncol(x) and either raise an error or initialize the colnames with some values.
Let me know if it's unclear.
Best.

**Comment by mnwright** [comment]
See #597.

**Comment by SamGG** [comment]
Thanks for your feedback. My bad, I didn't find it. I continue on #597.
