### ISSUE TITLE
Clarify Gini index calculation

### ISSUE THREAD

**Issue by anya-mueller** [imbs-hl/ranger#714]
To Whom it may concern,

I asked for the return of node stats from my ranger random forest classification model. When examining these in individual trees (retrieved with treeInfo) I found that I wasn't able to calculate the splitStat with the Gini formula : 1-(p1)^2-(p2)^2, where p1 is the probability of my first factor and p2 is the probability of my second factor (ie pred.0 and pred.1 in the treeinfo data frame). So I am wondering what is the Gini index that is used in ranger random forest. 

I used "permutation" to calculate variable importance, does this alter the splitStat used in the forest?

Thank you for you time and help.

Cheers,
Anya

**Comment by snembrini** [comment]
Hi Anya,
permutation importance is computed after the forest is built, so no it does not change the splitStat

when splitrule="gini" , splits are computed using the "empirical Gini Gain": you have to compute the impurity before splitting minus the sum of the impurity of the left and right nodes (weighted by the samples size)
I am not sure if by "factor" you mean "class": the gini index in a single node is two times the relative frequency of 1's multiplied by it's complement, i.e., 2*p*(1-p): @mnwright can confirm what formula is actually used 

SplitStat provided by treeInfo is just the cutoff for that given Predictor a that specific split: as far as I know the only way to obtain the Impurity value (which is the Gini impurity in case splitrule="gini") is to extract it $variable.importance after setting importance = "impurity", but that is the average across the forest

**Comment by mnwright** [comment]
For splitting, we want to maximize the Gini index. Some terms of the Gini index calculation are constant over possible splits of a node and are thus not calculated in the maximization. These values without the constant terms end up in `treeInfo()`, while the full Gini index is used for the impurity importance (calculated in this function: https://github.com/imbs-hl/ranger/blob/24a24bf7034d70a894a472e2f895c09488aa04f9/src/TreeClassification.cpp#L801).
