### ISSUE TITLE
Identifying out-of-bag observations for each tree

### ISSUE THREAD

**Issue by michaelgordy** [imbs-hl/ranger#717]
What is the correct way to identify the rows of a training sample that are out-of-bag for a given tree?  I expected that `rf$inbag.counts[[j]]==0` would return a vector of indices of out-of-bag rows for tree `j`.  It doesn't seem to work. 

Consider the following example of random forest regression using the Boston data:

```library(ranger)
data("Boston", package="MASS")
Boston$chas <- as.logical(Boston$chas)  # fix a small problem
rf <- ranger(medv ~ ., Boston, num.trees=200, keep.inbag=TRUE)
y1 <- predictions(rf) 
y2 <- predict(rf, Boston, inbag.counts=rf$inbag.counts) |> predictions() 

updatePredictions <- function(rf, data) { # Try to manually recreate regression predictions
  stopifnot(rf$treetype=="Regression")
  yy <- nn <- rep(0,nrow(data))
  for (j in 1:rf$num.trees) {
    oob <- rf$inbag.counts[[j]]==0  # vec length nrow(data)
    nn[oob] <- nn[oob]+1
    yy[oob] <- yy[oob] + predict(rf, data[oob, ])$predictions
  }
  yy/nn
}
y3 <- updatePredictions(rf, Boston)
```

I find that `y2` and `y3` are the same, but they differ from `y1`.  Either I misunderstand the identification of oob observations or I misunderstand the construction of `rf$predictions`.

**Comment by michaelgordy** [comment]
Thank you!  Is there any guidance on manual construction of `rf$variable.importance`?

**Comment by mnwright** [comment]
Here is an example (with groups of features, but that can be easily changed): https://github.com/imbs-hl/ranger/issues/403#issuecomment-481732062

**Comment by michaelgordy** [comment]
Thank you!
