### ISSUE TITLE
consistent errors with ranger on MacBook Pro Sonoma 14.1.1

### ISSUE THREAD

**Issue by michael-menke** [imbs-hl/ranger#720]
Trying to get AUC, sensitivity, specificity between 3 classes of 71 variables each. Using Rstudio version Version 2023.12.1+402 (2023.12.1+402), R version 4.4.0 (2024-04-24) -- "Puppy Cup". Tried multiple work arounds and get this message: pd_om_roc <- roc(pd_om_selected_data$PD_vs_OM, pd_om_probabilities)
Setting levels: control = PD, case = OM
Error in roc.default(pd_om_selected_data$PD_vs_OM, pd_om_probabilities) : 
  Predictor must be numeric or ordered.
Error during wrapup: argument "e" is missing, with no default
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
> pd_om_auc <- auc(pd_om_roc)
Error: object 'pd_om_roc' not found
Error during wrapup: argument "e" is missing, with no default
Error: no more error handlers available (recursive errors?); invoking 'abort' restart. 

Data: 
[masterDat.csv](https://github.com/imbs-hl/ranger/files/15142233/masterDat.csv)

Code: 

# For Level 1 (HE vs. not)
he_predictions <- predict(he_final_model, data = he_selected_data)
he_probabilities <- predict(he_final_model, data = he_selected_data, type = "response")$predictions

# Convert HE_vs_not to a numeric variable (0 and 1)
he_selected_data$HE_vs_not_numeric <- as.numeric(he_selected_data$HE_vs_not == 1)

library(ranger)

# Evaluate model performance using ranger's internal functions
he_eval <- ranger:::evaluateSurvivalPerformance(he_probabilities, he_selected_data$HE_vs_not_numeric)

# Extract AUC
he_auc <- he_eval$auc

# Extract sensitivity and specificity at the optimal threshold
he_sensitivity <- he_eval$sensitivity[which.max(he_eval$specificity + he_eval$sensitivity)]
he_specificity <- he_eval$specificity[which.max(he_eval$specificity + he_eval$sensitivity)]

# Print the results
cat("Level 1: HE vs. not\n")
cat(paste("AUC:", round(he_auc, 3), "\n"))
cat(paste("Sensitivity:", round(he_sensitivity, 3), "\n"))
cat(paste("Specificity:", round(he_specificity, 3), "\n"))

**Comment by mnwright** [comment]
There is no `ranger:::evaluateSurvivalPerformance`. Can you give a reproducible example?
