### ISSUE TITLE
Multicollinearity and Variable Importance

### ISSUE THREAD

**Issue by lukasmackin** [imbs-hl/ranger#727]
I apologize if this is not the proper place for this question, for it is more theoretical and pertains tangentially to the package. 

Can anybody explain how the permuted variable importance measure deals with multicollinearity? It seems that highly correlated predictors would have their importance understated. But since permuted variable importance is widespread, I assume that there must be some justification for why multicollinearity is a non-issue. 

Any insights are appreciated. Thanks in advance!

**Comment by mnwright** [comment]
PFI doesn't really deal with multicollinearity. That means, variable importance is split up among correlated features and you cannot adjust for confounders with PFI. An alternative is conditional variable importance. See e.g., the "cpi" package on CRAN or on Github here: https://github.com/bips-hb/cpi 

Also here are two of our papers on the topic: 

- Blesch et al. 2023: "Conditional feature importance for mixed data" https://doi.org/10.1007/s10182-023-00477-9 
- Ewald et al. 2024: "A guide to feature importance methods for scientific inference" https://arxiv.org/abs/2404.12862

**Comment by lukasmackin** [comment]
Thanks so much for the answer and resources!
