### ISSUE TITLE
Question about Calculation of Feature Importance in Regression

### ISSUE THREAD

**Issue by Tan-Jiahua** [imbs-hl/ranger#732]
Hi,

The documentation of the ranger says: "The ’impurity’ measure is ... the variance of the responses for regression", and I noticed that there has already been relevant discussion about the description. (https://github.com/imbs-hl/ranger/issues/489)

I think when using importance = 'impurity' for regression, the calculation of the variable importance of features (variable.importance) in the class ranger is related to the decrease in variances of the response from splitting the corresponding variable. How is the reduction of variances in different nodes across different trees summarized into a single value for each feature? Could you please tell me about that?

I found a description from another package describing this process (total decrease in node impurities from splitting on the variable, averaged over all trees), but I am unsure if the ranger implements it similarly.

Thank you!

**Comment by mnwright** [comment]
See #489.
