### ISSUE TITLE
parameter "class.weights" for  cost sensitive learning does not work

### ISSUE THREAD

**Issue by A-Pai** [imbs-hl/ranger#741]
parameter "class.weights" for  cost sensitive learning does not work:

library(pacman)
p_load(ranger, AppliedPredictiveModeling, skimr)
s <- skim_tee

data(abalone)
ab <- abalone
ab$Rings <- factor((ab$Rings) > 12, labels = c("L", "H"))

set.seed(100)
i <- sample(nrow(ab), nrow(ab) * 0.5)
tr_ab <- ab[i, ]   #for train
te_ab <- ab[-i, ]  #for test
s(tr_ab)

![image](https://github.com/user-attachments/assets/c09f9687-006f-4bd6-96d2-f30d227a5ae9)

(levels(tr_ab$Rings))
![image](https://github.com/user-attachments/assets/8b2d758d-3116-4c1c-97bc-e18de3eac6ff)

set.seed(711)
(rg_ab <- ranger(Rings ~ .,  data = tr_ab, class.weights = c(1,1)))
(table(te_ab$Rings, predict(rg_ab, te_ab, type = "response")$predictions))

![image](https://github.com/user-attachments/assets/43bae267-4225-402a-92c8-edbc856e251a)

set.seed(711)
(rg_ab1 <- ranger(Rings ~ .,  data = tr_ab, class.weights = c(1,5)))
(table(te_ab$Rings, predict(rg_ab1, te_ab, type = "response")$predictions))

![image](https://github.com/user-attachments/assets/01ffe099-1b69-49f7-a9c5-530243b8b99c)

when the  "class.weights" is changed to c(5,1) the table is hardly changed

**Comment by mnwright** [comment]
Try a larger `min.node.size` (or smaller `max.depth` etc.). With the default for classification, there will be only one observation in most leaves and class weights cannot make much difference in the majority voting.

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  LI,Gang

**Comment by A-Pai** [comment]
yes ，a larger min.node.size works，thanks for your guide，but parameter "class.weights"  also affects the splitting of internal nodes

**Comment by mnwright** [comment]
That's true, but it seems in this example this doesn't make much of a difference.
