### ISSUE TITLE
What's the point of compute variable importance with p-values?

### ISSUE THREAD

**Issue by A-Pai** [imbs-hl/ranger#742]
What's the point of compute variable importance with p-values?--function " importance_pvalues"
Is it for us to have a “natural cutoff”? which is the significance level？Just like the paper “Acomputationally fast variable importance test for random forests for high-dimensional data” said：
![image](https://github.com/user-attachments/assets/6f8a46d8-ebb0-4087-a122-0a2cfd69c64b)

**Comment by mnwright** [comment]
Yes, exactly. One might argue that p-values also need a cut-off value, but at least those are easier interpretable than variable importance values.
