### ISSUE TITLE
How can I add a custom distance metric in the tree construction process in C++?

### ISSUE THREAD

**Issue by Lakesenberg** [imbs-hl/ranger#755]

**Comment by mnwright** [comment]
See #368.

**Comment by Lakesenberg** [comment]
Where can I add self-definition distance into c++source files?

发自我的iPhone


------------------ Original ------------------
From: Marvin N. Wright ***@***.***&gt;
Date: Mon,Dec 16,2024 6:51 PM
To: imbs-hl/ranger ***@***.***&gt;
Cc: Lakesenberg ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [imbs-hl/ranger] How can I add a custom distance metric in thetree construction process in C++? (Issue #755)





 
See #368.
