### ISSUE TITLE
Question on how to pass "split.select.weights"

### ISSUE THREAD

**Issue by mayer79** [imbs-hl/ranger#78]
Hi rangers

I am unsure how the probabilities in "split.select.weights" are associated with the regressors. It it based on the order they are appearing in the formula? Or is "split.select.weights" simply a named numeric vector in any order?

Thanks for clarification.

**Comment by mnwright** [comment]
It is in the order they are appearing in the formula (or the data if no formula used). The names of `split.select.weights` are ignored. 

I'll keep this open, should add it to the docs.

**Comment by mayer79** [comment]
Great, thanks a lot.

**Comment by mnwright** [comment]
Added to docs.
