### ISSUE TITLE
Ranger will not compile with Intel C++ compiler due to a custom Mersenne Twister use

### ISSUE THREAD

**Issue by mbq** [imbs-hl/ranger#8]
Ranger uses [C++11 feature N3551](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2013/n3551.pdf), which is not implemented (and probably will never be) by Intel compilers, causing compilation error. When uses as an R package, it probably should rather use R PRNG infrastructure which is exposed by Rcpp, like [here](http://gallery.rcpp.org/articles/stl-random-shuffle/).

**Comment by aussetg** [comment]
What is the Intel Compiler lacking? Just the Mersenne twister or the whole C++11 random feature?

**Comment by mbq** [comment]
As I wrote, the whole feature is absent.

**Comment by mnwright** [comment]
Is this solved with version 16? See also #92.

**Comment by mnwright** [comment]
Closed. Please reopen if not solved.
