### ISSUE TITLE
Multithreading on Windows

### ISSUE THREAD

**Issue by rfcv** [imbs-hl/ranger#80]
The main page says:

_Note that, for now, R-devel and the new RTools toolchain is required for multithreading on Windows platforms (or install a binary version)._

I installed the current R-devel version (3.4.0), and the current RTools version (34), so the `num.threads` parameter of `ranger` should immediately work. But the function still runs on only one processor. Is there more that is required? Maybe you could expand on the instructions to make multithreading work on Windows as many of your users are likely interested in this functionality.

**Comment by mnwright** [comment]
Which ranger version are you using? Windows multithreading is available since 0.4.2 and is not on CRAN yet. I hope to submit a new version this week, including the feature.

**Comment by rfcv** [comment]
I was using the version currently on CRAN (version 0.4.0). After installing version 0.4.2 from Github, the multithreading works on Windows. Thanks for this feature.

**Comment by mnwright** [comment]
Included in CRAN version since 0.5.0.
