### ISSUE TITLE
Enhancement: num.trees for predict

### ISSUE THREAD

**Issue by rfcv** [imbs-hl/ranger#91]
If a `num.trees` parameter for `predict` is implemented to limit the number of trees for prediction, it makes it very easy to choose the right number of trees for a model, because one can grow a very large tree and then scale back the number of trees based on what the predictions are telling them.

**Comment by rfcv** [comment]
Otherwise, you could implement a function that prunes an object of class `ranger` (a ranger model) to a desired tree (or a selected vector of trees like function `selectTrees` in package `extraTrees`) or a function that grows a ranger model beyond what exists currently, like `grow` in `randomForest`. All of these would accomplish the same task, although I think `grow` is the best due to the ability to stop when test accuracy decays.

**Comment by rfcv** [comment]
@mnwright 
Tell me if this hack is effective at limiting the number of trees used for `predict`.
Say I grow a model to 500 trees. Then I want to make predictions using only 250 trees. I manually set `model$forest$num.trees=250` after growing the model. Does this accomplish the task?

**Comment by mnwright** [comment]
Adding a `num.trees` option to `predict()` is a good idea. I will add it when I'm back in the office in mid August. 

Meanwhile your hack should work fine. As an alternative you could set `predict.all = TRUE` in `predict()` and compute manual majority votes or averages on a subset of the trees.

**Comment by mnwright** [comment]
Done.
