### ISSUE TITLE
ranger wont compile with Intel 15 compilers

### ISSUE THREAD

**Issue by gshamov** [imbs-hl/ranger#92]
Compilation with the Intel 15.0.5 compiler (icpc -std=c++11)

Ends with error :

AAA_check_cpp11.cpp(3): error: #error directive: Error: ranger requires a real C++11 compiler. You probably have to update gcc.
  #error Error: ranger requires a real C++11 compiler. You probably have to update gcc.
   ^

Is it a real problem or all Intel compilers are now banned?

**Comment by mnwright** [comment]
I have no idea. I hope I'll find time to try the Intel compiler in August. 

Is [this](https://software.intel.com/en-us/articles/build-r-301-with-intel-c-compiler-and-intel-mkl-on-linux) still the way to do it?

**Comment by mnwright** [comment]
I just installed the intel compiler (16.0.3) in a Ubuntu 14.04 VM and built R 3.3.1 with it. ranger installs and runs fine. I also tried the pure C++ version and it seems to work fine, too. 

Is this solved with version 16 or is it something different?

**Comment by mnwright** [comment]
Closed. Please reopen if not solved.

**Comment by mbq** [comment]
I can confirm it builds with intel 16.

**Comment by mbq** [comment]
Although, I cannot get across this check against `__cplusplus` you make [here](https://github.com/imbs-hl/ranger/blob/master/ranger-r-package/ranger/src/AAA_check_cpp11.cpp#L2)... For my icpc (v 16.0.2) it is just `1`.

**Comment by boro2013** [comment]
Hi everyone,
I'm working on a cluster, and have installed R on my home directory. When I tried to install ranger i got the following error:
AAA_check_cpp11.cpp:3:2: error: #error Error: ranger requires a real C++11 compiler, e.g., gcc >= 4.7 or Clang >= 3.0. You probably have to update your C++ compiler.
make: *** [AAA_check_cpp11.o] Error 1
ERROR: compilation failed for package ‘ranger’

Linux release: CentOS release 6.9
processor: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz

I've no idea how to fix this issue.

**Comment by mnwright** [comment]
Try `gcc --version` to check your gcc version.

**Comment by boro2013** [comment]
I've installed a new version of gcc on my home directory, and now it works fine, thank u

**Comment by larsplus** [comment]
Hi, I manage my gcc version using ~/.R/Makevars where I set 
CC=/path/to/gcc-4.9.1
CXX=path/to/g++-4.9.1
but I get the same error; does ranger ignore ~/.R/Makevars and use the default gcc instead?

**Comment by mnwright** [comment]
Try 
````
CXX1X=/path/to/g++
````
