### ISSUE TITLE
probabilities ranger vs. randomForest

### ISSUE THREAD

**Issue by PhilippPro** [imbs-hl/ranger#96]
hi,

I just wanted to link to this interesting question on stackoverflow to different behaviour of ranger and randomForest when predicting probabilities:

http://stats.stackexchange.com/questions/226109/how-does-predict-randomforest-estimate-class-probabilities

Maybe somebody can answer it.

**Comment by mnwright** [comment]
Thanks for the link, I've posted an answer there.
