### ISSUE TITLE
Is there a way to correctly pass a big.matrix instance into ranger?

### ISSUE THREAD

**Issue by winbaram1000** [imbs-hl/ranger#99]
I need to train over 100GB dataset of 3600columns. 
After I read this(http://stackoverflow.com/questions/8315575/big-matrix-as-data-frame-in-r),I tried same method for ranger. but it  didn't work.

**Comment by mnwright** [comment]
Shared memory, disk caching or similar approaches are not supported in `ranger` and probably won't in the near future.
